# Discriminant Analysis with categorical variables (DISCQUAL)

In [1]:
# Chargement des librairies
import numpy as np
import pandas as pd

vote = pd.read_excel("./data/Data_Illustration_Livre_ADL.xlsx",sheet_name="VOTE",header=0)
vote.head()

        group adop_budget edu_spending  adop_n  adop_u  edu_n  edu_u
0  republican           n            y       1       0      0      0
1  republican           n            y       1       0      0      0
2    democrat           y            n       0       0      1      0
3    democrat           y            n       0       0      1      0
4    democrat           y            u       0       0      0      1

In [2]:
vote = vote[["group","adop_budget","edu_spending"]]
vote.head()

        group adop_budget edu_spending
0  republican           n            y
1  republican           n            y
2    democrat           y            n
3    democrat           y            n
4    democrat           y            u

In [3]:
X = vote[["adop_budget","edu_spending"]]
X.head()

  adop_budget edu_spending
0           n            y
1           n            y
2           y            n
3           y            n
4           y            u

In [4]:
from scientisttools.discriminant_analysis import DISCQUAL

In [5]:
disqual = DISCQUAL(n_components=None,
                    target=["group"],
                    features_labels=["adop_budget","edu_spending"],
                    row_labels=X.index)
disqual.fit(vote)

DISCQUAL(features_labels=['adop_budget', 'edu_spending'],
         row_labels=RangeIndex(start=0, stop=435, step=1), target=['group'])

In [7]:
pd.DataFrame(disqual.mod_coord_)

            0         1         2         3
0   -1.225629  0.198996  0.045177  0.007335
1   -1.225629  0.198996  0.045177  0.007335
2    0.856446  0.233447  0.067482  0.024687
3    0.856446  0.233447  0.067482  0.024687
4    0.464659 -1.721369 -1.887334 -0.367100
..        ...       ...       ...       ...
430 -0.193267  0.205069  0.039103 -1.025026
431  0.856446  0.233447  0.067482  0.024687
432 -1.225629  0.198996  0.045177  0.007335
433 -1.225629  0.198996  0.045177  0.007335
434 -1.225629  0.198996  0.045177  0.007335

[435 rows x 4 columns]