# Multiple Factor Analysis (MFA)

In [1]:
#changement de dossier
import os
os.chdir("d:/Bureau/PythonProject/packages/scientisttools/data/")

#importation des données
import pandas as pd
url = "http://factominer.free.fr/factomethods/datasets/wine.txt"
wine = pd.read_table(url,sep="\t")
wine.head()

,Label,Soil,Odor.Intensity.before.shaking,Aroma.quality.before.shaking,Fruity.before.shaking,Flower.before.shaking,Spice.before.shaking,Visual.intensity,Nuance,Surface.feeling,...,Acidity,Astringency,Alcohol,Balance,Smooth,Bitterness,Intensity,Harmony,Overall.quality,Typical
2EL,Saumur,Env1,3.074,3.000,2.714,2.280,1.960,4.321,4.000,3.269,...,2.107,2.429,2.500,3.250,2.731,1.926,2.857,3.143,3.393,3.250
1CHA,Saumur,Env1,2.964,2.821,2.375,2.280,1.680,3.222,3.000,2.808,...,2.107,2.179,2.654,2.926,2.500,1.926,2.893,2.964,3.214,3.036
1FON,Bourgueuil,Env1,2.857,2.929,2.560,1.960,2.077,3.536,3.393,3.000,...,2.179,2.250,2.643,3.321,2.679,2.000,3.074,3.143,3.536,3.179
1VAU,Chinon,Env2,2.808,2.593,2.417,1.913,2.160,2.893,2.786,2.538,...,3.179,2.185,2.500,2.333,1.680,1.963,2.462,2.038,2.464,2.250
1DAM,Saumur,Reference,3.607,3.429,3.154,2.154,2.040,4.393,4.036,3.385,...,2.571,2.536,2.786,3.464,3.036,2.071,3.643,3.643,3.741,3.444

In [2]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, 2EL  to T2
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Label                          21 non-null     object
 1   Soil                           21 non-null     object
 2   Odor.Intensity.before.shaking  21 non-null     float64
 3   Aroma.quality.before.shaking   21 non-null     float64
 4   Fruity.before.shaking          21 non-null     float64
 5   Flower.before.shaking          21 non-null     float64
 6   Spice.before.shaking           21 non-null     float64
 7   Visual.intensity               21 non-null     float64
 8   Nuance                         21 non-null     float64
 9   Surface.feeling                21 non-null     float64
 10  Odor.Intensity                 21 non-null     float64
 11  Quality.of.odour               21 non-null     float64
 12  Fruity                         21 non-null     float64
 13  Flower                         21 non-null     float64
 14  Spice                          21 non-null     float64
 15  Plante                         21 non-null     float64
 16  Phenolic                       21 non-null     float64
 17  Aroma.intensity                21 non-null     float64
 18  Aroma.persistency              21 non-null     float64
 19  Aroma.quality                  21 non-null     float64
 20  Attack.intensity               21 non-null     float64
 21  Acidity                        21 non-null     float64
 22  Astringency                    21 non-null     float64
 23  Alcohol                        21 non-null     float64
 24  Balance                        21 non-null     float64
 25  Smooth                         21 non-null     float64
 26  Bitterness                     21 non-null     float64
 27  Intensity                      21 non-null     float64
 28  Harmony                        21 non-null     float64
 29  Overall.quality                21 non-null     float64
 30  Typical                        21 non-null     float64
dtypes: float64(29), object(2)
memory usage: 5.2+ KB

In [3]:
df1 = wine.iloc[:,:2]
df1.head()

           Label       Soil
2EL       Saumur       Env1
1CHA      Saumur       Env1
1FON  Bourgueuil       Env1
1VAU      Chinon       Env2
1DAM      Saumur  Reference

In [4]:
df2 = wine.iloc[:,2:7]
df2.head()

,Odor.Intensity.before.shaking,Aroma.quality.before.shaking,Fruity.before.shaking,Flower.before.shaking,Spice.before.shaking
2EL,3.074,3.000,2.714,2.280,1.960
1CHA,2.964,2.821,2.375,2.280,1.680
1FON,2.857,2.929,2.560,1.960,2.077
1VAU,2.808,2.593,2.417,1.913,2.160
1DAM,3.607,3.429,3.154,2.154,2.040

In [5]:
df3 = wine.iloc[:,7:10]
df3.head()

      Visual.intensity  Nuance  Surface.feeling
2EL              4.321   4.000            3.269
1CHA             3.222   3.000            2.808
1FON             3.536   3.393            3.000
1VAU             2.893   2.786            2.538
1DAM             4.393   4.036            3.385

In [6]:
df4 = wine.iloc[:,10:20]
df4.head()

,Odor.Intensity,Quality.of.odour,Fruity,Flower,Spice,Plante,Phenolic,Aroma.intensity,Aroma.persistency,Aroma.quality
2EL,3.407,3.308,2.885,2.320,1.840,2.000,1.650,3.259,2.963,3.200
1CHA,3.370,3.000,2.560,2.440,1.739,2.000,1.381,2.962,2.808,2.926
1FON,3.250,2.929,2.769,2.192,2.250,1.750,1.250,3.077,2.800,3.077
1VAU,3.160,2.880,2.391,2.083,2.167,2.304,1.476,2.542,2.583,2.478
1DAM,3.536,3.360,3.160,2.231,2.148,1.762,1.600,3.615,3.296,3.462

In [7]:
df5= wine.iloc[:,20:29]
df5.head()

,Attack.intensity,Acidity,Astringency,Alcohol,Balance,Smooth,Bitterness,Intensity,Harmony
2EL,2.963,2.107,2.429,2.500,3.250,2.731,1.926,2.857,3.143
1CHA,3.036,2.107,2.179,2.654,2.926,2.500,1.926,2.893,2.964
1FON,3.222,2.179,2.250,2.643,3.321,2.679,2.000,3.074,3.143
1VAU,2.704,3.179,2.185,2.500,2.333,1.680,1.963,2.462,2.038
1DAM,3.464,2.571,2.536,2.786,3.464,3.036,2.071,3.643,3.643

In [8]:
from scientisttools.decomposition import PCA

pca1 =PCA(normalize=True,n_components=3,row_labels=wine.index,col_labels=df2.columns).fit(df2)
eig1 = pca1.eig_[0]
eig1.round(2)

array([2.24, 1.52, 0.82])

In [9]:
pca2 =PCA(normalize=True,n_components=3,row_labels=wine.index,col_labels=df3.columns).fit(df3)
eig2 = pca2.eig_[0]
eig2.round(2)

array([2.83, 0.15, 0.01])

In [10]:
pca3 =PCA(normalize=True,n_components=3,row_labels=wine.index,col_labels=df4.columns).fit(df4)
eig3 = pca3.eig_[0]
eig3.round(2)

array([4.7 , 2.48, 1.05])

In [11]:
pca4 =PCA(normalize=True,n_components=3,row_labels=wine.index,col_labels=df4.columns).fit(df5)
eig4 = pca4.eig_[0]
eig4.round(2)

array([5.64, 1.79, 0.67])

### Pondération

#### Centrer et réduire les données

In [12]:
from sklearn.preprocessing import StandardScaler

sc1 = StandardScaler(with_mean=True,with_std=True)
sc1.set_output(transform="pandas")
Z1 = sc1.fit_transform(df2)
Z1.head()

,Odor.Intensity.before.shaking,Aroma.quality.before.shaking,Fruity.before.shaking,Flower.before.shaking,Spice.before.shaking
2EL,-0.131490,-0.228030,-0.000243,1.591331,-0.134579
1CHA,-0.520902,-1.119980,-1.728249,1.591331,-1.331743
1FON,-0.899694,-0.581820,-0.785237,-0.692193,0.365664
1VAU,-1.073160,-2.256096,-1.514160,-1.027586,0.720538
1DAM,1.755390,1.909661,2.242598,0.692193,0.207468

In [13]:
sc2 = StandardScaler(with_mean=True,with_std=True)
sc2.set_output(transform="pandas")
Z2 = sc2.fit_transform(df3)
Z2.head()

      Visual.intensity    Nuance  Surface.feeling
2EL           0.677847  0.536452         0.324863
1CHA         -1.371678 -1.431319        -1.363274
1FON         -0.786100 -0.657985        -0.660189
1VAU         -1.985230 -1.852422        -2.351988
1DAM          0.812119  0.607291         0.749644

In [14]:
sc3 = StandardScaler(with_mean=True,with_std=True)
sc3.set_output(transform="pandas")
Z3 = sc3.fit_transform(df4)
Z3.head()

,Odor.Intensity,Quality.of.odour,Fruity,Flower,Spice,Plante,Phenolic,Aroma.intensity,Aroma.persistency,Aroma.quality
2EL,0.060115,0.324568,0.175057,1.073029,-1.680172,0.222944,0.722688,0.249504,-0.082489,0.442250
1CHA,-0.128991,-1.090058,-1.327792,1.888725,-2.181741,0.222944,-1.083712,-0.944783,-0.729479,-0.446265
1FON,-0.742307,-1.416157,-0.361344,0.202953,0.355899,-1.343932,-1.963409,-0.482348,-0.762872,0.043391
1VAU,-1.202295,-1.641212,-2.109274,-0.537971,-0.056282,2.128266,-0.445764,-2.633673,-1.668659,-1.899019
1DAM,0.719430,0.563401,1.446699,0.468054,-0.150636,-1.268722,0.386926,1.681039,1.307497,1.291852

In [15]:
sc4 = StandardScaler(with_mean=True,with_std=True)
sc4.set_output(transform="pandas")
Z4= sc2.fit_transform(df5)
Z4.head()

,Attack.intensity,Acidity,Astringency,Alcohol,Balance,Smooth,Bitterness,Intensity,Harmony
2EL,-0.647155,-1.188684,-0.058764,-1.473270,0.372576,0.140496,-0.780091,-0.849736,-0.011480
1CHA,-0.402738,-1.188684,-1.360490,-0.530541,-0.625459,-0.431272,-0.780091,-0.750722,-0.426422
1FON,0.220023,-0.881139,-0.990800,-0.597878,0.591282,0.011787,-0.373292,-0.252904,-0.011480
1VAU,-1.514334,3.390311,-1.329249,-1.473270,-2.452110,-2.460927,-0.576692,-1.936136,-2.572992
1DAM,1.030283,0.793269,0.498375,0.277514,1.031773,0.895429,0.017015,1.312062,1.147575

### Distance entre individus

In [16]:
from scipy.spatial.distance import pdist,squareform
import numpy as np
Z =pd.concat([Z1,Z2,Z3,Z4],axis=1)
col_weight = np.append(np.append(np.repeat(eig1[0],Z1.shape[1]),np.repeat(eig2[0],Z2.shape[1])),
                       np.append(np.repeat(eig3[0],Z3.shape[1]),np.repeat(eig4[0],Z4.shape[1])))
col_weight

array([2.24187001, 2.24187001, 2.24187001, 2.24187001, 2.24187001,
       2.83476673, 2.83476673, 2.83476673, 4.70074947, 4.70074947,
       4.70074947, 4.70074947, 4.70074947, 4.70074947, 4.70074947,
       4.70074947, 4.70074947, 4.70074947, 5.64201259, 5.64201259,
       5.64201259, 5.64201259, 5.64201259, 5.64201259, 5.64201259,
       5.64201259, 5.64201259])

In [17]:
row_dist = squareform(pdist(Z,metric= "seuclidean",V=col_weight)**2)
pd.DataFrame(row_dist)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.000000,9.345386,9.365981,29.726112,12.027174,6.648276,7.856119,6.847445,6.375361,9.595192,...,6.675017,5.123616,6.760372,4.944485,5.800981,8.126995,5.088089,31.720924,20.126368,20.320891
1,9.345386,0.000000,8.278223,17.453750,31.077212,16.929228,21.367569,13.597833,14.840943,11.531513,...,20.898287,17.650570,20.273969,15.967900,12.505393,20.149443,7.959094,17.333500,32.987044,29.875683
2,9.365981,8.278223,0.000000,17.823358,20.518397,7.295449,10.889626,11.073729,4.659874,6.851283,...,12.110659,13.131964,11.236466,8.615856,4.603949,15.632350,4.662605,17.747796,19.865560,19.642329
3,29.726112,17.453750,17.823358,0.000000,54.681731,33.499808,38.389033,27.028899,24.408719,17.820434,...,36.222259,44.038300,42.984240,36.043097,26.496832,40.796975,20.534525,8.232024,32.155607,29.998891
4,12.027174,31.077212,20.518397,54.681731,0.000000,11.101606,3.364129,17.426428,13.542277,21.868020,...,6.293411,4.888901,8.240606,5.946786,9.537188,6.376767,13.501947,60.235923,18.008248,23.401894
5,6.648276,16.929228,7.295449,33.499808,11.101606,0.000000,4.806973,8.681888,4.407596,9.952651,...,4.837898,5.192686,3.074211,2.759485,4.832390,9.485692,6.251300,39.326796,18.092660,17.561329
6,7.856119,21.367569,10.889626,38.389033,3.364129,4.806973,0.000000,10.724753,6.065543,13.845190,...,3.722021,3.191437,3.999488,2.242701,4.054356,4.606890,7.371271,44.099351,15.751014,19.012146
7,6.847445,13.597833,11.073729,27.028899,17.426428,8.681888,10.724753,0.000000,9.421213,12.633482,...,9.207719,9.646047,9.213927,8.048088,11.804288,13.599338,9.724020,36.977742,16.077777,10.406588
8,6.375361,14.840943,4.659874,24.408719,13.542277,4.407596,6.065543,9.421213,0.000000,5.776923,...,5.692554,8.618860,5.945318,5.047514,3.198318,9.023625,3.515434,27.716823,14.680008,18.500648
9,9.595192,11.531513,6.851283,17.820434,21.868020,9.952651,13.845190,12.633482,5.776923,0.000000,...,10.549802,13.265338,12.136212,10.913579,6.922536,12.063006,4.133518,18.352892,17.297816,22.578749
10,8.183684,16.867007,8.315924,30.250193,7.498477,4.881644,4.029687,9.118154,5.150998,6.898435,...,3.179658,4.857731,5.914089,3.681712,3.757640,6.609309,4.189095,35.996257,9.400798,14.328464
11,6.675017,20.898287,12.110659,36.222259,6.293411,4.837898,3.722021,9.207719,5.692554,10.549802,...,0.000000,3.785806,2.887469,4.043788,6.429829,7.587367,7.100871,42.549444,9.135163,14.208814
12,5.123616,17.650570,13.131964,44.038300,4.888901,5.192686,3.191437,9.646047,8.618860,13.265338,...,3.785806,0.000000,2.591806,2.432498,5.956977,3.748092,7.446651,47.522248,19.657290,22.588048
13,6.760372,20.273969,11.236466,42.984240,8.240606,3.074211,3.999488,9.213927,5.945318,12.136212,...,2.887469,2.591806,0.000000,3.052245,6.913845,7.495226,8.696596,46.273534,18.775171,20.272315
14,4.944485,15.967900,8.615856,36.043097,5.946786,2.759485,2.242701,8.048088,5.047514,10.913579,...,4.043788,2.432498,3.052245,0.000000,4.359953,4.097771,5.269133,39.915739,15.942527,18.090954
15,5.800981,12.505393,4.603949,26.496832,9.537188,4.832390,4.054356,11.804288,3.198318,6.922536,...,6.429829,5.956977,6.913845,4.359953,0.000000,7.159303,2.586904,28.436338,17.386126,21.233792
16,8.126995,20.149443,15.632350,40.796975,6.376767,9.485692,4.606890,13.599338,9.023625,12.063006,...,7.587367,3.748092,7.495226,4.097771,7.159303,0.000000,7.636088,44.030458,21.136537,27.185349
17,5.088089,7.959094,4.662605,20.534525,13.501947,6.251300,7.371271,9.724020,3.515434,4.133518,...,7.100871,7.446651,8.696596,5.269133,2.586904,7.636088,0.000000,23.966821,15.225419,18.533340
18,31.720924,17.333500,17.747796,8.232024,60.235923,39.326796,44.099351,36.977742,27.716823,18.352892,...,42.549444,47.522248,46.273534,39.915739,28.436338,44.030458,23.966821,0.000000,42.353426,47.813709
19,20.126368,32.987044,19.865560,32.155607,18.008248,18.092660,15.751014,16.077777,14.680008,17.297816,...,9.135163,19.657290,18.775171,15.942527,17.386126,21.136537,15.225419,42.353426,0.000000,8.041773
20,20.320891,29.875683,19.642329,29.998891,23.401894,17.561329,19.012146,10.406588,18.500648,22.578749,...,14.208814,22.588048,20.272315,18.090954,21.233792,27.185349,18.533340,47.813709,8.041773,0.000000

#### Pondération des données centrées et réduites

In [18]:
# Pondération
from mapply.mapply import mapply
Zb = pd.DataFrame().astype("float")
for eig, df in zip([eig1[0],eig2[0],eig3[0],eig4[0]],[Z1,Z2,Z3,Z4]):
    norm = mapply(df,lambda x : x/np.sqrt(eig),axis=0,progressbar=False,n_workers=-1)
    Zb = pd.concat([Zb,norm],axis=1)

## Mise en coeuvre de l'AFM

### Diagonalisation de la matrice

In [19]:
pca = PCA(normalize=False,n_components=3,row_labels=Zb.index,col_labels=Zb.columns).fit(Zb)
eig = pca.eig_[0]
eig.round(2)

array([3.46, 1.37, 0.62])