# MFAMIX

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
# Chargement des données
import pandas as pd
Biometrie2 = pd.read_csv("./data/Biometrie2.csv",sep=";",header=0,index_col=0)
Biometrie2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, A to F
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Longueur3classes  6 non-null      object
 1   Poids2classes     6 non-null      object
 2   Largeur3classes   6 non-null      object
 3   Longueur          6 non-null      int64
 4   Poids             6 non-null      int64
 5   Largeur           6 non-null      int64
 6   Long3cl           6 non-null      object
 7   Poids2cl          6 non-null      object
 8   Larg3cl           6 non-null      object
 9   Long              6 non-null      int64
 10  Poid              6 non-null      int64
 11  Larg              6 non-null      int64
dtypes: int64(6), object(6)
memory usage: 624.0+ bytes

## MFAMIX with supplementary elements

In [3]:
Biometrie1 = Biometrie2.iloc[:,:6]
Biometrie1

  Longueur3classes Poids2classes Largeur3classes  Longueur  Poids  Largeur
A            Long1        Poids2           Larg3         1      1        6
B            Long1        Poids1           Larg3         2      0        5
C            Long2        Poids2           Larg2         3      2        3
D            Long3        Poids1           Larg2         5      0        4
E            Long2        Poids2           Larg1         4      1        1
F            Long3        Poids1           Larg1         6      0        2

In [4]:
from scientisttools import MFAMIX
res_mfamix = MFAMIX(n_components=None,group=[3,3,3,3],group_type=["n","s","n","s"],num_group_sup=[2,3],parallelize=True) #
res_mfamix.fit(Biometrie2)

MFAMIX(group=[3, 3, 3, 3], group_type=['n', 's', 'n', 's'], n_components=None,
       num_group_sup=[2, 3], parallelize=True)

### Eigenvalues

In [5]:
eig = res_mfamix.eig_
eig

       eigenvalue  difference  proportion  cumulative
Dim.1    1.919803    0.390490   45.715436   45.715436
Dim.2    1.529313    0.922081   36.416876   82.132311
Dim.3    0.607232    0.489397   14.459759   96.592071
Dim.4    0.117835    0.092555    2.805952   99.398023
Dim.5    0.025280         NaN    0.601977  100.000000

### Individuals informtions

In [6]:
ind = res_mfamix.ind_
ind.keys()

dict_keys(['coord', 'cos2', 'contrib', 'infos', 'coord_partiel', 'within_inertia', 'within_partial_inertia'])

#### Individuals coordinates

In [7]:
ind["coord"].head(6)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
A  2.170061  0.040655 -0.209135  0.534032 -0.036846
B  1.389024 -1.207001 -0.338205 -0.569141  0.051539
C  0.064652  1.876511  0.916203 -0.122481  0.173123
D -0.898058 -1.106374  1.169873  0.035797 -0.195687
E -0.941581  1.400920 -0.985456 -0.131714 -0.195274
F -1.784097 -1.004711 -0.553280  0.253508  0.203145

#### Individuals cos2

In [8]:
ind["cos2"].head(6)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
A  0.934154  0.000328  0.008676  0.056573  0.000269
B  0.504125  0.380657  0.029887  0.084637  0.000694
C  0.000948  0.798502  0.190352  0.003402  0.006796
D  0.234535  0.355962  0.397994  0.000373  0.011136
E  0.228749  0.506373  0.250564  0.004476  0.009839
F  0.691341  0.219249  0.066488  0.013959  0.008963

#### Individuals contributions

In [9]:
ind["contrib"]

       Dim.1      Dim.2      Dim.3      Dim.4      Dim.5
A  40.882362   0.018013   1.200462  40.337447   0.895049
B  16.749872  15.876970   3.139457  45.815779   1.751256
C   0.036287  38.375526  23.039720   2.121843  19.759957
D   7.001663  13.340013  37.563982   0.181248  25.246427
E   7.696759  21.388428  26.654359   2.453802  25.139985
F  27.633057  11.001051   8.402019   9.089880  27.207325

#### Individuals partiel coordinates

In [10]:
ind["coord_partiel"]

        Gr1                                               Gr2            \
      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5     Dim.1     Dim.2
A  2.078405 -0.039441 -1.054187  0.493646 -0.196679  2.261717  0.120751
B  1.629355 -1.485879 -0.748551 -1.089564  1.359150  1.148693 -0.928123
C -0.220921  2.046547  1.507851 -0.654822 -1.662314  0.350224  1.706474
D -1.140130 -1.161634  2.378218  0.068163  0.479129 -0.655987 -1.051114
E -0.713750  1.924294 -1.476849  0.229796 -1.060365 -1.169413  0.877546
F -1.632959 -1.283887 -0.606481  0.952781  1.081078 -1.935234 -0.725534


      Dim.3     Dim.4     Dim.5
A  0.635917  0.574417  0.122988
B  0.072141 -0.048719 -1.256072
C  0.324555  0.409860  2.008561
D -0.038471  0.003432 -0.870504
E -0.494063 -0.493224  0.669816
F -0.500079 -0.445765 -0.674789

#### Individuals within inertia

In [11]:
ind["within_inertia"]

       Dim.1      Dim.2      Dim.3      Dim.4      Dim.5
A   2.988972   1.370763  24.314876   0.138620   0.360893
B  20.550490  16.617609   5.733308  23.019269  24.154642
C  29.015784   6.177679  11.918769  24.085708  47.590753
D  20.849154   0.652473  49.714942   0.089031   6.433015
E  18.468317  58.528202   8.221733  11.107624  10.572226
F   8.127283  16.653273   0.096372  41.559749  10.888472

#### Individuals within partial inertia

In [12]:
ind["within_partial_inertia"]

         Gr1                                                    Gr2  \
       Dim.1      Dim.2      Dim.3      Dim.4      Dim.5      Dim.1
A   1.494486   0.685382  12.157438   0.069310   0.180446   1.494486
B  10.275245   8.308805   2.866654  11.509634  12.077321  10.275245
C  14.507892   3.088840   5.959385  12.042854  23.795377  14.507892
D  10.424577   0.326236  24.857471   0.044515   3.216507  10.424577
E   9.234159  29.264101   4.110866   5.553812   5.286113   9.234159
F   4.063642   8.326637   0.048186  20.779874   5.444236   4.063642


       Dim.2      Dim.3      Dim.4      Dim.5
A   0.685382  12.157438   0.069310   0.180446
B   8.308805   2.866654  11.509634  12.077321
C   3.088840   5.959385  12.042854  23.795377
D   0.326236  24.857471   0.044515   3.216507
E  29.264101   4.110866   5.553812   5.286113
F   8.326637   0.048186  20.779874   5.444236

### Quantitatives variables informations

In [13]:
quanti_var = res_mfamix.quanti_var_
quanti_var.keys()

dict_keys(['coord', 'cor', 'contrib', 'cos2'])

#### Quantitatives variables coordinates

In [14]:
quanti_var["coord"]

             Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Longueur -0.973325 -0.213091  0.056472  0.057280  0.027582
Poids     0.219123  0.939266  0.183021  0.102501  0.160504
Largeur   0.849243 -0.410004  0.299344  0.144856 -0.009662

#### Quantitatives variables cor

In [15]:
quanti_var["cor"]

             Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Longueur -0.973325 -0.213091  0.056472  0.057280  0.027582
Poids     0.219123  0.939266  0.183021  0.102501  0.160504
Largeur   0.849243 -0.410004  0.299344  0.144856 -0.009662

#### Quantitatives variables contrib

In [16]:
quanti_var["contrib"]

              Dim.1      Dim.2     Dim.3      Dim.4      Dim.5
Longueur  27.954367   1.681986  0.297512   1.577355   1.704785
Poids      1.416799  32.679188  3.124927   5.050956  57.728131
Largeur   21.281274   6.226869  8.359451  10.087676   0.209204

#### Quantitatives variables cos2

In [17]:
quanti_var["cos2"]

             Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Longueur  0.947362  0.045408  0.003189  0.003281  0.000761
Poids     0.048015  0.882220  0.033497  0.010506  0.025761
Largeur   0.721213  0.168103  0.089607  0.020983  0.000093

#### Supplementary quantitatives variables

In [18]:
quanti_var_sup = res_mfamix.quanti_var_sup_
quanti_var_sup.keys()

dict_keys(['coord', 'cor', 'cos2'])

##### Supplementary quantitatives variables coordinates

In [19]:
quanti_var_sup["coord"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Long -0.973325 -0.213091  0.056472  0.057280  0.027582
Poid  0.219123  0.939266  0.183021  0.102501  0.160504
Larg  0.849243 -0.410004  0.299344  0.144856 -0.009662

##### Supplementary quantitatives variables cor

In [20]:
quanti_var_sup["cor"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Long -0.973325 -0.213091  0.056472  0.057280  0.027582
Poid  0.219123  0.939266  0.183021  0.102501  0.160504
Larg  0.849243 -0.410004  0.299344  0.144856 -0.009662

##### Supplementary quantitatives variables cos2

In [21]:
quanti_var_sup["cos2"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Long  0.947362  0.045408  0.003189  0.003281  0.000761
Poid  0.048015  0.882220  0.033497  0.010506  0.025761
Larg  0.721213  0.168103  0.089607  0.020983  0.000093

### Qualitatives variables informations

In [22]:
quali_var = res_mfamix.quali_var_
quali_var.keys()

dict_keys(['coord', 'cos2', 'vtest', 'dist', 'eta2', 'contrib', 'coord_partiel'])

#### Qualitatives variables coordinates

In [23]:
quali_var["coord"]

                           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Longueur3classes_Long1  1.779542 -0.583173 -0.273670 -0.017555  0.007347
Longueur3classes_Long2 -0.438465  1.638715 -0.034626 -0.127098 -0.011075
Longueur3classes_Long3 -1.341078 -1.055542  0.308297  0.144653  0.003729
Poids2classes_Poids1   -0.431044 -1.106029  0.092796 -0.093279  0.019666
Poids2classes_Poids2    0.431044  1.106029 -0.092796  0.093279 -0.019666
Largeur3classes_Larg1  -1.362839  0.198105 -0.769368  0.060897  0.003935
Largeur3classes_Larg2  -0.416703  0.385068  1.043038 -0.043342 -0.011282
Largeur3classes_Larg3   1.779542 -0.583173 -0.273670 -0.017555  0.007347

#### Qualitatives variables cos2

In [24]:
quali_var["cos2"]

                           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Longueur3classes_Long1  0.884050  0.094941  0.020908  0.000086  0.000015
Longueur3classes_Long2  0.066405  0.927558  0.000414  0.005580  0.000042
Longueur3classes_Long3  0.593827  0.367877  0.031383  0.006909  0.000005
Poids2classes_Poids1    0.130221  0.857375  0.006035  0.006098  0.000271
Poids2classes_Poids2    0.130221  0.857375  0.006035  0.006098  0.000271
Largeur3classes_Larg1   0.745249  0.015747  0.237509  0.001488  0.000006
Largeur3classes_Larg2   0.122988  0.105023  0.770568  0.001331  0.000090
Largeur3classes_Larg3   0.884050  0.094941  0.020908  0.000086  0.000015

#### Qualitatives variables contrib

In [25]:
quali_var["contrib"]

                            Dim.1      Dim.2      Dim.3      Dim.4      Dim.5
Longueur3classes_Long1  14.320299   2.423542   3.385277   0.369914   1.407645
Longueur3classes_Long2   0.869371  19.136511   0.054195  19.389905   3.199092
Longueur3classes_Long3   8.132859   7.939754   4.296125  25.116160   0.362595
Poids2classes_Poids1     1.260287  13.076145   0.583834  15.665961  15.128778
Poids2classes_Poids2     1.260287  13.076145   0.583834  15.665961  15.128778
Largeur3classes_Larg1    8.398942   0.279670  26.755133   4.451348   0.403864
Largeur3classes_Larg2    0.785216   1.056650  49.174436   2.254851   3.319484
Largeur3classes_Larg3   14.320299   2.423542   3.385277   0.369914   1.407645

#### Qualitatives variables vtest

In [26]:
quali_var["vtest"]

                           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Longueur3classes_Long1  2.030720 -0.745623 -0.555290 -0.080860  0.073060
Longueur3classes_Long2 -0.500353  2.095199 -0.070259 -0.585424 -0.110140
Longueur3classes_Long3 -1.530367 -1.349576  0.625549  0.666284  0.037080
Poids2classes_Poids1   -0.695630 -1.999876  0.266279 -0.607618  0.276569
Poids2classes_Poids2    0.695630  1.999876 -0.266279  0.607618 -0.276569
Largeur3classes_Larg1  -1.555200  0.253289 -1.561085  0.280497  0.039134
Largeur3classes_Larg2  -0.475520  0.492334  2.116376 -0.199637 -0.112194
Largeur3classes_Larg3   2.030720 -0.745623 -0.555290 -0.080860  0.073060

#### Qualitatives variables partiel coordinates

In [27]:
quali_var["coord_partiel"]

                             Gr1                                          \
                           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Longueur3classes_Long1  1.853880 -0.762660 -0.901369 -0.297959  0.581236
Longueur3classes_Long2 -0.467336  1.985421  0.015501 -0.212513 -1.361339
Longueur3classes_Long3 -1.386545 -1.222761  0.885868  0.510472  0.780104
Poids2classes_Poids1   -0.381245 -1.310467  0.341062 -0.022873  0.973119
Poids2classes_Poids2    0.381245  1.310467 -0.341062  0.022873 -0.973119
Largeur3classes_Larg1  -1.173355  0.320203 -1.041665  0.591288  0.010357
Largeur3classes_Larg2  -0.680525  0.442457  1.943034 -0.293330 -0.591593
Largeur3classes_Larg3   1.853880 -0.762660 -0.901369 -0.297959  0.581236

                             Gr2
                           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Longueur3classes_Long1  1.705205 -0.403686  0.354029  0.262849 -0.566542
Longueur3classes_Long2 -0.409594  1.292010 -0.084754 -0.041682  1.339188
Longueur3classes_Long3 -1.295611 -0.888324 -0.269275 -0.221166 -0.772646
Poids2classes_Poids1   -0.480843 -0.901590 -0.155470 -0.163684 -0.933788
Poids2classes_Poids2    0.480843  0.901590  0.155470  0.163684  0.933788
Largeur3classes_Larg1  -1.552323  0.076006 -0.497071 -0.469494 -0.002486
Largeur3classes_Larg2  -0.152881  0.327680  0.143042  0.206646  0.569029
Largeur3classes_Larg3   1.705205 -0.403686  0.354029  0.262849 -0.566542

#### Qualitatives variables eta2

In [28]:
quali_var["eta2"]

                     Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Longueur3classes  0.895493  0.902289  0.093946  0.105759  0.002512
Poids2classes     0.096780  0.799901  0.014181  0.073840  0.015298
Largeur3classes   0.902479  0.115000  0.963251  0.016676  0.002594

#### Supplementary qualitatives variables

In [29]:
quali_var_sup = res_mfamix.quali_var_sup_
quali_var_sup.keys()

dict_keys(['coord', 'cos2', 'vtest', 'dist', 'eta2', 'coord_partiel'])

##### Supplementary qualitatives variables coordinates

In [30]:
quali_var_sup["coord"]

                    Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Long3cl_Long1    1.779542 -0.583173 -0.273670 -0.017555  0.007347
Long3cl_Long2   -0.438465  1.638715 -0.034626 -0.127098 -0.011075
Long3cl_Long3   -1.341078 -1.055542  0.308297  0.144653  0.003729
Poids2cl_Poids1 -0.431044 -1.106029  0.092796 -0.093279  0.019666
Poids2cl_Poids2  0.431044  1.106029 -0.092796  0.093279 -0.019666
Larg3cl_Larg1   -1.362839  0.198105 -0.769368  0.060897  0.003935
Larg3cl_Larg2   -0.416703  0.385068  1.043038 -0.043342 -0.011282
Larg3cl_Larg3    1.779542 -0.583173 -0.273670 -0.017555  0.007347

##### Supplementary qualitatives variables cos2

In [31]:
quali_var_sup["cos2"]

                    Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Long3cl_Long1    0.884050  0.094941  0.020908  0.000086  0.000015
Long3cl_Long2    0.066405  0.927558  0.000414  0.005580  0.000042
Long3cl_Long3    0.593827  0.367877  0.031383  0.006909  0.000005
Poids2cl_Poids1  0.130221  0.857375  0.006035  0.006098  0.000271
Poids2cl_Poids2  0.130221  0.857375  0.006035  0.006098  0.000271
Larg3cl_Larg1    0.745249  0.015747  0.237509  0.001488  0.000006
Larg3cl_Larg2    0.122988  0.105023  0.770568  0.001331  0.000090
Larg3cl_Larg3    0.884050  0.094941  0.020908  0.000086  0.000015

##### Supplementary qualitatives variables vtest

In [32]:
quali_var_sup["vtest"]

                    Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Long3cl_Long1    2.030720 -0.745623 -0.555290 -0.080860  0.073060
Long3cl_Long2   -0.500353  2.095199 -0.070259 -0.585424 -0.110140
Long3cl_Long3   -1.530367 -1.349576  0.625549  0.666284  0.037080
Poids2cl_Poids1 -0.695630 -1.999876  0.266279 -0.607618  0.276569
Poids2cl_Poids2  0.695630  1.999876 -0.266279  0.607618 -0.276569
Larg3cl_Larg1   -1.555200  0.253289 -1.561085  0.280497  0.039134
Larg3cl_Larg2   -0.475520  0.492334  2.116376 -0.199637 -0.112194
Larg3cl_Larg3    2.030720 -0.745623 -0.555290 -0.080860  0.073060

##### Supplementary qualitatives partiel coordinates

In [33]:
quali_var_sup["coord_partiel"]

                      Gr1                                               Gr2  \
                    Dim.1     Dim.2     Dim.3     Dim.4     Dim.5     Dim.1
Long3cl_Long1    1.853880 -0.762660 -0.901369 -0.297959  0.581236  1.705205
Long3cl_Long2   -0.467336  1.985421  0.015501 -0.212513 -1.361339 -0.409594
Long3cl_Long3   -1.386545 -1.222761  0.885868  0.510472  0.780104 -1.295611
Poids2cl_Poids1 -0.381245 -1.310467  0.341062 -0.022873  0.973119 -0.480843
Poids2cl_Poids2  0.381245  1.310467 -0.341062  0.022873 -0.973119  0.480843
Larg3cl_Larg1   -1.173355  0.320203 -1.041665  0.591288  0.010357 -1.552323
Larg3cl_Larg2   -0.680525  0.442457  1.943034 -0.293330 -0.591593 -0.152881
Larg3cl_Larg3    1.853880 -0.762660 -0.901369 -0.297959  0.581236  1.705205


                    Dim.2     Dim.3     Dim.4     Dim.5
Long3cl_Long1   -0.403686  0.354029  0.262849 -0.566542
Long3cl_Long2    1.292010 -0.084754 -0.041682  1.339188
Long3cl_Long3   -0.888324 -0.269275 -0.221166 -0.772646
Poids2cl_Poids1 -0.901590 -0.155470 -0.163684 -0.933788
Poids2cl_Poids2  0.901590  0.155470  0.163684  0.933788
Larg3cl_Larg1    0.076006 -0.497071 -0.469494 -0.002486
Larg3cl_Larg2    0.327680  0.143042  0.206646  0.569029
Larg3cl_Larg3   -0.403686  0.354029  0.262849 -0.566542

### groups informations

In [34]:
group = res_mfamix.group_
group.keys()

dict_keys(['coord', 'contrib', 'cos2', 'correlation', 'Lg', 'dist2', 'RV', 'coord_sup', 'dist2_sup', 'cos2_sup'])

#### Group coordinates

In [35]:
group["coord"]

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Gr1  0.947376  0.908595  0.535689  0.098138  0.010202
Gr2  0.972427  0.620718  0.071543  0.019697  0.015077

#### Group cos2

In [36]:
group["cos2"]

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Gr1  0.430810  0.396262  0.137742  0.004623  0.000050
Gr2  0.675338  0.275167  0.003656  0.000277  0.000162

#### Group contrib

In [37]:
group["contrib"]

        Dim.1      Dim.2     Dim.3      Dim.4      Dim.5
Gr1  49.34756  59.411958  88.21811  83.284013  40.357881
Gr2  50.65244  40.588042  11.78189  16.715987  59.642119

#### Group correlation

In [38]:
group["correlation"]

       Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Gr1  0.98779  0.994531  0.966165  0.833307  0.117382
Gr2  0.98840  0.988391  0.447416  0.289588  0.172073

#### Group Lg

In [39]:
group["Lg"]

          Gr1       Gr2       Gr3       Gr4       MFA
Gr1  2.083333  1.462078  2.083333  1.462078  1.846758
Gr2  1.462078  1.400209  1.462078  1.400209  1.490927
Gr3  2.083333  1.462078  2.083333  1.462078  1.846758
Gr4  1.462078  1.400209  1.462078  1.400209  1.490927
MFA  1.846758  1.490927  1.846758  1.490927  1.738556

#### Group RV

In [40]:
group["RV"]

          Gr1       Gr2       Gr3       Gr4       MFA
Gr1  1.000000  0.856041  1.000000  0.856041  0.970367
Gr2  0.856041  1.000000  0.856041  1.000000  0.955577
Gr3  1.000000  0.856041  1.000000  0.856041  0.970367
Gr4  0.856041  1.000000  0.856041  1.000000  0.955577
MFA  0.970367  0.955577  0.970367  0.955577  1.000000

#### Group dist2

In [41]:
group["dist2"]

Gr1    2.083333
Gr2    1.400209
Name: Sq. Dist., dtype: float64

#### Supplementary group

##### Supplementary group coordinates

In [42]:
group["coord_sup"]

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Gr3  0.947376  0.908595  0.535689  0.098138  0.010202
Gr4  0.972427  0.620718  0.071543  0.019697  0.015077

##### Supplementary group cos2

In [43]:
group["cos2_sup"]

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Gr3  0.430810  0.396262  0.137742  0.004623  0.000050
Gr4  0.675338  0.275167  0.003656  0.000277  0.000162

##### Supplementary group dist2

In [44]:
group["dist2_sup"]

Gr3    2.083333
Gr4    1.400209
Name: Sq. Dist., dtype: float64

### Inertia ratio

In [45]:
res_mfamix.inertia_ratio_

Dim.1    0.976181
Dim.2    0.951470
Dim.3    0.553679
Dim.4    0.375353
Dim.5    0.020978
Name: inertia_ratio, dtype: float64

### Partial axes

In [46]:
partial_axes = res_mfamix.partial_axes_
partial_axes.keys()

dict_keys(['coord', 'cor', 'contrib', 'cos2', 'cor_between'])

#### Partial axes coordinates

In [47]:
partial_axes["coord"]

            Gr1                                               Gr2            \
          Dim.1     Dim.2     Dim.3     Dim.4     Dim.5     Dim.1     Dim.2
Dim.1  0.908166 -0.302745  0.278772  0.074522  0.017707  0.981189 -0.113547
Dim.2 -0.333453 -0.935871  0.061721  0.008146  0.095283  0.108399  0.983967
Dim.3 -0.248333  0.156734  0.949516  0.099987  0.046759  0.148277  0.014467
Dim.4 -0.036162  0.026996 -0.123970  0.982030  0.134951  0.058139  0.016093
Dim.5  0.032673  0.084834 -0.039073 -0.141419  0.984992  0.012294  0.135825

                      Gr3                                               Gr4  \
          Dim.3     Dim.1     Dim.2     Dim.3     Dim.4     Dim.5     Dim.1
Dim.1 -0.149827  0.908166 -0.302745  0.278772  0.074522  0.017707  0.981189
Dim.2 -0.067310 -0.333453 -0.935871  0.061721  0.008146  0.095283  0.108399
Dim.3  0.835411 -0.248333  0.156734  0.949516  0.099987  0.046759  0.148277
Dim.4  0.477605 -0.036162  0.026996 -0.123970  0.982030  0.134951  0.058139
Dim.5  0.216802  0.032673  0.084834 -0.039073 -0.141419  0.984992  0.012294


          Dim.2     Dim.3
Dim.1 -0.113547 -0.149827
Dim.2  0.983967 -0.067310
Dim.3  0.014467  0.835411
Dim.4  0.016093  0.477605
Dim.5  0.135825  0.216802

#### Partial axes cor

In [48]:
partial_axes["cor"]

            Gr1                                               Gr2            \
          Dim.1     Dim.2     Dim.3     Dim.4     Dim.5     Dim.1     Dim.2
Dim.1  0.908166 -0.302745  0.278772  0.074522  0.017707  0.981189 -0.113547
Dim.2 -0.333453 -0.935871  0.061721  0.008146  0.095283  0.108399  0.983967
Dim.3 -0.248333  0.156734  0.949516  0.099987  0.046759  0.148277  0.014467
Dim.4 -0.036162  0.026996 -0.123970  0.982030  0.134951  0.058139  0.016093
Dim.5  0.032673  0.084834 -0.039073 -0.141419  0.984992  0.012294  0.135825

                      Gr3                                               Gr4  \
          Dim.3     Dim.1     Dim.2     Dim.3     Dim.4     Dim.5     Dim.1
Dim.1 -0.149827  0.908166 -0.302745  0.278772  0.074522  0.017707  0.981189
Dim.2 -0.067310 -0.333453 -0.935871  0.061721  0.008146  0.095283  0.108399
Dim.3  0.835411 -0.248333  0.156734  0.949516  0.099987  0.046759  0.148277
Dim.4  0.477605 -0.036162  0.026996 -0.123970  0.982030  0.134951  0.058139
Dim.5  0.216802  0.032673  0.084834 -0.039073 -0.141419  0.984992  0.012294


          Dim.2     Dim.3
Dim.1 -0.113547 -0.149827
Dim.2  0.983967 -0.067310
Dim.3  0.014467  0.835411
Dim.4  0.016093  0.477605
Dim.5  0.135825  0.216802

#### Partial axes contrib

In [49]:
partial_axes["contrib"]

             Gr1                                                       Gr2  \
           Dim.1      Dim.2      Dim.3      Dim.4         Dim.5      Dim.1
Dim.1  42.960898   4.336112   2.024009   0.026542  1.431896e-34  50.147448
Dim.2   7.270625  52.016385   0.124549   0.000398  5.204691e-33   0.768337
Dim.3  10.155831   3.674291  74.236930   0.151059  3.156798e-33   3.620725
Dim.4   1.109742   0.561713   6.521242  75.091316  1.355009e-31   2.868514
Dim.5   4.222936  25.856741   3.019526   7.258678  3.364778e-29   0.597870

                              Gr3                           Gr4
           Dim.2      Dim.3 Dim.1 Dim.2 Dim.3 Dim.4 Dim.5 Dim.1 Dim.2 Dim.3
Dim.1   0.422183   0.082809   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Dim.2  39.798725   0.020981   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Dim.3   0.021666   8.139498   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Dim.4   0.138164  13.709308   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Dim.5  45.876746  13.167503   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

#### Partial axes cor between

In [50]:
partial_axes["cor_between"].round(4)

              Gr1                                     Gr2                  \
            Dim.1   Dim.2   Dim.3   Dim.4   Dim.5   Dim.1   Dim.2   Dim.3
Gr1 Dim.1  1.0000 -0.0000 -0.0000  0.0000 -0.0000  0.8164 -0.4310 -0.3313
    Dim.2 -0.0000  1.0000 -0.0000  0.0000 -0.0000 -0.3726 -0.8723  0.2706
    Dim.3 -0.0000 -0.0000  1.0000 -0.0000  0.0000  0.4133  0.0355  0.6796
    Dim.4  0.0000  0.0000 -0.0000  1.0000 -0.0000  0.1442 -0.0024  0.5102
    Dim.5 -0.0000 -0.0000  0.0000 -0.0000  1.0000  0.0546  0.2284  0.3080
Gr2 Dim.1  0.8164 -0.3726  0.4133  0.1442  0.0546  1.0000 -0.0000 -0.0000
    Dim.2 -0.4310 -0.8723  0.0355 -0.0024  0.2284 -0.0000  1.0000 -0.0000
    Dim.3 -0.3313  0.2706  0.6796  0.5102  0.3080 -0.0000 -0.0000  1.0000
Gr3 Dim.1  1.0000 -0.0000 -0.0000  0.0000 -0.0000  0.8164 -0.4310 -0.3313
    Dim.2 -0.0000  1.0000 -0.0000  0.0000 -0.0000 -0.3726 -0.8723  0.2706
    Dim.3 -0.0000 -0.0000  1.0000 -0.0000  0.0000  0.4133  0.0355  0.6796
    Dim.4  0.0000  0.0000 -0.0000  1.0000 -0.0000  0.1442 -0.0024  0.5102
    Dim.5 -0.0000 -0.0000  0.0000 -0.0000  1.0000  0.0546  0.2284  0.3080
Gr4 Dim.1  0.8164 -0.3726  0.4133  0.1442  0.0546  1.0000 -0.0000 -0.0000
    Dim.2 -0.4310 -0.8723  0.0355 -0.0024  0.2284 -0.0000  1.0000 -0.0000
    Dim.3 -0.3313  0.2706  0.6796  0.5102  0.3080 -0.0000 -0.0000  1.0000

              Gr3                                     Gr4
            Dim.1   Dim.2   Dim.3   Dim.4   Dim.5   Dim.1   Dim.2   Dim.3
Gr1 Dim.1  1.0000 -0.0000 -0.0000  0.0000 -0.0000  0.8164 -0.4310 -0.3313
    Dim.2 -0.0000  1.0000 -0.0000  0.0000 -0.0000 -0.3726 -0.8723  0.2706
    Dim.3 -0.0000 -0.0000  1.0000 -0.0000  0.0000  0.4133  0.0355  0.6796
    Dim.4  0.0000  0.0000 -0.0000  1.0000 -0.0000  0.1442 -0.0024  0.5102
    Dim.5 -0.0000 -0.0000  0.0000 -0.0000  1.0000  0.0546  0.2284  0.3080
Gr2 Dim.1  0.8164 -0.3726  0.4133  0.1442  0.0546  1.0000 -0.0000 -0.0000
    Dim.2 -0.4310 -0.8723  0.0355 -0.0024  0.2284 -0.0000  1.0000 -0.0000
    Dim.3 -0.3313  0.2706  0.6796  0.5102  0.3080 -0.0000 -0.0000  1.0000
Gr3 Dim.1  1.0000 -0.0000 -0.0000  0.0000 -0.0000  0.8164 -0.4310 -0.3313
    Dim.2 -0.0000  1.0000 -0.0000  0.0000 -0.0000 -0.3726 -0.8723  0.2706
    Dim.3 -0.0000 -0.0000  1.0000 -0.0000  0.0000  0.4133  0.0355  0.6796
    Dim.4  0.0000  0.0000 -0.0000  1.0000 -0.0000  0.1442 -0.0024  0.5102
    Dim.5 -0.0000 -0.0000  0.0000 -0.0000  1.0000  0.0546  0.2284  0.3080
Gr4 Dim.1  0.8164 -0.3726  0.4133  0.1442  0.0546  1.0000 -0.0000 -0.0000
    Dim.2 -0.4310 -0.8723  0.0355 -0.0024  0.2284 -0.0000  1.0000 -0.0000
    Dim.3 -0.3313  0.2706  0.6796  0.5102  0.3080 -0.0000 -0.0000  1.0000

### Summary

#### Summary quantitatives variables

In [51]:
res_mfamix.summary_quanti_

,group,group name,variable,count,mean,std,min,25%,50%,75%,max
0,1,Gr2,Longueur,6,3.500000,1.870829,1.0,2.25,3.5,4.75,6.0
1,1,Gr2,Poids,6,0.666667,0.816497,0.0,0.00,0.5,1.00,2.0
2,1,Gr2,Largeur,6,3.500000,1.870829,1.0,2.25,3.5,4.75,6.0
3,3,Gr4,Long,6,3.500000,1.870829,1.0,2.25,3.5,4.75,6.0
4,3,Gr4,Poid,6,0.666667,0.816497,0.0,0.00,0.5,1.00,2.0
5,3,Gr4,Larg,6,3.500000,1.870829,1.0,2.25,3.5,4.75,6.0

#### Summary qualitatives

In [52]:
res_mfamix.summary_quali_

    group group name          variable               categorie  count
0       0        Gr1  Longueur3classes  Longueur3classes_Long1      2
1       0        Gr1  Longueur3classes  Longueur3classes_Long2      2
2       0        Gr1  Longueur3classes  Longueur3classes_Long3      2
3       0        Gr1     Poids2classes    Poids2classes_Poids2      3
4       0        Gr1     Poids2classes    Poids2classes_Poids1      3
5       0        Gr1   Largeur3classes   Largeur3classes_Larg3      2
6       0        Gr1   Largeur3classes   Largeur3classes_Larg2      2
7       0        Gr1   Largeur3classes   Largeur3classes_Larg1      2
8       2        Gr3           Long3cl           Long3cl_Long1      2
9       2        Gr3           Long3cl           Long3cl_Long2      2
10      2        Gr3           Long3cl           Long3cl_Long3      2
11      2        Gr3          Poids2cl         Poids2cl_Poids2      3
12      2        Gr3          Poids2cl         Poids2cl_Poids1      3
13      2        Gr3           Larg3cl           Larg3cl_Larg3      2
14      2        Gr3           Larg3cl           Larg3cl_Larg2      2
15      2        Gr3           Larg3cl           Larg3cl_Larg1      2

#### Extraction

In [53]:
from scientisttools import get_eig, get_mfa, summaryMFA
eig = get_eig(res_mfamix)
ind = get_mfa(res_mfamix,choice="ind")
quanti_var = get_mfa(res_mfamix,choice="quanti_var")
quali_var = get_mfa(res_mfamix,choice="quali_var")
groups = get_mfa(res_mfamix,choice="group")
partial_axes = get_mfa(res_mfamix,choice = "partial_axes")

In [54]:
summaryMFA(res_mfamix)

                     Multiple Factor Analysis - Results

Importance of components
                          Dim.1   Dim.2   Dim.3   Dim.4    Dim.5
Variance                  1.920   1.529   0.607   0.118    0.025
Difference                0.390   0.922   0.489   0.093      NaN
% of var.                45.715  36.417  14.460   2.806    0.602
Cumulative of % of var.  45.715  82.132  96.592  99.398  100.000

Groups

     Sq. Dist.  Dim.1     ctr   cos2  Dim.2     ctr   cos2  Dim.3     ctr  \
Gr1      2.083  0.947  49.348  0.431  0.909  59.412  0.396  0.536  88.218
Gr2      1.400  0.972  50.652  0.675  0.621  40.588  0.275  0.072  11.782

      cos2
Gr1  0.138
Gr2  0.004

Supplementary groups

     Sq. Dist.  Dim.1   cos2  Dim.2   cos2  Dim.3   cos2
Gr3      2.083  0.947  0.431  0.909  0.396  0.536  0.138
Gr4      1.400  0.972  0.675  0.621  0.275  0.072  0.004

Individuals

   Weight  Sq. Dist.  Inertia  Dim.1     ctr   cos2  Dim.2     ctr   cos2  \
A   0.167      5.041    0.840  2.170  40.882  0.934  0.041   0.018  0.000
B   0.167      3.827    0.638  1.389  16.750  0.504 -1.207  15.877  0.381
C   0.167      4.410    0.735  0.065   0.036  0.001  1.877  38.376  0.799
D   0.167      3.439    0.573 -0.898   7.002  0.235 -1.106  13.340  0.356
E   0.167      3.876    0.646 -0.942   7.697  0.229  1.401  21.388  0.506
F   0.167      4.604    0.767 -1.784  27.633  0.691 -1.005  11.001  0.219

   Dim.3     ctr   cos2
A -0.209   1.200  0.009
B -0.338   3.139  0.030
C  0.916  23.040  0.190
D  1.170  37.564  0.398
E -0.985  26.654  0.251
F -0.553   8.402  0.066

Continuous variables

          Dim.1     ctr   cos2  Dim.2     ctr   cos2  Dim.3    ctr   cos2
Longueur -0.973  27.954  0.947 -0.213   1.682  0.045  0.056  0.298  0.003
Poids     0.219   1.417  0.048  0.939  32.679  0.882  0.183  3.125  0.033
Largeur   0.849  21.281  0.721 -0.410   6.227  0.168  0.299  8.359  0.090

Categories (the 6 first)

                        Sq. Dist.  Dim.1     ctr   cos2  Dim.2     ctr   cos2  \
Longueur3classes_Long1      3.582  1.780  14.320  0.884 -0.583   2.424  0.095
Longueur3classes_Long2      2.895 -0.438   0.869  0.066  1.639  19.137  0.928
Longueur3classes_Long3      3.029 -1.341   8.133  0.594 -1.056   7.940  0.368
Poids2classes_Poids1        1.427 -0.431   1.260  0.130 -1.106  13.076  0.857
Poids2classes_Poids2        1.427  0.431   1.260  0.130  1.106  13.076  0.857
Largeur3classes_Larg1       2.492 -1.363   8.399  0.745  0.198   0.280  0.016

                        Dim.3     ctr   cos2
Longueur3classes_Long1 -0.274   3.385  0.021
Longueur3classes_Long2 -0.035   0.054  0.000
Longueur3classes_Long3  0.308   4.296  0.031
Poids2classes_Poids1    0.093   0.584  0.006
Poids2classes_Poids2   -0.093   0.584  0.006
Largeur3classes_Larg1  -0.769  26.755  0.238

Categories (eta2)

                  Dim.1  Dim.2  Dim.3  Dim.4  Dim.5
Longueur3classes  0.895  0.902  0.094  0.106  0.003
Poids2classes     0.097  0.800  0.014  0.074  0.015
Largeur3classes   0.902  0.115  0.963  0.017  0.003

Supplementary Continuous variables

      Dim.1   cos2  Dim.2   cos2  Dim.3   cos2
Long -0.973  0.947 -0.213  0.045  0.056  0.003
Poid  0.219  0.048  0.939  0.882  0.183  0.033
Larg  0.849  0.721 -0.410  0.168  0.299  0.090

Supplementary categories (the 6 first)

                 Sq. Dist.  Dim.1   cos2  Dim.2   cos2  Dim.3   cos2
Long3cl_Long1        3.582  1.780  0.884 -0.583  0.095 -0.274  0.021
Long3cl_Long2        2.895 -0.438  0.066  1.639  0.928 -0.035  0.000
Long3cl_Long3        3.029 -1.341  0.594 -1.056  0.368  0.308  0.031
Poids2cl_Poids1      1.427 -0.431  0.130 -1.106  0.857  0.093  0.006
Poids2cl_Poids2      1.427  0.431  0.130  1.106  0.857 -0.093  0.006
Larg3cl_Larg1        2.492 -1.363  0.745  0.198  0.016 -0.769  0.238

Supplementary categories eta2 (the 6 first)

          Dim.1  Dim.2  Dim.3  Dim.4  Dim.5
Long3cl   0.895  0.902  0.094  0.106  0.003
Poids2cl  0.097  0.800  0.014  0.074  0.015
Larg3cl   0.902  0.115  0.963  0.017  0.003

## Methods

### fit_transform

In [55]:
Biometrie2 = pd.read_csv("./data/Biometrie2.csv",sep=";",header=0,index_col=0)

In [56]:
res_mfamix.fit_transform(Biometrie2)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
A  2.170061  0.040655 -0.209135  0.534032 -0.036846
B  1.389024 -1.207001 -0.338205 -0.569141  0.051539
C  0.064652  1.876511  0.916203 -0.122481  0.173123
D -0.898058 -1.106374  1.169873  0.035797 -0.195687
E -0.941581  1.400920 -0.985456 -0.131714 -0.195274
F -1.784097 -1.004711 -0.553280  0.253508  0.203145

### transform

In [57]:
X = Biometrie1.copy()
for i in range(X.shape[1]):
    if X.iloc[:,i].dtype in ["object","category"]:
        value = {x : X.columns.tolist()[i]+"_"+str(x) for x in X.iloc[:,i].unique()}
        X.iloc[:,i] = X.iloc[:,i].map(value)
X

,Longueur3classes,Poids2classes,Largeur3classes,Longueur,Poids,Largeur
A,Longueur3classes_Long1,Poids2classes_Poids2,Largeur3classes_Larg3,1,1,6
B,Longueur3classes_Long1,Poids2classes_Poids1,Largeur3classes_Larg3,2,0,5
C,Longueur3classes_Long2,Poids2classes_Poids2,Largeur3classes_Larg2,3,2,3
D,Longueur3classes_Long3,Poids2classes_Poids1,Largeur3classes_Larg2,5,0,4
E,Longueur3classes_Long2,Poids2classes_Poids2,Largeur3classes_Larg1,4,1,1
F,Longueur3classes_Long3,Poids2classes_Poids1,Largeur3classes_Larg1,6,0,2

In [58]:
res_mfamix.transform(X)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
A  2.170061  0.040655 -0.209135  0.534032 -0.036846
B  1.389024 -1.207001 -0.338205 -0.569141  0.051539
C  0.064652  1.876511  0.916203 -0.122481  0.173123
D -0.898058 -1.106374  1.169873  0.035797 -0.195687
E -0.941581  1.400920 -0.985456 -0.131714 -0.195274
F -1.784097 -1.004711 -0.553280  0.253508  0.203145

## MFAMIX without supplementary

In [59]:
res_mfamix2 = MFAMIX(n_components=10,group=[3,3,3,3],group_type=["n","s","n","s"],name_group=list(range(4)),num_group_sup=None,parallelize=True)
res_mfamix2.fit(Biometrie2)

MFAMIX(group=[3, 3, 3, 3], group_type=['n', 's', 'n', 's'], n_components=10,
       name_group=[0, 1, 2, 3], parallelize=True)

In [60]:
summaryMFA(res_mfamix2)

                     Multiple Factor Analysis - Results

Importance of components
                          Dim.1   Dim.2   Dim.3   Dim.4    Dim.5
Variance                  3.840   3.059   1.214   0.236    0.051
Difference                0.781   1.844   0.979   0.185      NaN
% of var.                45.715  36.417  14.460   2.806    0.602
Cumulative of % of var.  45.715  82.132  96.592  99.398  100.000

Groups

     Sq. Dist.  Dim.1     ctr   cos2  Dim.2     ctr   cos2  Dim.3     ctr  \
Gr1      2.083  0.947  24.674  0.431  0.909  29.706  0.396  0.536  44.109
Gr2      1.400  0.972  25.326  0.675  0.621  20.294  0.275  0.072   5.891
Gr3      2.083  0.947  24.674  0.431  0.909  29.706  0.396  0.536  44.109
Gr4      1.400  0.972  25.326  0.675  0.621  20.294  0.275  0.072   5.891

      cos2
Gr1  0.138
Gr2  0.004
Gr3  0.138
Gr4  0.004

Individuals

   Weight  Sq. Dist.  Inertia  Dim.1     ctr   cos2  Dim.2     ctr   cos2  \
A   0.167     10.082    1.680  3.069  40.882  0.934  0.057   0.018  0.000
B   0.167      7.654    1.276  1.964  16.750  0.504 -1.707  15.877  0.381
C   0.167      8.820    1.470  0.091   0.036  0.001  2.654  38.376  0.799
D   0.167      6.878    1.146 -1.270   7.002  0.235 -1.565  13.340  0.356
E   0.167      7.752    1.292 -1.332   7.697  0.229  1.981  21.388  0.506
F   0.167      9.208    1.535 -2.523  27.633  0.691 -1.421  11.001  0.219

   Dim.3     ctr   cos2
A -0.296   1.200  0.009
B -0.478   3.139  0.030
C  1.296  23.040  0.190
D  1.654  37.564  0.398
E -1.394  26.654  0.251
F -0.782   8.402  0.066

Continuous variables

          Dim.1     ctr   cos2  Dim.2     ctr   cos2  Dim.3    ctr   cos2
Longueur -0.973  13.977  0.947 -0.213   0.841  0.045  0.056  0.149  0.003
Poids     0.219   0.708  0.048  0.939  16.340  0.882  0.183  1.562  0.033
Largeur   0.849  10.641  0.721 -0.410   3.113  0.168  0.299  4.180  0.090
Long     -0.973  13.977  0.947 -0.213   0.841  0.045  0.056  0.149  0.003
Poid      0.219   0.708  0.048  0.939  16.340  0.882  0.183  1.562  0.033
Larg      0.849  10.641  0.721 -0.410   3.113  0.168  0.299  4.180  0.090

Categories (the 6 first)

                        Sq. Dist.  Dim.1    ctr   cos2  Dim.2    ctr   cos2  \
Longueur3classes_Long1      7.164  2.517  7.160  0.884 -0.825  1.212  0.095
Longueur3classes_Long2      5.790 -0.620  0.435  0.066  2.317  9.568  0.928
Longueur3classes_Long3      6.057 -1.897  4.066  0.594 -1.493  3.970  0.368
Poids2classes_Poids1        2.854 -0.610  0.630  0.130 -1.564  6.538  0.857
Poids2classes_Poids2        2.854  0.610  0.630  0.130  1.564  6.538  0.857
Largeur3classes_Larg1       4.984 -1.927  4.199  0.745  0.280  0.140  0.016

                        Dim.3     ctr   cos2
Longueur3classes_Long1 -0.387   1.693  0.021
Longueur3classes_Long2 -0.049   0.027  0.000
Longueur3classes_Long3  0.436   2.148  0.031
Poids2classes_Poids1    0.131   0.292  0.006
Poids2classes_Poids2   -0.131   0.292  0.006
Largeur3classes_Larg1  -1.088  13.378  0.238

Categories (eta2)

                  Dim.1  Dim.2  Dim.3  Dim.4  Dim.5
Longueur3classes  0.895  0.902  0.094  0.106  0.003
Poids2classes     0.097  0.800  0.014  0.074  0.015
Largeur3classes   0.902  0.115  0.963  0.017  0.003
Long3cl           0.895  0.902  0.094  0.106  0.003
Poids2cl          0.097  0.800  0.014  0.074  0.015
Larg3cl           0.902  0.115  0.963  0.017  0.003

In [61]:
from scientisttools import dimdesc
DimDesc = dimdesc(res_mfamix2)
DimDesc.keys()

dict_keys(['Dim.1', 'Dim.2', 'Dim.3', 'Dim.4', 'Dim.5'])

In [62]:
DimDesc["Dim.1"]

{'quanti':           correlation    pvalue
 Largeur      0.849243  0.032378
 Larg         0.849243  0.032378
 Longueur    -0.973325  0.001058
 Long        -0.973325  0.001058,
 'quali':                   Sum. Intra  Sum. Inter      Eta2    F-stats    pvalue
 Largeur3classes     2.246662   20.790975  0.902479  13.881241  0.030454
 Larg3cl             2.246662   20.790975  0.902479  13.881241  0.030454
 Longueur3classes    2.407589   20.630048  0.895493  12.853139  0.033784
 Long3cl             2.407589   20.630048  0.895493  12.853139  0.033784,
 'category':                                          Estimate    pvalue
 Longueur3classes=Longueur3classes_Long1   3.77498  0.012263
 Largeur3classes=Largeur3classes_Larg3     3.77498  0.012263
 Long3cl=Long3cl_Long1                     3.77498  0.012263
 Larg3cl=Larg3cl_Larg3                     3.77498  0.012263}

In [63]:
Biometrie2 = pd.read_csv("./data/Biometrie2.csv",sep=";",header=0,index_col=0)
res_mfamix2.transform(Biometrie2)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
A  3.068930  0.057495 -0.295762  0.755235 -0.052108
B  1.964376 -1.706957 -0.478294 -0.804888  0.072887
C  0.091431  2.653787  1.295707 -0.173215  0.244833
D -1.270046 -1.564649  1.654451  0.050625 -0.276744
E -1.331597  1.981200 -1.393645 -0.186272 -0.276160
F -2.523094 -1.420875 -0.782456  0.358515  0.287290

## MFAMIX

In [64]:
Biometrie2 = pd.read_csv("./data/Biometrie2.csv",sep=";",header=0,index_col=0)
res_mfamix3 = MFAMIX(n_components=10,group=[3,3]+[1]*6,group_type=["n","s"]+["n"]*3+["s"]*3,num_group_sup=list(range(2,8)),
                     name_group=("G1qualitatif","G2quantitatif","LongQuali","PoidQuali","LargQuali","LongQuanti","PoidQuanti","LargQuanti"),parallelize=True)
res_mfamix3.fit(Biometrie2)

MFAMIX(group=[3, 3, 1, 1, 1, 1, 1, 1],
       group_type=['n', 's', 'n', 'n', 'n', 's', 's', 's'], n_components=10,
       name_group=('G1qualitatif', 'G2quantitatif', 'LongQuali', 'PoidQuali',
                   'LargQuali', 'LongQuanti', 'PoidQuanti', 'LargQuanti'),
       num_group_sup=[2, 3, 4, 5, 6, 7], parallelize=True)

In [65]:
summaryMFA(res_mfamix3)

                     Multiple Factor Analysis - Results

Importance of components
                          Dim.1   Dim.2   Dim.3   Dim.4    Dim.5
Variance                  1.920   1.529   0.607   0.118    0.025
Difference                0.390   0.922   0.489   0.093      NaN
% of var.                45.715  36.417  14.460   2.806    0.602
Cumulative of % of var.  45.715  82.132  96.592  99.398  100.000

Groups

               Sq. Dist.  Dim.1     ctr   cos2  Dim.2     ctr   cos2  Dim.3  \
G1qualitatif       2.083  0.947  49.348  0.431  0.909  59.412  0.396  0.536
G2quantitatif      1.400  0.972  50.652  0.675  0.621  40.588  0.275  0.072

                  ctr   cos2
G1qualitatif   88.218  0.138
G2quantitatif  11.782  0.004

Supplementary groups

            Sq. Dist.  Dim.1   cos2  Dim.2   cos2  Dim.3   cos2
LongQuali         2.0  0.895  0.401  0.902  0.407  0.094  0.004
PoidQuali         1.0  0.097  0.009  0.800  0.640  0.014  0.000
LargQuali         2.0  0.902  0.407  0.115  0.007  0.963  0.464
LongQuanti        1.0  0.947  0.897  0.045  0.002  0.003  0.000
PoidQuanti        1.0  0.048  0.002  0.882  0.778  0.033  0.001
LargQuanti        1.0  0.721  0.520  0.168  0.028  0.090  0.008

Individuals

   Weight  Sq. Dist.  Inertia  Dim.1     ctr   cos2  Dim.2     ctr   cos2  \
A   0.167      5.041    0.840  2.170  40.882  0.934  0.041   0.018  0.000
B   0.167      3.827    0.638  1.389  16.750  0.504 -1.207  15.877  0.381
C   0.167      4.410    0.735  0.065   0.036  0.001  1.877  38.376  0.799
D   0.167      3.439    0.573 -0.898   7.002  0.235 -1.106  13.340  0.356
E   0.167      3.876    0.646 -0.942   7.697  0.229  1.401  21.388  0.506
F   0.167      4.604    0.767 -1.784  27.633  0.691 -1.005  11.001  0.219

   Dim.3     ctr   cos2
A -0.209   1.200  0.009
B -0.338   3.139  0.030
C  0.916  23.040  0.190
D  1.170  37.564  0.398
E -0.985  26.654  0.251
F -0.553   8.402  0.066

Continuous variables

          Dim.1     ctr   cos2  Dim.2     ctr   cos2  Dim.3    ctr   cos2
Longueur -0.973  27.954  0.947 -0.213   1.682  0.045  0.056  0.298  0.003
Poids     0.219   1.417  0.048  0.939  32.679  0.882  0.183  3.125  0.033
Largeur   0.849  21.281  0.721 -0.410   6.227  0.168  0.299  8.359  0.090

Categories (the 6 first)

                        Sq. Dist.  Dim.1     ctr   cos2  Dim.2     ctr   cos2  \
Longueur3classes_Long1      3.582  1.780  14.320  0.884 -0.583   2.424  0.095
Longueur3classes_Long2      2.895 -0.438   0.869  0.066  1.639  19.137  0.928
Longueur3classes_Long3      3.029 -1.341   8.133  0.594 -1.056   7.940  0.368
Poids2classes_Poids1        1.427 -0.431   1.260  0.130 -1.106  13.076  0.857
Poids2classes_Poids2        1.427  0.431   1.260  0.130  1.106  13.076  0.857
Largeur3classes_Larg1       2.492 -1.363   8.399  0.745  0.198   0.280  0.016

                        Dim.3     ctr   cos2
Longueur3classes_Long1 -0.274   3.385  0.021
Longueur3classes_Long2 -0.035   0.054  0.000
Longueur3classes_Long3  0.308   4.296  0.031
Poids2classes_Poids1    0.093   0.584  0.006
Poids2classes_Poids2   -0.093   0.584  0.006
Largeur3classes_Larg1  -0.769  26.755  0.238

Categories (eta2)

                  Dim.1  Dim.2  Dim.3  Dim.4  Dim.5
Longueur3classes  0.895  0.902  0.094  0.106  0.003
Poids2classes     0.097  0.800  0.014  0.074  0.015
Largeur3classes   0.902  0.115  0.963  0.017  0.003

Supplementary Continuous variables

      Dim.1   cos2  Dim.2   cos2  Dim.3   cos2
Long -0.973  0.947 -0.213  0.045  0.056  0.003
Poid  0.219  0.048  0.939  0.882  0.183  0.033
Larg  0.849  0.721 -0.410  0.168  0.299  0.090

Supplementary categories (the 6 first)

                 Sq. Dist.  Dim.1   cos2  Dim.2   cos2  Dim.3   cos2
Long3cl_Long1        3.582  1.780  0.884 -0.583  0.095 -0.274  0.021
Long3cl_Long2        2.895 -0.438  0.066  1.639  0.928 -0.035  0.000
Long3cl_Long3        3.029 -1.341  0.594 -1.056  0.368  0.308  0.031
Poids2cl_Poids1      1.427 -0.431  0.130 -1.106  0.857  0.093  0.006
Poids2cl_Poids2      1.427  0.431  0.130  1.106  0.857 -0.093  0.006
Larg3cl_Larg1        2.492 -1.363  0.745  0.198  0.016 -0.769  0.238

Supplementary categories eta2 (the 6 first)

          Dim.1  Dim.2  Dim.3  Dim.4  Dim.5
Long3cl   0.895  0.902  0.094  0.106  0.003
Poids2cl  0.097  0.800  0.014  0.074  0.015
Larg3cl   0.902  0.115  0.963  0.017  0.003