# PCAMIX

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
from scientisttools import load_wine
wine = load_wine()
wine.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, 2EL  to T2
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Label                          21 non-null     category
 1   Soil                           21 non-null     category
 2   Odor.Intensity.before.shaking  21 non-null     float64
 3   Aroma.quality.before.shaking   21 non-null     float64
 4   Fruity.before.shaking          21 non-null     float64
 5   Flower.before.shaking          21 non-null     float64
 6   Spice.before.shaking           21 non-null     float64
 7   Visual.intensity               21 non-null     float64
 8   Nuance                         21 non-null     float64
 9   Surface.feeling                21 non-null     float64
 10  Odor.Intensity                 21 non-null     float64
 11  Quality.of.odour               21 non-null     float64
 12  Fruity                         21 non-null     float64
 13  Flower                         21 non-null     float64
 14  Spice                          21 non-null     float64
 15  Plante                         21 non-null     float64
 16  Phenolic                       21 non-null     float64
 17  Aroma.intensity                21 non-null     float64
 18  Aroma.persistency              21 non-null     float64
 19  Aroma.quality                  21 non-null     float64
 20  Attack.intensity               21 non-null     float64
 21  Acidity                        21 non-null     float64
 22  Astringency                    21 non-null     float64
 23  Alcohol                        21 non-null     float64
 24  Balance                        21 non-null     float64
 25  Smooth                         21 non-null     float64
 26  Bitterness                     21 non-null     float64
 27  Intensity                      21 non-null     float64
 28  Harmony                        21 non-null     float64
 29  Overall.quality                21 non-null     float64
 30  Typical                        21 non-null     float64
dtypes: category(2), float64(29)
memory usage: 5.3+ KB

In [3]:
from scientisttools import splitmix
X_quanti = splitmix(wine)["quanti"]
X_quali = splitmix(wine)["quali"]

## PCA with PCA and PCAMIX

In [4]:
from scientisttools import get_pcamix, get_eig, summaryPCAMIX

In [5]:
from scientisttools import PCAMIX, PCA, MCA, FAMD
# PCA with PCAMIX
pca_pcamix = PCAMIX(n_components=2,quali_sup=[0,1]).fit(wine)
# PCA with PCA
pca_pca = PCA(n_components=2,quali_sup=[0,1]).fit(wine)

### Eigenvalues

In [6]:
# Eigenvalues with PCA
pca_pca.eig_.head(6)

       eigenvalue  difference  proportion  cumulative
Dim.1   15.049891    9.578082   51.896177   51.896177
Dim.2    5.471810    3.454656   18.868310   70.764487
Dim.3    2.017153    0.657591    6.955701   77.720188
Dim.4    1.359562    0.258270    4.688146   82.408334
Dim.5    1.101292    0.285672    3.797559   86.205893
Dim.6    0.815620    0.031304    2.812482   89.018376

In [7]:
# Eigenvalues with PCAMIX
pca_pcamix.eig_.head(6)

       eigenvalue  difference  proportion  cumulative
Dim.1   15.049891    9.578082   51.896177   51.896177
Dim.2    5.471810    3.454656   18.868310   70.764487
Dim.3    2.017153    0.657591    6.955701   77.720188
Dim.4    1.359562    0.258270    4.688146   82.408334
Dim.5    1.101292    0.285672    3.797559   86.205893
Dim.6    0.815620    0.031304    2.812482   89.018376

### Individuals

#### Coordinates

In [8]:
# Coordinates with PCA
pca_pca.ind_["coord"].head(6)

         Dim.1     Dim.2
2EL   0.258595 -1.674157
1CHA -3.534399 -2.943770
1FON -1.691259 -1.804182
1VAU -9.405279  1.498490
1DAM  5.002900  0.044303
2BOU  2.301510 -0.684421

In [9]:
# Coordinates with PCAMIX
pca_pcamix.ind_["coord"].head(6)

         Dim.1     Dim.2
2EL   0.258595 -1.674157
1CHA -3.534399 -2.943770
1FON -1.691259 -1.804182
1VAU -9.405279  1.498490
1DAM  5.002900  0.044303
2BOU  2.301510 -0.684421

#### Contributions

In [10]:
# Contributions with PCA
pca_pca.ind_["contrib"].head(6)

          Dim.1     Dim.2
2EL    0.021159  2.439171
1CHA   3.952560  7.541496
1FON   0.905039  2.832765
1VAU  27.989215  1.954148
1DAM   7.919378  0.001708
2BOU   1.675997  0.407659

In [11]:
# Contributions with PCAMIX
pca_pcamix.ind_["contrib"].head(6)

          Dim.1     Dim.2
2EL    0.021159  2.439171
1CHA   3.952560  7.541496
1FON   0.905039  2.832765
1VAU  27.989215  1.954148
1DAM   7.919378  0.001708
2BOU   1.675997  0.407659

#### Cos2

In [12]:
# Cos2 with PCA
pca_pca.ind_["cos2"].head(6)

         Dim.1     Dim.2
2EL   0.004792  0.200830
1CHA  0.360873  0.250341
1FON  0.177092  0.201530
1VAU  0.885760  0.022484
1DAM  0.753348  0.000059
2BOU  0.373777  0.033055

In [13]:
# Cos2 with PCAMIX
pca_pcamix.ind_["cos2"].head(6)

         Dim.1     Dim.2
2EL   0.004792  0.200830
1CHA  0.360873  0.250341
1FON  0.177092  0.201530
1VAU  0.885760  0.022484
1DAM  0.753348  0.000059
2BOU  0.373777  0.033055

### Variables

#### Coordinates

In [14]:
# coordinates with PCA
pca_pca.var_["coord"].head(6)

                                  Dim.1     Dim.2
Odor.Intensity.before.shaking  0.472347  0.739186
Aroma.quality.before.shaking   0.804932  0.040927
Fruity.before.shaking          0.680186 -0.038002
Flower.before.shaking          0.473859 -0.312723
Spice.before.shaking          -0.051836  0.801735
Visual.intensity               0.844884  0.332235

In [15]:
# Coordinates with PCAMIX
pca_pcamix.quanti_var_["coord"].head(6)

                                  Dim.1     Dim.2
Odor.Intensity.before.shaking  0.472347  0.739186
Aroma.quality.before.shaking   0.804932  0.040927
Fruity.before.shaking          0.680186 -0.038002
Flower.before.shaking          0.473859 -0.312723
Spice.before.shaking          -0.051836  0.801735
Visual.intensity               0.844884  0.332235

#### Contributions

In [16]:
# contributions with PCA
pca_pca.var_["contrib"].head(6)

                                  Dim.1      Dim.2
Odor.Intensity.before.shaking  1.482483   9.985640
Aroma.quality.before.shaking   4.305114   0.030612
Fruity.before.shaking          3.074129   0.026393
Flower.before.shaking          1.491989   1.787266
Spice.before.shaking           0.017853  11.747098
Visual.intensity               4.743081   2.017245

In [17]:
# Contributions with PCAMIX
pca_pcamix.quanti_var_["contrib"].head(6)

                                  Dim.1      Dim.2
Odor.Intensity.before.shaking  1.482483   9.985640
Aroma.quality.before.shaking   4.305114   0.030612
Fruity.before.shaking          3.074129   0.026393
Flower.before.shaking          1.491989   1.787266
Spice.before.shaking           0.017853  11.747098
Visual.intensity               4.743081   2.017245

#### Cos2

In [18]:
# Cos2 with PCA
pca_pca.var_["cos2"].head(6)

                                  Dim.1     Dim.2
Odor.Intensity.before.shaking  0.223112  0.546395
Aroma.quality.before.shaking   0.647915  0.001675
Fruity.before.shaking          0.462653  0.001444
Flower.before.shaking          0.224543  0.097796
Spice.before.shaking           0.002687  0.642779
Visual.intensity               0.713829  0.110380

In [19]:
# Cos2 with PCAMIX
pca_pcamix.quanti_var_["cos2"].head(6)

                                  Dim.1     Dim.2
Odor.Intensity.before.shaking  0.223112  0.546395
Aroma.quality.before.shaking   0.647915  0.001675
Fruity.before.shaking          0.462653  0.001444
Flower.before.shaking          0.224543  0.097796
Spice.before.shaking           0.002687  0.642779
Visual.intensity               0.713829  0.110380

### Supplementary qualitatives 

#### coordinates

In [20]:
# Coordinates with PCA
pca_pca.quali_sup_["coord"].head(6)

               Dim.1     Dim.2
Bourgueuil -0.534290 -1.269377
Chinon     -1.672583 -0.342947
Saumur      0.899643  0.817095
Env1       -1.720421 -1.169033
Env2       -1.619232  0.334942
Env4       -0.943122  6.234275

In [21]:
# Coordinates with PCAMIX
pca_pcamix.quali_sup_["coord"].head(6)

               Dim.1     Dim.2
Bourgueuil -0.137724 -0.542657
Chinon     -0.431143 -0.146609
Saumur      0.231901  0.349307
Env1       -0.443474 -0.499760
Env2       -0.417390  0.143187
Env4       -0.243109  2.665143

#### Cos2

In [22]:
# Cos2 with PCA
pca_pca.quali_sup_["cos2"].head(6)

               Dim.1     Dim.2
Bourgueuil  0.079218  0.447150
Chinon      0.518064  0.021780
Saumur      0.381812  0.314960
Env1        0.520961  0.240541
Env2        0.581353  0.024875
Env4        0.021758  0.950729

In [23]:
# Cos2 with PCAMIX
pca_pcamix.quali_sup_["cos2"].head(6)

               Dim.1     Dim.2
Bourgueuil  0.007587  0.117790
Chinon      0.043737  0.005057
Saumur      0.059156  0.134217
Env1        0.098335  0.124880
Env2        0.054442  0.006407
Env4        0.006221  0.747683

#### Vtest

In [24]:
# vtest with PCA
pca_pca.quali_sup_["vtest"].head(6)

               Dim.1     Dim.2
Saumur      1.087714  1.638395
Bourgueuil -0.389543 -1.534865
Chinon     -0.935280 -0.318040
Env1       -1.402388 -1.580379
Reference   2.564827 -1.151024
Env2       -1.043476  0.357968

In [25]:
pca_pcamix.quali_sup_["vtest"].head(6)

               Dim.1     Dim.2
Bourgueuil -0.100413 -0.656152
Chinon     -0.241088 -0.135962
Saumur      0.280381  0.700411
Env1       -0.361494 -0.675610
Env2       -0.268977  0.153031
Env4       -0.090926  1.653134

#### Eta2

In [26]:
# Eta2 with PCA
pca_pca.quali_sup_["eta2"].head(6)

          Dim.1     Dim.2
Label  0.068995  0.152143
Soil   0.331943  0.808771

In [27]:
# Eta2 with PCAMIX
pca_pcamix.quali_sup_["eta2"].head(6)

          Dim.1     Dim.2
Label  0.068995  0.152143
Soil   0.331943  0.808771

### Using get functions

In [28]:
ind = get_pcamix(pca_pcamix,choice="ind")
quanti_var = get_pcamix(pca_pcamix,choice="quanti_var")
summaryPCAMIX(pca_pcamix)

                Principal Component Analysis of Mixed Data - Results

Importance of components
                          Dim.1   Dim.2
Variance                 15.050   5.472
Difference                9.578   3.455
% of var.                51.896  18.868
Cumulative of % of var.  51.896  70.764

Individuals (the 10 first)

      Weight  Sq. Dist.  Inertia  Dim.1     ctr   cos2  Dim.2    ctr   cos2
2EL    0.048     13.956    0.665  0.259   0.021  0.005 -1.674  2.439  0.201
1CHA   0.048     34.616    1.648 -3.534   3.953  0.361 -2.944  7.541  0.250
1FON   0.048     16.152    0.769 -1.691   0.905  0.177 -1.804  2.833  0.202
1VAU   0.048     99.868    4.756 -9.405  27.989  0.886  1.498  1.954  0.022
1DAM   0.048     33.224    1.582  5.003   7.919  0.753  0.044  0.002  0.000
2BOU   0.048     14.171    0.675  2.302   1.676  0.374 -0.684  0.408  0.033
1BOI   0.048     17.294    0.824  3.273   3.389  0.619 -0.363  0.115  0.008
3EL    0.048     21.535    1.025  0.545   0.094  0.014  1.716  2.563  0.137
DOM1   0.048      7.937    0.378  0.349   0.039  0.015 -0.815  0.578  0.084
1TUR   0.048     16.716    0.796 -2.265   1.623  0.307 -0.575  0.287  0.020

Continuous variables (the 10 first)

                               Dim.1    ctr   cos2  Dim.2     ctr   cos2
Odor.Intensity.before.shaking  0.472  1.482  0.223  0.739   9.986  0.546
Aroma.quality.before.shaking   0.805  4.305  0.648  0.041   0.031  0.002
Fruity.before.shaking          0.680  3.074  0.463 -0.038   0.026  0.001
Flower.before.shaking          0.474  1.492  0.225 -0.313   1.787  0.098
Spice.before.shaking          -0.052  0.018  0.003  0.802  11.747  0.643
Visual.intensity               0.845  4.743  0.714  0.332   2.017  0.110
Nuance                         0.827  4.543  0.684  0.329   1.983  0.109
Surface.feeling                0.934  5.796  0.872  0.175   0.561  0.031
Odor.Intensity                 0.551  2.018  0.304  0.663   8.025  0.439
Quality.of.odour               0.828  4.556  0.686 -0.276   1.397  0.076

Supplementary categories

            Sq. Dist.  Dim.1   cos2  v.test  Dim.2   cos2  v.test
Bourgueuil      0.204 -0.138  0.008  -0.100 -0.543  0.118  -0.656
Chinon          0.154 -0.431  0.044  -0.241 -0.147  0.005  -0.136
Saumur          0.249  0.232  0.059   0.280  0.349  0.134   0.700
Env1            0.222 -0.443  0.098  -0.361 -0.500  0.125  -0.676
Env2            0.181 -0.417  0.054  -0.269  0.143  0.006   0.153
Env4            0.086 -0.243  0.006  -0.091  2.665  0.748   1.653
Reference       0.222  0.811  0.329   0.661 -0.364  0.066  -0.492

Supplementary categorical variables (eta2)

       Dim.1  Dim.2
Label  0.069  0.152
Soil   0.332  0.809

### Projection of supplementary individuals

In [29]:
pca_pca.transform(X_quanti).head(6)

         Dim.1     Dim.2
2EL   0.258595 -1.674157
1CHA -3.534399 -2.943770
1FON -1.691259 -1.804182
1VAU -9.405279  1.498490
1DAM  5.002900  0.044303
2BOU  2.301510 -0.684421

In [30]:
pca_pcamix.transform(X_quanti).head(6)

         Dim.1     Dim.2
2EL   0.258595 -1.674157
1CHA -3.534399 -2.943770
1FON -1.691259 -1.804182
1VAU -9.405279  1.498490
1DAM  5.002900  0.044303
2BOU  2.301510 -0.684421

## MCA with MCA and PCAMIX

In [31]:
# MCA
mca_mca = MCA(n_components=2,quanti_sup=list(range(2,wine.shape[1]))).fit(wine)
mca_pcamix = PCAMIX(n_components=2,quanti_sup=list(range(2,wine.shape[1]))).fit(wine)

### Eigenvalues

In [32]:
# Eigenvalues with MCA
mca_mca.eig_.head(6)

       eigenvalue  difference  proportion  cumulative
Dim.1    0.724785    0.085944   28.991408   28.991408
Dim.2    0.638841    0.138841   25.553638   54.545046
Dim.3    0.500000    0.138841   20.000000   74.545046
Dim.4    0.361159    0.085944   14.446362   88.991408
Dim.5    0.275215         NaN   11.008592  100.000000

In [33]:
# Eigenvalues with PCAMIX
mca_pcamix.eig_.head(6)

       eigenvalue  difference  proportion  cumulative
Dim.1    1.449570    0.171889   28.991408   28.991408
Dim.2    1.277682    0.277682   25.553638   54.545046
Dim.3    1.000000    0.277682   20.000000   74.545046
Dim.4    0.722318    0.171889   14.446362   88.991408
Dim.5    0.550430         NaN   11.008592  100.000000

The are a splightly different when the functions MCA and PCAMIX are. To have the same values as with MCA, the eigenvalues should be divided by $p$, the number of categoricals variables.

In [34]:
p = X_quali.shape[1]
(mca_pcamix.eig_.iloc[:,0]/p).head(6)

Dim.1    0.724785
Dim.2    0.638841
Dim.3    0.500000
Dim.4    0.361159
Dim.5    0.275215
Name: eigenvalue, dtype: float64

### Individuals

#### Coordinates

In [35]:
# Coordinates with MCA
mca_mca.ind_["coord"].head(6)

         Dim.1     Dim.2
2EL  -0.085244 -0.366298
1CHA -0.085244 -0.366298
1FON -1.136257  0.131342
1VAU  1.190131  1.420468
1DAM -0.085244 -0.366298
2BOU -1.136257  0.131342

In [36]:
# Coordinates with PCAMIX
mca_pcamix.ind_["coord"].head(6)

         Dim.1     Dim.2
2EL  -0.120554 -0.518024
1CHA -0.120554 -0.518024
1FON -1.606910  0.185745
1VAU  1.683099  2.008845
1DAM -0.120554 -0.518024
2BOU -1.606910  0.185745

To get identical results, we have to divided by $\sqrt{p}$

In [37]:
import numpy as np
(mca_pcamix.ind_["coord"]/np.sqrt(p)).head(6)

         Dim.1     Dim.2
2EL  -0.085244 -0.366298
1CHA -0.085244 -0.366298
1FON -1.136257  0.131342
1VAU  1.190131  1.420468
1DAM -0.085244 -0.366298
2BOU -1.136257  0.131342

#### Contributions

In [38]:
# Contributions with MCA
mca_mca.ind_["contrib"].head(6)

         Dim.1      Dim.2
2EL   0.047742   1.000132
1CHA  0.047742   1.000132
1FON  8.482510   0.128586
1VAU  9.305950  15.040098
1DAM  0.047742   1.000132
2BOU  8.482510   0.128586

In [39]:
# Contributions with PCAMIX
mca_pcamix.ind_["contrib"].head(6)

         Dim.1      Dim.2
2EL   0.047742   1.000132
1CHA  0.047742   1.000132
1FON  8.482510   0.128586
1VAU  9.305950  15.040098
1DAM  0.047742   1.000132
2BOU  8.482510   0.128586

#### Cos2

In [40]:
# Cos2 with MCA
mca_mca.ind_["cos2"].head(6)

         Dim.1     Dim.2
2EL   0.004996  0.092245
1CHA  0.004996  0.092245
1FON  0.573813  0.007667
1VAU  0.380245  0.541672
1DAM  0.004996  0.092245
2BOU  0.573813  0.007667

In [41]:
# Cos2 with PCAMIX
mca_pcamix.ind_["cos2"].head(6)

         Dim.1     Dim.2
2EL   0.004996  0.092245
1CHA  0.004996  0.092245
1FON  0.573813  0.007667
1VAU  0.380245  0.541672
1DAM  0.004996  0.092245
2BOU  0.573813  0.007667

### Variables

#### Coordinates

In [42]:
# Coordinates with MCA
mca_mca.var_["coord"].head(6)

               Dim.1     Dim.2
Bourgueuil -1.334664  0.164326
Chinon      0.751073  1.489246
Saumur      0.454881 -0.631177
Env1       -0.600025  0.045630
Env2        1.275346  0.781443
Env4        1.011812 -2.273020

In [43]:
# Coordinates with PCAMIX
mca_pcamix.quali_var_["coord"].head(6)

               Dim.1     Dim.2
Bourgueuil -1.334664  0.164326
Chinon      0.751073  1.489246
Saumur      0.454881 -0.631177
Env1       -0.600025  0.045630
Env2        1.275346  0.781443
Env4        1.011812 -2.273020

#### Cos2

In [44]:
# Cos2 with MCA
mca_mca.var_["cos2"].head(6)

               Dim.1     Dim.2
Bourgueuil  0.712531  0.010801
Chinon      0.132732  0.521848
Saumur      0.227608  0.438222
Env1        0.180015  0.001041
Env2        0.508284  0.190829
Env4        0.107765  0.543855

In [45]:
# Cos2 with PCAMIX
mca_pcamix.quali_var_["cos2"].head(6)

               Dim.1     Dim.2
Bourgueuil  0.712531  0.010801
Chinon      0.132732  0.521848
Saumur      0.227608  0.438222
Env1        0.180015  0.001041
Env2        0.508284  0.190829
Env4        0.107765  0.543855

#### Contributions

In [46]:
# Contributions with MCA
mca_mca.var_["contrib"].head(6)

                Dim.1      Dim.2
Bourgueuil  35.110444   0.603841
Chinon       7.412523  33.063668
Saumur       7.477033  16.332491
Env1         8.279013   0.054321
Env2        26.715753  11.379485
Env4         6.726222  38.511874

In [47]:
# Contributions with PCAMIX
mca_pcamix.quali_var_["contrib"].head(6)

                Dim.1      Dim.2
Bourgueuil  35.110444   0.603841
Chinon       7.412523  33.063668
Saumur       7.477033  16.332491
Env1         8.279013   0.054321
Env2        26.715753  11.379485
Env4         6.726222  38.511874

### Supplementary continuous 

#### Coordinates

In [48]:
# Coordinates with MCA
mca_mca.quanti_sup_["coord"].head(6)

                                  Dim.1     Dim.2
Odor.Intensity.before.shaking  0.388224 -0.674578
Aroma.quality.before.shaking  -0.128608 -0.294616
Fruity.before.shaking         -0.140083  0.049503
Flower.before.shaking         -0.287771 -0.080213
Spice.before.shaking           0.127615 -0.492527
Visual.intensity               0.051160 -0.433996

In [49]:
# Coordinates with PCAMIX
mca_pcamix.quanti_sup_["coord"].head(6)

                                  Dim.1     Dim.2
Odor.Intensity.before.shaking  0.388224 -0.674578
Aroma.quality.before.shaking  -0.128608 -0.294616
Fruity.before.shaking         -0.140083  0.049503
Flower.before.shaking         -0.287771 -0.080213
Spice.before.shaking           0.127615 -0.492527
Visual.intensity               0.051160 -0.433996

#### Cos2

In [50]:
# Cos2 with MCA
mca_mca.quanti_sup_["cos2"].head(6)

                                  Dim.1     Dim.2
Odor.Intensity.before.shaking  0.150718  0.455055
Aroma.quality.before.shaking   0.016540  0.086799
Fruity.before.shaking          0.019623  0.002451
Flower.before.shaking          0.082812  0.006434
Spice.before.shaking           0.016285  0.242583
Visual.intensity               0.002617  0.188353

In [51]:
# Cos2 with PCAMIX
mca_pcamix.quanti_sup_["cos2"].head(6)

                                  Dim.1     Dim.2
Odor.Intensity.before.shaking  0.150718  0.455055
Aroma.quality.before.shaking   0.016540  0.086799
Fruity.before.shaking          0.019623  0.002451
Flower.before.shaking          0.082812  0.006434
Spice.before.shaking           0.016285  0.242583
Visual.intensity               0.002617  0.188353

### Using get functions

In [52]:
ind = get_pcamix(mca_pcamix,choice="ind")
quali_var = get_pcamix(mca_pcamix,choice="quali_var")
summaryPCAMIX(mca_pcamix)

                Principal Component Analysis of Mixed Data - Results

Importance of components
                          Dim.1   Dim.2
Variance                  1.450   1.278
Difference                0.172   0.278
% of var.                28.991  25.554
Cumulative of % of var.  28.991  54.545

Individuals (the 10 first)

      Weight  Sq. Dist.  Inertia  Dim.1    ctr   cos2  Dim.2     ctr   cos2
2EL    0.048      2.909    0.139 -0.121  0.048  0.005 -0.518   1.000  0.092
1CHA   0.048      2.909    0.139 -0.121  0.048  0.005 -0.518   1.000  0.092
1FON   0.048      4.500    0.214 -1.607  8.483  0.574  0.186   0.129  0.008
1VAU   0.048      7.450    0.355  1.683  9.306  0.380  2.009  15.040  0.542
1DAM   0.048      2.909    0.139 -0.121  0.048  0.005 -0.518   1.000  0.092
2BOU   0.048      4.500    0.214 -1.607  8.483  0.574  0.186   0.129  0.008
1BOI   0.048      4.500    0.214 -1.607  8.483  0.574  0.186   0.129  0.008
3EL    0.048      2.909    0.139 -0.121  0.048  0.005 -0.518   1.000  0.092
DOM1   0.048      6.250    0.298  0.125  0.052  0.003  1.358   6.872  0.295
1TUR   0.048      4.109    0.196  1.437  6.784  0.503  0.133   0.066  0.004

Supplementary continuous variables (the 10 first)

                               Dim.1   cos2  Dim.2   cos2
Odor.Intensity.before.shaking  0.388  0.151 -0.675  0.455
Aroma.quality.before.shaking  -0.129  0.017 -0.295  0.087
Fruity.before.shaking         -0.140  0.020  0.050  0.002
Flower.before.shaking         -0.288  0.083 -0.080  0.006
Spice.before.shaking           0.128  0.016 -0.493  0.243
Visual.intensity               0.051  0.003 -0.434  0.188
Nuance                         0.041  0.002 -0.405  0.164
Surface.feeling                0.005  0.000 -0.265  0.070
Odor.Intensity                 0.422  0.178 -0.566  0.321
Quality.of.odour              -0.059  0.003  0.244  0.060

Categories

            Weight  Sq. Dist.  Inertia  Dim.1     ctr   cos2  vtest  Dim.2  \
Bourgueuil   3.500      2.500    8.750 -1.335  35.110  0.713 -3.135  0.164
Chinon       5.250      4.250   22.312  0.751   7.413  0.133  1.353  1.489
Saumur       1.909      0.909    1.736  0.455   7.477  0.228  1.772 -0.631
Env1         3.000      2.000    6.000 -0.600   8.279  0.180 -1.576  0.046
Env2         4.200      3.200   13.440  1.275  26.716  0.508  2.648  0.781
Env4        10.500      9.500   99.750  1.012   6.726  0.108  1.219 -2.273
Reference    3.000      2.000    6.000 -0.600   8.279  0.180 -1.576  0.046

               ctr   cos2  vtest
Bourgueuil   0.604  0.011  0.411
Chinon      33.064  0.522  2.858
Saumur      16.332  0.438 -2.619
Env1         0.054  0.001  0.128
Env2        11.379  0.191  1.728
Env4        38.512  0.544 -2.918
Reference    0.054  0.001  0.128

Categoricals variables (eta2)

       Dim.1  Dim.2
Label  0.725  0.639
Soil   0.725  0.639

In [53]:
mca_mca.transform(X_quali).head(6)

         Dim.1     Dim.2
2EL  -0.085244 -0.366298
1CHA -0.085244 -0.366298
1FON -1.136257  0.131342
1VAU  1.190131  1.420468
1DAM -0.085244 -0.366298
2BOU -1.136257  0.131342

In [54]:
(mca_pcamix.transform(X_quali)/np.sqrt(p)).head(6)

         Dim.1     Dim.2
2EL  -0.085244 -0.366298
1CHA -0.085244 -0.366298
1FON -1.136257  0.131342
1VAU  1.190131  1.420468
1DAM -0.085244 -0.366298
2BOU -1.136257  0.131342

## Mixed Analysis with FAMD and PCAMIX

In [55]:
# Mixed with FAMD
res_famd = FAMD(n_components=2).fit(wine)
# Mixed with PCAMIX
res_pcamix = PCAMIX(n_components=2).fit(wine)

### Eigenvalues

In [56]:
# Eigenvalues with FAMD
res_famd.eig_.head(6)

       eigenvalue  difference  proportion  cumulative
Dim.1   15.466717    8.978694   45.490344   45.490344
Dim.2    6.488023    3.909089   19.082421   64.572764
Dim.3    2.578934    0.511839    7.585100   72.157865
Dim.4    2.067096    0.611116    6.079693   78.237558
Dim.5    1.455980    0.213716    4.282294   82.519852
Dim.6    1.242263    0.277295    3.653716   86.173567

In [57]:
# Eigenvalues with PCAMIX
res_pcamix.eig_.head(6)

       eigenvalue  difference  proportion  cumulative
Dim.1   15.466717    8.978694   45.490344   45.490344
Dim.2    6.488023    3.909089   19.082421   64.572764
Dim.3    2.578934    0.511839    7.585100   72.157865
Dim.4    2.067096    0.611116    6.079693   78.237558
Dim.5    1.455980    0.213716    4.282294   82.519852
Dim.6    1.242263    0.277295    3.653716   86.173567

### Individuals

#### Coordinates

In [58]:
# Coordinates with FAMD
res_famd.ind_["coord"].head(6)

         Dim.1     Dim.2
2EL   0.198477 -1.512808
1CHA -3.540549 -2.674165
1FON -1.815741 -2.149922
1VAU -9.499231  1.281334
1DAM  5.213173  0.059018
2BOU  2.450057 -1.068744

In [59]:
# Coordinates with PCAMIX
res_pcamix.ind_["coord"].head(6)

         Dim.1     Dim.2
2EL   0.198477 -1.512808
1CHA -3.540549 -2.674165
1FON -1.815741 -2.149922
1VAU -9.499231  1.281334
1DAM  5.213173  0.059018
2BOU  2.450057 -1.068744

### Variables

#### Coordinates

In [60]:
# Coordinates with FAMD
res_famd.var_["coord"].tail(6)

                    Dim.1     Dim.2
Intensity        0.883192  0.013834
Harmony          0.901361  0.026433
Overall.quality  0.701245  0.186204
Typical          0.705523  0.142703
Label            0.073892  0.211503
Soil             0.359079  0.854803

In [61]:
# Coordinates with PCAMIX
res_pcamix.var_["coord"].tail(6)

                    Dim.1     Dim.2
Intensity        0.883192  0.013834
Harmony          0.901361  0.026433
Overall.quality  0.701245  0.186204
Typical          0.705523  0.142703
Label            0.073892  0.211503
Soil             0.359079  0.854803

### Categories

#### Coordinates

In [62]:
# Coordinates with  FAMD
res_famd.quali_var_["coord"].head(6)

               Dim.1     Dim.2
Bourgueuil -0.508034 -1.625556
Chinon     -1.797428 -0.451489
Saumur      0.930719  1.050845
Env1       -1.818434 -1.323286
Env2       -1.719406  0.452715
Env4       -0.940094  6.942930

In [63]:
# Coordinates with PCAMIX
res_pcamix.quali_var_["coord"].head(6)

               Dim.1     Dim.2
Bourgueuil -0.129180 -0.638184
Chinon     -0.457038 -0.177252
Saumur      0.236657  0.412555
Env1       -0.462379 -0.519514
Env2       -0.437199  0.177733
Env4       -0.239041  2.725753

The function `FAMD` gives the same results up to a factor of $\sqrt{\lambda_{\alpha}}$ in each dimension (where $\lambda_{\alpha}$ is the $\alpha$ th eigenvalue)

In [64]:
res_famd.quali_var_["coord"].dot(np.diag(1/np.sqrt(res_famd.eig_.iloc[:2,0]))).head(6)

                   0         1
Bourgueuil -0.129180 -0.638184
Chinon     -0.457038 -0.177252
Saumur      0.236657  0.412555
Env1       -0.462379 -0.519514
Env2       -0.437199  0.177733
Env4       -0.239041  2.725753

In other words, the categorie coordinates obtained with the function `PCAmix` verify the so - called **quali-barycentric** property. This property says that a categorie is represented a the barycenter of the observations that have this categorie, up to a factor of $\dfrac{1}{\sqrt{\lambda_{\alpha}}}$ in each dimension.

In [65]:
import pandas as pd
barycenter = pd.DataFrame()
for col in X_quali.columns:
    dat = pd.concat((res_pcamix.ind_["coord"],X_quali[col]),axis=1).groupby(col).mean()
    barycenter = pd.concat((barycenter,dat),axis=0)
# Quasi barycenter
quasi_barycenter = barycenter.apply(lambda x : x/np.sqrt(res_pcamix.eig_.iloc[:2,0]),axis=1)
quasi_barycenter

               Dim.1     Dim.2
Bourgueuil -0.129180 -0.638184
Chinon     -0.457038 -0.177252
Saumur      0.236657  0.412555
Env1       -0.462379 -0.519514
Env2       -0.437199  0.177733
Env4       -0.239041  2.725753
Reference   0.842962 -0.386224

The categorie coordinate of the `FAMD` on their part verify the **barycentric** property.

In [66]:
res_famd.quali_var_["coord"].head(6)

               Dim.1     Dim.2
Bourgueuil -0.508034 -1.625556
Chinon     -1.797428 -0.451489
Saumur      0.930719  1.050845
Env1       -1.818434 -1.323286
Env2       -1.719406  0.452715
Env4       -0.940094  6.942930

In [67]:
barycenter

               Dim.1     Dim.2
Bourgueuil -0.508034 -1.625556
Chinon     -1.797428 -0.451489
Saumur      0.930719  1.050845
Env1       -1.818434 -1.323286
Env2       -1.719406  0.452715
Env4       -0.940094  6.942930
Reference   3.315180 -0.983775

### Transform

In [68]:
res_famd.transform(wine).head(6)

         Dim.1     Dim.2
2EL   0.198477 -1.512808
1CHA -3.540549 -2.674165
1FON -1.815741 -2.149922
1VAU -9.499231  1.281334
1DAM  5.213173  0.059018
2BOU  2.450057 -1.068744

In [69]:
res_pcamix.transform(wine).head(6)

         Dim.1     Dim.2
2EL   0.198477 -1.512808
1CHA -3.540549 -2.674165
1FON -1.815741 -2.149922
1VAU -9.499231  1.281334
1DAM  5.213173  0.059018
2BOU  2.450057 -1.068744

### Using get functions

In [70]:
ind = get_pcamix(res_pcamix,choice="ind")
quanti_var = get_pcamix(res_pcamix,choice="quanti_var")
quali_var = get_pcamix(res_pcamix,choice="quali_var")
summaryPCAMIX(res_pcamix)

                Principal Component Analysis of Mixed Data - Results

Importance of components
                          Dim.1   Dim.2
Variance                 15.467   6.488
Difference                8.979   3.909
% of var.                45.490  19.082
Cumulative of % of var.  45.490  64.573

Individuals (the 10 first)

      Weight  Sq. Dist.  Inertia  Dim.1     ctr   cos2  Dim.2    ctr   cos2
2EL    0.048     16.865    0.803  0.198   0.012  0.002 -1.513  1.680  0.136
1CHA   0.048     37.525    1.787 -3.541   3.859  0.334 -2.674  5.249  0.191
1FON   0.048     20.652    0.983 -1.816   1.015  0.160 -2.150  3.392  0.224
1VAU   0.048    107.318    5.110 -9.499  27.782  0.841  1.281  1.205  0.015
1DAM   0.048     36.133    1.721  5.213   8.367  0.752  0.059  0.003  0.000
2BOU   0.048     18.671    0.889  2.450   1.848  0.321 -1.069  0.838  0.061
1BOI   0.048     21.794    1.038  3.414   3.589  0.535 -0.794  0.462  0.029
3EL    0.048     24.444    1.164  0.474   0.069  0.009  1.524  1.706  0.095
DOM1   0.048     14.187    0.676  0.106   0.003  0.001 -1.042  0.796  0.076
1TUR   0.048     20.825    0.992 -2.286   1.608  0.251 -0.257  0.048  0.003

Continuous variables (the 10 first)

                               Dim.1    ctr   cos2  Dim.2    ctr   cos2
Odor.Intensity.before.shaking  0.473  1.444  0.223  0.763  8.964  0.582
Aroma.quality.before.shaking   0.814  4.279  0.662  0.053  0.043  0.003
Fruity.before.shaking          0.682  3.007  0.465 -0.048  0.036  0.002
Flower.before.shaking          0.477  1.474  0.228 -0.303  1.416  0.092
Spice.before.shaking          -0.056  0.020  0.003  0.768  9.102  0.591
Visual.intensity               0.844  4.609  0.713  0.337  1.749  0.113
Nuance                         0.826  4.409  0.682  0.330  1.675  0.109
Surface.feeling                0.930  5.593  0.865  0.184  0.525  0.034
Odor.Intensity                 0.545  1.919  0.297  0.685  7.242  0.470
Quality.of.odour               0.826  4.417  0.683 -0.274  1.156  0.075

Categories

            Weight  Sq. Dist.  Inertia  Dim.1    ctr   cos2  vtest  Dim.2  \
Bourgueuil   3.500      2.500    8.750 -0.129  0.031  0.007 -0.093 -0.638
Chinon       5.250      4.250   22.312 -0.457  0.257  0.049 -0.252 -0.177
Saumur       1.909      0.909    1.736  0.237  0.190  0.062  0.282  0.413
Env1         3.000      2.000    6.000 -0.462  0.461  0.107 -0.372 -0.520
Env2         4.200      3.200   13.440 -0.437  0.294  0.060 -0.278  0.178
Env4        10.500      9.500   99.750 -0.239  0.035  0.006 -0.088  2.726
Reference    3.000      2.000    6.000  0.843  1.531  0.355  0.678 -0.386

               ctr   cos2  vtest
Bourgueuil   1.794  0.163 -0.709
Chinon       0.092  0.007 -0.151
Saumur       1.374  0.187  0.760
Env1         1.387  0.135 -0.645
Env2         0.116  0.010  0.174
Env4        10.906  0.782  1.553
Reference    0.766  0.075 -0.479

Categoricals variables (eta2)

       Dim.1  Dim.2
Label  0.074  0.212
Soil   0.359  0.855

In [71]:
wine2 = wine.copy()
wine2.index = [x+"_2" for x in wine2.index]
Wine = pd.concat((wine,wine2),axis=0)
res_pcamix2 = PCAMIX(n_components=2,ind_sup=list(range(wine.shape[0],Wine.shape[0]))).fit(Wine)
summaryPCAMIX(res_pcamix2)

                Principal Component Analysis of Mixed Data - Results

Importance of components
                          Dim.1   Dim.2
Variance                 15.467   6.488
Difference                8.979   3.909
% of var.                45.490  19.082
Cumulative of % of var.  45.490  64.573

Individuals (the 10 first)

      Weight  Sq. Dist.  Inertia  Dim.1     ctr   cos2  Dim.2    ctr   cos2
2EL    0.048     16.865    0.803  0.198   0.012  0.002 -1.513  1.680  0.136
1CHA   0.048     37.525    1.787 -3.541   3.859  0.334 -2.674  5.249  0.191
1FON   0.048     20.652    0.983 -1.816   1.015  0.160 -2.150  3.392  0.224
1VAU   0.048    107.318    5.110 -9.499  27.782  0.841  1.281  1.205  0.015
1DAM   0.048     36.133    1.721  5.213   8.367  0.752  0.059  0.003  0.000
2BOU   0.048     18.671    0.889  2.450   1.848  0.321 -1.069  0.838  0.061
1BOI   0.048     21.794    1.038  3.414   3.589  0.535 -0.794  0.462  0.029
3EL    0.048     24.444    1.164  0.474   0.069  0.009  1.524  1.706  0.095
DOM1   0.048     14.187    0.676  0.106   0.003  0.001 -1.042  0.796  0.076
1TUR   0.048     20.825    0.992 -2.286   1.608  0.251 -0.257  0.048  0.003

Supplementary individuals (the 10 first)

        Sq. Dist.  Dim.1   cos2  Dim.2   cos2
2EL _2     16.865  0.198  0.002 -1.513  0.136
1CHA_2     37.525 -3.541  0.334 -2.674  0.191
1FON_2     20.652 -1.816  0.160 -2.150  0.224
1VAU_2    107.318 -9.499  0.841  1.281  0.015
1DAM_2     36.133  5.213  0.752  0.059  0.000
2BOU_2     18.671  2.450  0.321 -1.069  0.061
1BOI_2     21.794  3.414  0.535 -0.794  0.029
3EL _2     24.444  0.474  0.009  1.524  0.095
DOM1_2     14.187  0.106  0.001 -1.042  0.076
1TUR_2     20.825 -2.286  0.251 -0.257  0.003

Continuous variables (the 10 first)

                               Dim.1    ctr   cos2  Dim.2    ctr   cos2
Odor.Intensity.before.shaking  0.473  1.444  0.223  0.763  8.964  0.582
Aroma.quality.before.shaking   0.814  4.279  0.662  0.053  0.043  0.003
Fruity.before.shaking          0.682  3.007  0.465 -0.048  0.036  0.002
Flower.before.shaking          0.477  1.474  0.228 -0.303  1.416  0.092
Spice.before.shaking          -0.056  0.020  0.003  0.768  9.102  0.591
Visual.intensity               0.844  4.609  0.713  0.337  1.749  0.113
Nuance                         0.826  4.409  0.682  0.330  1.675  0.109
Surface.feeling                0.930  5.593  0.865  0.184  0.525  0.034
Odor.Intensity                 0.545  1.919  0.297  0.685  7.242  0.470
Quality.of.odour               0.826  4.417  0.683 -0.274  1.156  0.075

Categories

            Weight  Sq. Dist.  Inertia  Dim.1    ctr   cos2  vtest  Dim.2  \
Bourgueuil   3.500      2.500    8.750 -0.129  0.031  0.007 -0.093 -0.638
Chinon       5.250      4.250   22.312 -0.457  0.257  0.049 -0.252 -0.177
Saumur       1.909      0.909    1.736  0.237  0.190  0.062  0.282  0.413
Env1         3.000      2.000    6.000 -0.462  0.461  0.107 -0.372 -0.520
Env2         4.200      3.200   13.440 -0.437  0.294  0.060 -0.278  0.178
Env4        10.500      9.500   99.750 -0.239  0.035  0.006 -0.088  2.726
Reference    3.000      2.000    6.000  0.843  1.531  0.355  0.678 -0.386

               ctr   cos2  vtest
Bourgueuil   1.794  0.163 -0.709
Chinon       0.092  0.007 -0.151
Saumur       1.374  0.187  0.760
Env1         1.387  0.135 -0.645
Env2         0.116  0.010  0.174
Env4        10.906  0.782  1.553
Reference    0.766  0.075 -0.479

Categoricals variables (eta2)

       Dim.1  Dim.2
Label  0.074  0.212
Soil   0.359  0.855

In [72]:
eig = get_eig(res_pcamix2)