In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
from scientisttools import load_cars
cars = load_cars()
cars

     CONS  CYLI  VITE  VOLU  RP/P  LONG FISC  MARQ PRIX
NOM
AS2   6.2   998   140   955  23.2  3.40  4CV  ETRA  CP1
CI4   5.6   954   145  1170  19.4  3.50  4CV  FRAN  CP1
PE6   6.7   993   145  1151  20.8  3.61  4CV  FRAN  CP2
FI3   6.3   999   140  1088  21.8  3.64  4CV  ETRA  CP1
FI5   6.2   999   145   968  21.5  3.64  4CV  ETRA  CP2
FI8   8.9  1301   200   968  11.0  3.64  6CV  ETRA  CP4
FID   7.7  1302   165   968  16.0  3.64  6CV  ETRA  CP3
FO1   7.0  1117   137   900  22.7  3.64  4CV  ETRA  CP1
RE7   9.3  1597   180   973  12.0  3.64  6CV  FRAN  CP4
NI1   6.4   988   140   375  17.0  3.64  4CV  ETRA  CP1
OP1   7.2   993   143   845  22.4  3.62  4CV  ETRA  CP1
PE1   6.8   954   134  1200  23.8  3.70  4CV  FRAN  CP1
PE3   5.8  1124   142  1200  21.4  3.70  5CV  FRAN  CP3
DA2   9.2  1360   170  1200  13.9  3.70  6CV  ETRA  CP3
PE9   8.7  1580   190  1200  11.2  3.70  6CV  FRAN  CP4
RE1   6.3   956   115   950  33.1  3.67  4CV  FRAN  CP1
RE3   6.3  1108   120   950  28.4  3.67  5CV  FRAN  CP2
RE4   5.8  1108   143   915  20.6  3.59  5CV  FRAN  CP2
FO9   7.9  1397   167   915  13.8  3.59  6CV  ETRA  CP3
RE8   8.7  1397   200   915  10.2  3.59  6CV  FRAN  CP4
SE4   8.8  1461   175  1200  14.7  3.63  6CV  ETRA  CP3
SE9   7.3   903   131  1088  23.4  3.46  4CV  ETRA  CP1
SZ2   6.4   993   145   400  18.4  3.58  4CV  ETRA  CP1
SZ3   6.5  1324   163   400  14.0  3.58  5CV  ETRA  CP3
TO1   6.1   999   150   202  19.5  3.70  4CV  ETRA  CP2
TO3   6.8  1295   170   202  15.0  3.70  5CV  ETRA  CP3
VW3   7.8  1272   170  1040  14.3  3.65  6CV  ETRA  CP3

In [3]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, AS2 to VW3
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CONS    27 non-null     float64
 1   CYLI    27 non-null     int64
 2   VITE    27 non-null     int64
 3   VOLU    27 non-null     int64
 4   RP/P    27 non-null     float64
 5   LONG    27 non-null     float64
 6   FISC    27 non-null     object
 7   MARQ    27 non-null     object
 8   PRIX    27 non-null     object
dtypes: float64(3), int64(3), object(3)
memory usage: 2.1+ KB

In [4]:
from scientisttools import MPCA

res_mpca = MPCA(n_components=5)
res_mpca.fit(cars)

MPCA(n_components=5)

### fit_transform

In [5]:
res_mpca.fit_transform(cars)

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
NOM
AS2 -2.626868 -1.700462  1.403855  0.374420 -1.431409
CI4 -2.397295  0.966126  1.758490  0.827966 -1.324621
PE6 -1.631235  2.247254  0.329646 -0.568445  1.283136
FI3 -2.086566 -1.102789  0.837737  0.359289  0.400727
FI5 -1.769700 -0.132189 -0.580175 -1.282820  1.868576
FI8  3.766185 -0.661957  1.355248 -1.455975 -0.049329
FID  2.161129 -1.272850 -0.715298  1.044895  0.709465
FO1 -1.795874 -1.233806  0.752408  0.108646  0.327720
RE7  4.002668  1.815679  1.850259 -0.808617 -0.566181
NI1 -1.912613 -1.764613  0.130560 -1.156757 -0.415251
OP1 -1.888796 -1.381416  0.838695 -0.054705  0.169040
PE1 -2.165121  1.501280  1.388492  1.019595  0.526395
PE3 -0.222393  2.356597 -2.199960  2.058609 -0.646423
DA2  3.098776 -1.113514 -0.348331  1.346747  1.484363
PE9  4.150984  2.107470  1.816939 -0.583353 -0.074522
RE1 -3.337327  1.561796  1.051333  1.109674  0.378394
RE3 -1.773843  3.395349 -2.098894  0.012404  0.425613
RE4 -1.172103  2.963985 -1.914665 -0.519590 -0.620547
FO9  2.484617 -1.478592 -0.587998  0.903153  0.213665
RE8  3.805576  1.557855  1.921905 -1.174844 -1.154160
SE4  3.084617 -1.219290 -0.222294  1.394515  0.881066
SE9 -2.506774 -1.524648  1.571622  0.681453 -0.616449
SZ2 -2.000447 -1.858788  0.350305 -1.048469 -0.806124
SZ3  0.883669 -1.118285 -3.014050 -0.128212 -1.980307
TO1 -1.644697 -0.628712 -1.553439 -2.891343  1.465478
TO3  1.132242 -1.016719 -3.494236 -0.623758 -1.247660
VW3  2.361192 -1.264758 -0.628156  1.055521  0.799346

### transform

In [6]:
res_mpca.transform(cars)

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
NOM
AS2 -2.626868 -1.700462  1.403855  0.374420 -1.431409
CI4 -2.397295  0.966126  1.758490  0.827966 -1.324621
PE6 -1.631235  2.247254  0.329646 -0.568445  1.283136
FI3 -2.086566 -1.102789  0.837737  0.359289  0.400727
FI5 -1.769700 -0.132189 -0.580175 -1.282820  1.868576
FI8  3.766185 -0.661957  1.355248 -1.455975 -0.049329
FID  2.161129 -1.272850 -0.715298  1.044895  0.709465
FO1 -1.795874 -1.233806  0.752408  0.108646  0.327720
RE7  4.002668  1.815679  1.850259 -0.808617 -0.566181
NI1 -1.912613 -1.764613  0.130560 -1.156757 -0.415251
OP1 -1.888796 -1.381416  0.838695 -0.054705  0.169040
PE1 -2.165121  1.501280  1.388492  1.019595  0.526395
PE3 -0.222393  2.356597 -2.199960  2.058609 -0.646423
DA2  3.098776 -1.113514 -0.348331  1.346747  1.484363
PE9  4.150984  2.107470  1.816939 -0.583353 -0.074522
RE1 -3.337327  1.561796  1.051333  1.109674  0.378394
RE3 -1.773843  3.395349 -2.098894  0.012404  0.425613
RE4 -1.172103  2.963985 -1.914665 -0.519590 -0.620547
FO9  2.484617 -1.478592 -0.587998  0.903153  0.213665
RE8  3.805576  1.557855  1.921905 -1.174844 -1.154160
SE4  3.084617 -1.219290 -0.222294  1.394515  0.881066
SE9 -2.506774 -1.524648  1.571622  0.681453 -0.616449
SZ2 -2.000447 -1.858788  0.350305 -1.048469 -0.806124
SZ3  0.883669 -1.118285 -3.014050 -0.128212 -1.980307
TO1 -1.644697 -0.628712 -1.553439 -2.891343  1.465478
TO3  1.132242 -1.016719 -3.494236 -0.623758 -1.247660
VW3  2.361192 -1.264758 -0.628156  1.055521  0.799346

## Eigenvalues

In [7]:
res_mpca.eig_

        eigenvalue  difference  proportion  cumulative
Dim.1     6.153650    3.397784   41.024332   41.024332
Dim.2     2.755866    0.407014   18.372438   59.396770
Dim.3     2.348852    1.139269   15.659013   75.055783
Dim.4     1.209583    0.272588    8.063886   83.119668
Dim.5     0.936995    0.128760    6.246630   89.366299
Dim.6     0.808235    0.500608    5.388230   94.754529
Dim.7     0.307627    0.097812    2.050846   96.805375
Dim.8     0.209815    0.111817    1.398765   98.204140
Dim.9     0.097998    0.021374    0.653320   98.857460
Dim.10    0.076624    0.004898    0.510826   99.368286
Dim.11    0.071726    0.048695    0.478174   99.846461
Dim.12    0.023031         NaN    0.153539  100.000000

### Individuals informations

In [8]:
ind = res_mpca.ind_
ind.keys()

dict_keys(['coord', 'cos2', 'contrib', 'dist', 'infos'])

#### Individuals coordinates

In [9]:
ind["coord"]

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
NOM
AS2 -2.626868 -1.700462  1.403855  0.374420 -1.431409
CI4 -2.397295  0.966126  1.758490  0.827966 -1.324621
PE6 -1.631235  2.247254  0.329646 -0.568445  1.283136
FI3 -2.086566 -1.102789  0.837737  0.359289  0.400727
FI5 -1.769700 -0.132189 -0.580175 -1.282820  1.868576
FI8  3.766185 -0.661957  1.355248 -1.455975 -0.049329
FID  2.161129 -1.272850 -0.715298  1.044895  0.709465
FO1 -1.795874 -1.233806  0.752408  0.108646  0.327720
RE7  4.002668  1.815679  1.850259 -0.808617 -0.566181
NI1 -1.912613 -1.764613  0.130560 -1.156757 -0.415251
OP1 -1.888796 -1.381416  0.838695 -0.054705  0.169040
PE1 -2.165121  1.501280  1.388492  1.019595  0.526395
PE3 -0.222393  2.356597 -2.199960  2.058609 -0.646423
DA2  3.098776 -1.113514 -0.348331  1.346747  1.484363
PE9  4.150984  2.107470  1.816939 -0.583353 -0.074522
RE1 -3.337327  1.561796  1.051333  1.109674  0.378394
RE3 -1.773843  3.395349 -2.098894  0.012404  0.425613
RE4 -1.172103  2.963985 -1.914665 -0.519590 -0.620547
FO9  2.484617 -1.478592 -0.587998  0.903153  0.213665
RE8  3.805576  1.557855  1.921905 -1.174844 -1.154160
SE4  3.084617 -1.219290 -0.222294  1.394515  0.881066
SE9 -2.506774 -1.524648  1.571622  0.681453 -0.616449
SZ2 -2.000447 -1.858788  0.350305 -1.048469 -0.806124
SZ3  0.883669 -1.118285 -3.014050 -0.128212 -1.980307
TO1 -1.644697 -0.628712 -1.553439 -2.891343  1.465478
TO3  1.132242 -1.016719 -3.494236 -0.623758 -1.247660
VW3  2.361192 -1.264758 -0.628156  1.055521  0.799346

#### Individuals cos2

In [10]:
ind["cos2"]

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
NOM
AS2  0.393628  0.164946  0.112423  0.007997  0.116879
CI4  0.394645  0.064096  0.212346  0.047075  0.120489
PE6  0.209410  0.397437  0.008552  0.025430  0.129572
FI3  0.549312  0.153441  0.088546  0.016287  0.020261
FI5  0.298589  0.001666  0.032092  0.156894  0.332887
FI8  0.685984  0.021192  0.088828  0.102522  0.000118
FID  0.520224  0.180461  0.056991  0.121612  0.056065
FO1  0.473792  0.223630  0.083165  0.001734  0.015778
RE7  0.647916  0.133321  0.138447  0.026443  0.012964
NI1  0.354869  0.302074  0.001654  0.129807  0.016728
OP1  0.509688  0.272636  0.100495  0.000428  0.004082
PE1  0.367387  0.176637  0.151094  0.081473  0.021716
PE3  0.002954  0.331696  0.289068  0.253115  0.024958
DA2  0.623909  0.080562  0.007884  0.117846  0.143160
PE9  0.656091  0.169116  0.125702  0.012958  0.000211
RE1  0.554413  0.121418  0.055020  0.061295  0.007127
RE3  0.145875  0.534465  0.204236  0.000007  0.008398
RE4  0.081199  0.519241  0.216672  0.015957  0.022760
FO9  0.572090  0.202601  0.032040  0.075591  0.004231
RE8  0.609584  0.102152  0.155474  0.058097  0.056069
SE4  0.660406  0.103186  0.003430  0.134975  0.053880
SE9  0.432616  0.160034  0.170047  0.031970  0.026162
SZ2  0.402336  0.347372  0.012338  0.110521  0.065334
SZ3  0.051027  0.081720  0.593644  0.001074  0.256265
TO1  0.162380  0.023728  0.144860  0.501835  0.128920
TO3  0.069909  0.056371  0.665827  0.021217  0.084889
VW3  0.567349  0.162781  0.040153  0.113376  0.065022

#### Individuals contributions

In [11]:
ind["contrib"]

         Dim.1      Dim.2      Dim.3      Dim.4      Dim.5
NOM
AS2   4.153171   3.886081   3.107601   0.429257   8.098913
CI4   3.458966   1.254427   4.875965   2.099066   6.935579
PE6   1.601535   6.787070   0.171347   0.989413   6.507955
FI3   2.620402   1.634419   1.106615   0.395266   0.634740
FI5   1.884963   0.023484   0.530761   5.038854  13.801318
FI8   8.537029   0.588894   2.896130   6.490956   0.009618
FID   2.811027   2.177371   0.806779   3.343075   1.989581
FO1   1.941133   2.045842   0.892663   0.036144   0.424527
RE7   9.642786   4.430534   5.398157   2.002101   1.267097
NI1   2.201698   4.184826   0.026878   4.097178   0.681586
OP1   2.147205   2.564643   1.109145   0.009163   0.112948
PE1   2.821422   3.029014   3.039955   3.183142   1.095272
PE3   0.029768   7.463606   7.631504  12.976224   1.651704
DA2   5.779413   1.666362   0.191322   5.553579   8.709217
PE9  10.370638   5.968990   5.205488   1.041989   0.021952
RE1   6.703492   3.278134   1.742856   3.770433   0.565962
RE3   1.893800  15.493407   6.946426   0.000471   0.716026
RE4   0.826866  11.806747   5.780508   0.826651   1.522117
FO9   3.715543   2.938156   0.545170   2.497602   0.180454
RE8   8.716544   3.261611   5.824311   4.226306   5.265402
SE4   5.726721   1.997986   0.077918   5.954520   3.068430
SE9   3.782107   3.124047   3.894726   1.421912   1.502080
SZ2   2.408560   4.643419   0.193497   3.365981   2.568635
SZ3   0.469984   1.680674  14.324568   0.050334  15.501167
TO1   1.628079   0.531228   3.805124  25.597637   8.489020
TO3   0.771581   1.389249  19.252405   1.191332   6.153072
VW3   3.355567   2.149776   0.622180   3.411414   2.525626

#### Additionals informations

In [12]:
ind["infos"]

         dist    weight   inertia
NOM
AS2  4.186927  0.037037  0.649272
CI4  3.816087  0.037037  0.539352
PE6  3.564658  0.037037  0.470622
FI3  2.815286  0.037037  0.293549
FI5  3.238639  0.037037  0.388474
FI8  4.547206  0.037037  0.765818
FID  2.996301  0.037037  0.332512
FO1  2.609048  0.037037  0.252116
RE7  4.972674  0.037037  0.915833
NI1  3.210650  0.037037  0.381788
OP1  2.645652  0.037037  0.259240
PE1  3.572073  0.037037  0.472582
PE3  4.091806  0.037037  0.620107
DA2  3.923102  0.037037  0.570027
PE9  5.124707  0.037037  0.972690
RE1  4.482104  0.037037  0.744047
RE3  4.644346  0.037037  0.798887
RE4  4.113310  0.037037  0.626641
FO9  3.284938  0.037037  0.399660
RE8  4.874203  0.037037  0.879920
SE4  3.795735  0.037037  0.533615
SE9  3.811218  0.037037  0.537977
SZ2  3.153790  0.037037  0.368385
SZ3  3.911898  0.037037  0.566776
TO1  4.081495  0.037037  0.616985
TO3  4.282244  0.037037  0.679171
VW3  3.134772  0.037037  0.363955

#### Individuals distances

In [13]:
ind["dist"]

NOM
AS2    4.186927
CI4    3.816087
PE6    3.564658
FI3    2.815286
FI5    3.238639
FI8    4.547206
FID    2.996301
FO1    2.609048
RE7    4.972674
NI1    3.210650
OP1    2.645652
PE1    3.572073
PE3    4.091806
DA2    3.923102
PE9    5.124707
RE1    4.482104
RE3    4.644346
RE4    4.113310
FO9    3.284938
RE8    4.874203
SE4    3.795735
SE9    3.811218
SZ2    3.153790
SZ3    3.911898
TO1    4.081495
TO3    4.282244
VW3    3.134772
Name: dist, dtype: float64

### Quantitatives variables informations

In [14]:
quanti_var = res_mpca.quanti_var_
quanti_var.keys()

dict_keys(['coord', 'contrib', 'cor', 'cos2', 'corr'])

#### Quantitatives variables coordinates

In [15]:
quanti_var["coord"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
CONS  0.859012 -0.117609  0.345895  0.036224  0.167043
CYLI  0.950441  0.067598 -0.059370  0.029615 -0.073148
VITE  0.928352 -0.101186  0.103113 -0.225809 -0.101447
VOLU  0.151948  0.375336  0.476545  0.618212  0.279747
RP/P -0.864684  0.223102 -0.009520  0.234878  0.166710
LONG  0.292079  0.269671 -0.334891 -0.069933  0.506087

#### Quantitatives variables cos2

In [16]:
quanti_var["cos2"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
CONS  0.737901  0.013832  0.119644  0.001312  0.027903
CYLI  0.903338  0.004569  0.003525  0.000877  0.005351
VITE  0.861837  0.010239  0.010632  0.050990  0.010292
VOLU  0.023088  0.140877  0.227095  0.382186  0.078259
RP/P  0.747678  0.049774  0.000091  0.055168  0.027792
LONG  0.085310  0.072722  0.112152  0.004891  0.256124

#### Quantitatives variables contrib

In [17]:
quanti_var["contrib"]

          Dim.1     Dim.2     Dim.3      Dim.4      Dim.5
CONS  11.991275  0.501903  5.093707   0.108482   2.977964
CYLI  14.679706  0.165810  0.150063   0.072508   0.571044
VITE  14.005294  0.371521  0.452659   4.215477   1.098357
VOLU   0.375193  5.111899  9.668361  31.596531   8.352085
RP/P  12.150162  1.806123  0.003859   4.560882   2.966116
LONG   1.386335  2.638820  4.774767   0.404328  27.334663

### Qualitatives variables informations

In [18]:
quali_var = res_mpca.quali_var_
quali_var.keys()

dict_keys(['coord', 'contrib', 'cos2', 'vtest'])

#### Qualitatives variables coordinates

In [19]:
quali_var["coord"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
4CV  -0.829601 -0.225533  0.400444 -0.169944  0.139799
5CV  -0.044295  0.377974 -0.791452  0.069307 -0.400827
6CV   0.915821 -0.072409  0.227730  0.123018  0.182113
ETRA  0.022882 -0.945880 -0.195347 -0.095776  0.140474
FRAN -0.022882  0.945880  0.195347  0.095776 -0.140474
CP1  -0.702382 -0.302027  0.504614  0.154892 -0.221186
CP2  -0.307164  0.450615 -0.361921 -0.455122  0.435591
CP3   0.489931 -0.299382 -0.593292  0.520044  0.017891
CP4   0.660909  0.302648  0.472400 -0.381343 -0.198629

#### Qualitatives variables cos2

In [20]:
quali_var["cos2"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
4CV   0.688238  0.050865  0.160356  0.028881  0.019544
5CV   0.001962  0.142864  0.626396  0.004803  0.160663
6CV   0.838728  0.005243  0.051861  0.015133  0.033165
ETRA  0.000524  0.894690  0.038161  0.009173  0.019733
FRAN  0.000524  0.894690  0.038161  0.009173  0.019733
CP1   0.493340  0.091221  0.254635  0.023991  0.048923
CP2   0.094350  0.203054  0.130987  0.207136  0.189740
CP3   0.240033  0.089630  0.351995  0.270446  0.000320
CP4   0.436801  0.091596  0.223162  0.145422  0.039454

#### Qualitatives variables contrib

In [21]:
quali_var["contrib"]

          Dim.1      Dim.2      Dim.3      Dim.4      Dim.5
4CV   11.184220   1.845703   6.826981   2.387666   2.085792
5CV    0.031884   5.184003  26.668183   0.397119  17.146591
6CV   13.629758   0.190251   2.207925   1.251127   3.539530
ETRA   0.008509  32.464927   1.624646   0.758357   2.105977
FRAN   0.008509  32.464927   1.624646   0.758357   2.105977
CP1    8.017031   3.310051  10.840822   1.983449   5.221275
CP2    1.533229   7.368060   5.576641  17.124606  20.249805
CP3    3.900656   3.252329  14.985851  22.358594   0.034162
CP4    7.098241   3.323673   9.500889  12.022516   4.210662

#### Qualitatives variables vtest

In [22]:
quali_var["vtest"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
4CV  -1.643226 -0.667537  1.283833 -0.759244  0.709626
5CV  -0.043406  0.553469 -1.255328  0.153187 -1.006582
6CV   1.331116 -0.157266  0.535752  0.403295  0.678335
ETRA  0.061325 -3.788073 -0.847404 -0.578959  0.964801
FRAN -0.036074  2.228278  0.498473  0.340564 -0.567530
CP1  -1.107309 -0.711508  1.287637  0.550773 -0.893615
CP2  -0.300998  0.659837 -0.574046 -1.005937  1.093883
CP3   0.653467 -0.596695 -1.280842  1.564506  0.061154
CP4   0.566537  0.387670  0.655443 -0.737311 -0.436343

### Variables informations

In [23]:
var = res_mpca.var_
var.keys()

dict_keys(['coord', 'contrib', 'cos2'])

#### Variables coordinates

In [24]:
var["coord"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
CONS  0.737901  0.013832  0.119644  0.001312  0.027903
CYLI  0.903338  0.004569  0.003525  0.000877  0.005351
VITE  0.861837  0.010239  0.010632  0.050990  0.010292
VOLU  0.023088  0.140877  0.227095  0.382186  0.078259
RP/P  0.747678  0.049774  0.000091  0.055168  0.027792
LONG  0.085310  0.072722  0.112152  0.004891  0.256124
FISC  0.917614  0.146278  0.628118  0.028978  0.163154
MARQ  0.000524  0.894690  0.038161  0.009173  0.019733
PRIX  0.928500  0.363985  0.704857  0.498075  0.219240

#### Variables cos2

In [25]:
var["cos2"]

             Dim.1     Dim.2         Dim.3         Dim.4     Dim.5
CONS  5.444980e-01  0.000191  1.431460e-02  1.721820e-06  0.000779
CYLI  8.160190e-01  0.000021  1.242397e-05  7.691975e-07  0.000029
VITE  7.427625e-01  0.000105  1.130454e-04  2.599949e-03  0.000106
VOLU  5.330593e-04  0.019846  5.157236e-02  1.460663e-01  0.006124
RP/P  5.590230e-01  0.002477  8.215183e-09  3.043470e-03  0.000772
LONG  7.277832e-03  0.005289  1.257812e-02  2.391872e-05  0.065600
FISC  4.210081e-01  0.010699  1.972662e-01  4.198661e-04  0.013310
MARQ  2.741426e-07  0.800470  1.456225e-03  8.414302e-05  0.000389
PRIX  2.873710e-01  0.044162  1.656079e-01  8.269302e-02  0.016022

#### Variables contrib

In [26]:
var["contrib"]

          Dim.1      Dim.2      Dim.3      Dim.4      Dim.5
CONS  11.991275   0.501903   5.093707   0.108482   2.977964
CYLI  14.679706   0.165810   0.150063   0.072508   0.571044
VITE  14.005294   0.371521   0.452659   4.215477   1.098357
VOLU   0.375193   5.111899   9.668361  31.596531   8.352085
RP/P  12.150162   1.806123   0.003859   4.560882   2.966116
LONG   1.386335   2.638820   4.774767   0.404328  27.334663
FISC  14.911710   5.307868  26.741497   2.395713  17.412504
MARQ   0.008509  32.464927   1.624646   0.758357   2.105977
PRIX  15.088613  13.207663  30.008582  41.177450  23.398211

In [27]:
# Concatenate
import pandas as pd
cars2 = cars.copy()
cars2.columns = [x+"2" for x in cars2.columns]
Cars = pd.concat((cars,cars2),axis=1)
Cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, AS2 to VW3
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CONS    27 non-null     float64
 1   CYLI    27 non-null     float64
 2   VITE    27 non-null     float64
 3   VOLU    27 non-null     float64
 4   RP/P    27 non-null     float64
 5   LONG    27 non-null     float64
 6   FISC    27 non-null     object
 7   MARQ    27 non-null     object
 8   PRIX    27 non-null     object
 9   CONS2   27 non-null     float64
 10  CYLI2   27 non-null     float64
 11  VITE2   27 non-null     float64
 12  VOLU2   27 non-null     float64
 13  RP/P2   27 non-null     float64
 14  LONG2   27 non-null     float64
 15  FISC2   27 non-null     object
 16  MARQ2   27 non-null     object
 17  PRIX2   27 non-null     object
dtypes: float64(12), object(6)
memory usage: 5.1+ KB

In [28]:
res_mpca2 = MPCA(n_components= 5,quanti_sup=list(range(9,15)),quali_sup=[15,16,17])
res_mpca2.fit(Cars)

MPCA(n_components=5, quali_sup=[15, 16, 17], quanti_sup=[9, 10, 11, 12, 13, 14])

### Suppplementary quantitatives

In [29]:
quanti_sup = res_mpca2.quanti_sup_
quanti_sup.keys()

dict_keys(['coord', 'cor', 'cos2', 'weighted_corr'])

#### Supplementary coordinates

In [30]:
quanti_sup["coord"]

          Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
CONS2  0.859012 -0.117609  0.345895  0.036224  0.167043
CYLI2  0.950441  0.067598 -0.059370  0.029615 -0.073148
VITE2  0.928352 -0.101186  0.103113 -0.225809 -0.101447
VOLU2  0.151948  0.375336  0.476545  0.618212  0.279747
RP/P2 -0.864684  0.223102 -0.009520  0.234878  0.166710
LONG2  0.292079  0.269671 -0.334891 -0.069933  0.506087

#### Supplementary cos2

In [31]:
quanti_sup["cos2"]

          Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
CONS2  0.737901  0.013832  0.119644  0.001312  0.027903
CYLI2  0.903338  0.004569  0.003525  0.000877  0.005351
VITE2  0.861837  0.010239  0.010632  0.050990  0.010292
VOLU2  0.023088  0.140877  0.227095  0.382186  0.078259
RP/P2  0.747678  0.049774  0.000091  0.055168  0.027792
LONG2  0.085310  0.072722  0.112152  0.004891  0.256124

### Supplementary qualitatives

In [32]:
quali_sup = res_mpca2.quali_sup_
quali_sup.keys()

dict_keys(['coord', 'cos2', 'vtest', 'dist', 'eta2', 'barycentre'])

#### Qualitatives supplementary coordinates

In [33]:
quali_sup["coord"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
4CV  -2.135640 -0.388536  0.636887 -0.193961  0.140432
5CV  -0.230486  1.316185 -2.544361  0.159890 -0.813865
6CV   3.212860 -0.169995  0.493586  0.191338  0.249301
ETRA  0.043535 -1.204317 -0.229620 -0.080788  0.104289
FRAN -0.074009  2.047339  0.390355  0.137340 -0.177292
CP1  -2.271768 -0.653732  1.008350  0.222111 -0.279158
CP2  -1.598316  1.569137 -1.163505 -1.049959  0.884451
CP3   1.872981 -0.765926 -1.401290  0.881434  0.026689
CP4   3.931353  1.204762  1.736088 -1.005697 -0.461048

#### Qualitatives supplementary cos2

In [34]:
quali_sup["cos2"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
4CV   0.878882  0.029090  0.078163  0.007249  0.003800
5CV   0.005888  0.191996  0.717490  0.002833  0.073411
6CV   0.963075  0.002696  0.022730  0.003416  0.005799
ETRA  0.001238  0.947619  0.034449  0.004264  0.007106
FRAN  0.001238  0.947619  0.034449  0.004264  0.007106
CP1   0.756059  0.062608  0.148953  0.007227  0.011416
CP2   0.288341  0.277909  0.152798  0.124430  0.088293
CP3   0.511028  0.085458  0.286045  0.113177  0.000104
CP4   0.727370  0.068308  0.141845  0.047600  0.010004

#### Qualitatives supplementary vtest

In [35]:
quali_sup["vtest"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
4CV  -4.230151 -1.149997  2.041874 -0.866545  0.712838
5CV  -0.225859  1.927296 -4.035629  0.353399 -2.043827
6CV   4.669788 -0.369215  1.161199  0.627271  0.928599
ETRA  0.116676 -4.823063 -0.996079 -0.488361  0.716279
FRAN -0.116676  4.823063  0.996079  0.488361 -0.716279
CP1  -3.581458 -1.540044  2.573034  0.789796 -1.127830
CP2  -1.566234  2.297694 -1.845444 -2.320677  2.221087
CP3   2.498169 -1.526557 -3.025208  2.651714  0.091227
CP4   3.369988  1.543209  2.408777 -1.944474 -1.012816

#### Qualitatives variables eta2

In [36]:
quali_sup["eta2"]

          Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
FISC2  0.917614  0.146278  0.628118  0.028978  0.163154
MARQ2  0.000524  0.894690  0.038161  0.009173  0.019733
PRIX2  0.928500  0.363985  0.704857  0.498075  0.219240

## MPCA with supplementary individuals

In [37]:
# Concatenate
cars3 = cars.copy()
cars3.index = [x+"2" for x in cars3.index]
Cars2 = pd.concat((cars,cars3),axis=0)
Cars2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54 entries, AS2 to VW32
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CONS    54 non-null     float64
 1   CYLI    54 non-null     float64
 2   VITE    54 non-null     float64
 3   VOLU    54 non-null     float64
 4   RP/P    54 non-null     float64
 5   LONG    54 non-null     float64
 6   FISC    54 non-null     object
 7   MARQ    54 non-null     object
 8   PRIX    54 non-null     object
dtypes: float64(6), object(3)
memory usage: 4.2+ KB

In [38]:
res_mpca3 = MPCA(n_components=5,ind_sup=list(range(cars.shape[0],Cars2.shape[0])))
res_mpca3.fit(Cars2)

MPCA(ind_sup=[27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
              43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
     n_components=5)

### Supplementary individuals

In [39]:
ind_sup = res_mpca3.ind_sup_
ind_sup.keys()

dict_keys(['coord', 'cos2', 'dist'])

#### Supplementary individuals coordinates

In [40]:
ind_sup["coord"]

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
AS22 -2.626868 -1.700462  1.403855  0.374420 -1.431409
CI42 -2.397295  0.966126  1.758490  0.827966 -1.324621
PE62 -1.631235  2.247254  0.329646 -0.568445  1.283136
FI32 -2.086566 -1.102789  0.837737  0.359289  0.400727
FI52 -1.769700 -0.132189 -0.580175 -1.282820  1.868576
FI82  3.766185 -0.661957  1.355248 -1.455975 -0.049329
FID2  2.161129 -1.272850 -0.715298  1.044895  0.709465
FO12 -1.795874 -1.233806  0.752408  0.108646  0.327720
RE72  4.002668  1.815679  1.850259 -0.808617 -0.566181
NI12 -1.912613 -1.764613  0.130560 -1.156757 -0.415251
OP12 -1.888796 -1.381416  0.838695 -0.054705  0.169040
PE12 -2.165121  1.501280  1.388492  1.019595  0.526395
PE32 -0.222393  2.356597 -2.199960  2.058609 -0.646423
DA22  3.098776 -1.113514 -0.348331  1.346747  1.484363
PE92  4.150984  2.107470  1.816939 -0.583353 -0.074522
RE12 -3.337327  1.561796  1.051333  1.109674  0.378394
RE32 -1.773843  3.395349 -2.098894  0.012404  0.425613
RE42 -1.172103  2.963985 -1.914665 -0.519590 -0.620547
FO92  2.484617 -1.478592 -0.587998  0.903153  0.213665
RE82  3.805576  1.557855  1.921905 -1.174844 -1.154160
SE42  3.084617 -1.219290 -0.222294  1.394515  0.881066
SE92 -2.506774 -1.524648  1.571622  0.681453 -0.616449
SZ22 -2.000447 -1.858788  0.350305 -1.048469 -0.806124
SZ32  0.883669 -1.118285 -3.014050 -0.128212 -1.980307
TO12 -1.644697 -0.628712 -1.553439 -2.891343  1.465478
TO32  1.132242 -1.016719 -3.494236 -0.623758 -1.247660
VW32  2.361192 -1.264758 -0.628156  1.055521  0.799346

In [41]:
res_mpca3.ind_["coord"].head(6)

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
AS2 -2.626868 -1.700462  1.403855  0.374420 -1.431409
CI4 -2.397295  0.966126  1.758490  0.827966 -1.324621
PE6 -1.631235  2.247254  0.329646 -0.568445  1.283136
FI3 -2.086566 -1.102789  0.837737  0.359289  0.400727
FI5 -1.769700 -0.132189 -0.580175 -1.282820  1.868576
FI8  3.766185 -0.661957  1.355248 -1.455975 -0.049329

#### Supplementary individuals cos2

In [42]:
ind_sup["cos2"].head(6)

         Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
AS22  0.393628  0.164946  0.112423  0.007997  0.116879
CI42  0.394645  0.064096  0.212346  0.047075  0.120489
PE62  0.209410  0.397437  0.008552  0.025430  0.129572
FI32  0.549312  0.153441  0.088546  0.016287  0.020261
FI52  0.298589  0.001666  0.032092  0.156894  0.332887
FI82  0.685984  0.021192  0.088828  0.102522  0.000118

In [43]:
res_mpca3.ind_["cos2"].head(6)

        Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
AS2  0.393628  0.164946  0.112423  0.007997  0.116879
CI4  0.394645  0.064096  0.212346  0.047075  0.120489
PE6  0.209410  0.397437  0.008552  0.025430  0.129572
FI3  0.549312  0.153441  0.088546  0.016287  0.020261
FI5  0.298589  0.001666  0.032092  0.156894  0.332887
FI8  0.685984  0.021192  0.088828  0.102522  0.000118

### Extractions functions

In [44]:
from scientisttools import get_eig, get_mpca, summaryMPCA
eig = get_eig(res_mpca)
ind = get_mpca(res_mpca,choice="ind")
quanti_var = get_mpca(res_mpca,choice="quanti_var")
quali_var = get_mpca(res_mpca,choice="quali_var")
quanti_var_sup = get_mpca(res_mpca2,choice="quanti_sup")
quali_var_sup = get_mpca(res_mpca2,choice="quali_sup")
ind_sup = get_mpca(res_mpca3,choice="ind_sup")
summaryMPCA(res_mpca)

                     Mixed Principal Components Analysis - Results

Importance of components
                          Dim.1   Dim.2   Dim.3   Dim.4   Dim.5
Variance                  6.154   2.756   2.349   1.210   0.937
Difference                3.398   0.407   1.139   0.273   0.129
% of var.                41.024  18.372  15.659   8.064   6.247
Cumulative of % of var.  41.024  59.397  75.056  83.120  89.366

Individuals (the 10 first)

     Dim.1    ctr   cos2  Dim.2    ctr   cos2  Dim.3    ctr   cos2
AS2 -2.627  4.153  0.394 -1.700  3.886  0.165  1.404  3.108  0.112
CI4 -2.397  3.459  0.395  0.966  1.254  0.064  1.758  4.876  0.212
PE6 -1.631  1.602  0.209  2.247  6.787  0.397  0.330  0.171  0.009
FI3 -2.087  2.620  0.549 -1.103  1.634  0.153  0.838  1.107  0.089
FI5 -1.770  1.885  0.299 -0.132  0.023  0.002 -0.580  0.531  0.032
FI8  3.766  8.537  0.686 -0.662  0.589  0.021  1.355  2.896  0.089
FID  2.161  2.811  0.520 -1.273  2.177  0.180 -0.715  0.807  0.057
FO1 -1.796  1.941  0.474 -1.234  2.046  0.224  0.752  0.893  0.083
RE7  4.003  9.643  0.648  1.816  4.431  0.133  1.850  5.398  0.138
NI1 -1.913  2.202  0.355 -1.765  4.185  0.302  0.131  0.027  0.002

Continuous variables

      Dim.1     ctr   cos2  Dim.2    ctr   cos2  Dim.3    ctr   cos2
CONS  0.859  11.991  0.738 -0.118  0.502  0.014  0.346  5.094  0.120
CYLI  0.950  14.680  0.903  0.068  0.166  0.005 -0.059  0.150  0.004
VITE  0.928  14.005  0.862 -0.101  0.372  0.010  0.103  0.453  0.011
VOLU  0.152   0.375  0.023  0.375  5.112  0.141  0.477  9.668  0.227
RP/P -0.865  12.150  0.748  0.223  1.806  0.050 -0.010  0.004  0.000
LONG  0.292   1.386  0.085  0.270  2.639  0.073 -0.335  4.775  0.112

Categories

      Dim.1     ctr   cos2  vtest  Dim.2     ctr   cos2  vtest  Dim.3     ctr  \
4CV  -0.830  11.184  0.688 -1.643 -0.226   1.846  0.051 -0.668  0.400   6.827
5CV  -0.044   0.032  0.002 -0.043  0.378   5.184  0.143  0.553 -0.791  26.668
6CV   0.916  13.630  0.839  1.331 -0.072   0.190  0.005 -0.157  0.228   2.208
ETRA  0.023   0.009  0.001  0.061 -0.946  32.465  0.895 -3.788 -0.195   1.625
FRAN -0.023   0.009  0.001 -0.036  0.946  32.465  0.895  2.228  0.195   1.625
CP1  -0.702   8.017  0.493 -1.107 -0.302   3.310  0.091 -0.712  0.505  10.841
CP2  -0.307   1.533  0.094 -0.301  0.451   7.368  0.203  0.660 -0.362   5.577
CP3   0.490   3.901  0.240  0.653 -0.299   3.252  0.090 -0.597 -0.593  14.986
CP4   0.661   7.098  0.437  0.567  0.303   3.324  0.092  0.388  0.472   9.501

       cos2  vtest
4CV   0.160  1.284
5CV   0.626 -1.255
6CV   0.052  0.536
ETRA  0.038 -0.847
FRAN  0.038  0.498
CP1   0.255  1.288
CP2   0.131 -0.574
CP3   0.352 -1.281
CP4   0.223  0.655

Categorical variables (eta2)

      Dim.1  Dim.2  Dim.3
FISC  0.918  0.146  0.628
MARQ  0.001  0.895  0.038
PRIX  0.929  0.364  0.705

In [45]:
summaryMPCA(res_mpca2)

                     Mixed Principal Components Analysis - Results

Importance of components
                          Dim.1   Dim.2   Dim.3   Dim.4   Dim.5
Variance                  6.154   2.756   2.349   1.210   0.937
Difference                3.398   0.407   1.139   0.273   0.129
% of var.                41.024  18.372  15.659   8.064   6.247
Cumulative of % of var.  41.024  59.397  75.056  83.120  89.366

Individuals (the 10 first)

     Dim.1    ctr   cos2  Dim.2    ctr   cos2  Dim.3    ctr   cos2
AS2 -2.627  4.153  0.394 -1.700  3.886  0.165  1.404  3.108  0.112
CI4 -2.397  3.459  0.395  0.966  1.254  0.064  1.758  4.876  0.212
PE6 -1.631  1.602  0.209  2.247  6.787  0.397  0.330  0.171  0.009
FI3 -2.087  2.620  0.549 -1.103  1.634  0.153  0.838  1.107  0.089
FI5 -1.770  1.885  0.299 -0.132  0.023  0.002 -0.580  0.531  0.032
FI8  3.766  8.537  0.686 -0.662  0.589  0.021  1.355  2.896  0.089
FID  2.161  2.811  0.520 -1.273  2.177  0.180 -0.715  0.807  0.057
FO1 -1.796  1.941  0.474 -1.234  2.046  0.224  0.752  0.893  0.083
RE7  4.003  9.643  0.648  1.816  4.431  0.133  1.850  5.398  0.138
NI1 -1.913  2.202  0.355 -1.765  4.185  0.302  0.131  0.027  0.002

Continuous variables

      Dim.1     ctr   cos2  Dim.2    ctr   cos2  Dim.3    ctr   cos2
CONS  0.859  11.991  0.738 -0.118  0.502  0.014  0.346  5.094  0.120
CYLI  0.950  14.680  0.903  0.068  0.166  0.005 -0.059  0.150  0.004
VITE  0.928  14.005  0.862 -0.101  0.372  0.010  0.103  0.453  0.011
VOLU  0.152   0.375  0.023  0.375  5.112  0.141  0.477  9.668  0.227
RP/P -0.865  12.150  0.748  0.223  1.806  0.050 -0.010  0.004  0.000
LONG  0.292   1.386  0.085  0.270  2.639  0.073 -0.335  4.775  0.112

Supplementary continuous variables

       Dim.1   cos2  Dim.2   cos2  Dim.3   cos2
CONS2  0.859  0.738 -0.118  0.014  0.346  0.120
CYLI2  0.950  0.903  0.068  0.005 -0.059  0.004
VITE2  0.928  0.862 -0.101  0.010  0.103  0.011
VOLU2  0.152  0.023  0.375  0.141  0.477  0.227
RP/P2 -0.865  0.748  0.223  0.050 -0.010  0.000
LONG2  0.292  0.085  0.270  0.073 -0.335  0.112

Categories

      Dim.1     ctr   cos2  vtest  Dim.2     ctr   cos2  vtest  Dim.3     ctr  \
4CV  -0.830  11.184  0.688 -1.643 -0.226   1.846  0.051 -0.668  0.400   6.827
5CV  -0.044   0.032  0.002 -0.043  0.378   5.184  0.143  0.553 -0.791  26.668
6CV   0.916  13.630  0.839  1.331 -0.072   0.190  0.005 -0.157  0.228   2.208
ETRA  0.023   0.009  0.001  0.061 -0.946  32.465  0.895 -3.788 -0.195   1.625
FRAN -0.023   0.009  0.001 -0.036  0.946  32.465  0.895  2.228  0.195   1.625
CP1  -0.702   8.017  0.493 -1.107 -0.302   3.310  0.091 -0.712  0.505  10.841
CP2  -0.307   1.533  0.094 -0.301  0.451   7.368  0.203  0.660 -0.362   5.577
CP3   0.490   3.901  0.240  0.653 -0.299   3.252  0.090 -0.597 -0.593  14.986
CP4   0.661   7.098  0.437  0.567  0.303   3.324  0.092  0.388  0.472   9.501

       cos2  vtest
4CV   0.160  1.284
5CV   0.626 -1.255
6CV   0.052  0.536
ETRA  0.038 -0.847
FRAN  0.038  0.498
CP1   0.255  1.288
CP2   0.131 -0.574
CP3   0.352 -1.281
CP4   0.223  0.655

Categorical variables (eta2)

      Dim.1  Dim.2  Dim.3
FISC  0.918  0.146  0.628
MARQ  0.001  0.895  0.038
PRIX  0.929  0.364  0.705

Supplementary categories

      Dim.1   cos2  v.test  Dim.2   cos2  v.test  Dim.3   cos2  v.test
4CV  -2.136  0.879  -4.230 -0.389  0.029  -1.150  0.637  0.078   2.042
5CV  -0.230  0.006  -0.226  1.316  0.192   1.927 -2.544  0.717  -4.036
6CV   3.213  0.963   4.670 -0.170  0.003  -0.369  0.494  0.023   1.161
ETRA  0.044  0.001   0.117 -1.204  0.948  -4.823 -0.230  0.034  -0.996
FRAN -0.074  0.001  -0.117  2.047  0.948   4.823  0.390  0.034   0.996
CP1  -2.272  0.756  -3.581 -0.654  0.063  -1.540  1.008  0.149   2.573
CP2  -1.598  0.288  -1.566  1.569  0.278   2.298 -1.164  0.153  -1.845
CP3   1.873  0.511   2.498 -0.766  0.085  -1.527 -1.401  0.286  -3.025
CP4   3.931  0.727   3.370  1.205  0.068   1.543  1.736  0.142   2.409

Supplementary categorical variables (eta2)

       Dim.1  Dim.2  Dim.3
FISC2  0.918  0.146  0.628
MARQ2  0.001  0.895  0.038
PRIX2  0.929  0.364  0.705

In [46]:
summaryMPCA(res_mpca3)

                     Mixed Principal Components Analysis - Results

Importance of components
                          Dim.1   Dim.2   Dim.3   Dim.4   Dim.5
Variance                  6.154   2.756   2.349   1.210   0.937
Difference                3.398   0.407   1.139   0.273   0.129
% of var.                41.024  18.372  15.659   8.064   6.247
Cumulative of % of var.  41.024  59.397  75.056  83.120  89.366

Individuals (the 10 first)

     Dim.1    ctr   cos2  Dim.2    ctr   cos2  Dim.3    ctr   cos2
AS2 -2.627  4.153  0.394 -1.700  3.886  0.165  1.404  3.108  0.112
CI4 -2.397  3.459  0.395  0.966  1.254  0.064  1.758  4.876  0.212
PE6 -1.631  1.602  0.209  2.247  6.787  0.397  0.330  0.171  0.009
FI3 -2.087  2.620  0.549 -1.103  1.634  0.153  0.838  1.107  0.089
FI5 -1.770  1.885  0.299 -0.132  0.023  0.002 -0.580  0.531  0.032
FI8  3.766  8.537  0.686 -0.662  0.589  0.021  1.355  2.896  0.089
FID  2.161  2.811  0.520 -1.273  2.177  0.180 -0.715  0.807  0.057
FO1 -1.796  1.941  0.474 -1.234  2.046  0.224  0.752  0.893  0.083
RE7  4.003  9.643  0.648  1.816  4.431  0.133  1.850  5.398  0.138
NI1 -1.913  2.202  0.355 -1.765  4.185  0.302  0.131  0.027  0.002

Supplementary individuals (the 10 first)

      Dim.1   cos2  Dim.2   cos2  Dim.3   cos2
AS22 -2.627  0.394 -1.700  0.165  1.404  0.112
CI42 -2.397  0.395  0.966  0.064  1.758  0.212
PE62 -1.631  0.209  2.247  0.397  0.330  0.009
FI32 -2.087  0.549 -1.103  0.153  0.838  0.089
FI52 -1.770  0.299 -0.132  0.002 -0.580  0.032
FI82  3.766  0.686 -0.662  0.021  1.355  0.089
FID2  2.161  0.520 -1.273  0.180 -0.715  0.057
FO12 -1.796  0.474 -1.234  0.224  0.752  0.083
RE72  4.003  0.648  1.816  0.133  1.850  0.138
NI12 -1.913  0.355 -1.765  0.302  0.131  0.002

Continuous variables

      Dim.1     ctr   cos2  Dim.2    ctr   cos2  Dim.3    ctr   cos2
CONS  0.859  11.991  0.738 -0.118  0.502  0.014  0.346  5.094  0.120
CYLI  0.950  14.680  0.903  0.068  0.166  0.005 -0.059  0.150  0.004
VITE  0.928  14.005  0.862 -0.101  0.372  0.010  0.103  0.453  0.011
VOLU  0.152   0.375  0.023  0.375  5.112  0.141  0.477  9.668  0.227
RP/P -0.865  12.150  0.748  0.223  1.806  0.050 -0.010  0.004  0.000
LONG  0.292   1.386  0.085  0.270  2.639  0.073 -0.335  4.775  0.112

Categories

      Dim.1     ctr   cos2  vtest  Dim.2     ctr   cos2  vtest  Dim.3     ctr  \
4CV  -0.830  11.184  0.688 -1.643 -0.226   1.846  0.051 -0.668  0.400   6.827
5CV  -0.044   0.032  0.002 -0.043  0.378   5.184  0.143  0.553 -0.791  26.668
6CV   0.916  13.630  0.839  1.331 -0.072   0.190  0.005 -0.157  0.228   2.208
ETRA  0.023   0.009  0.001  0.061 -0.946  32.465  0.895 -3.788 -0.195   1.625
FRAN -0.023   0.009  0.001 -0.036  0.946  32.465  0.895  2.228  0.195   1.625
CP1  -0.702   8.017  0.493 -1.107 -0.302   3.310  0.091 -0.712  0.505  10.841
CP2  -0.307   1.533  0.094 -0.301  0.451   7.368  0.203  0.660 -0.362   5.577
CP3   0.490   3.901  0.240  0.653 -0.299   3.252  0.090 -0.597 -0.593  14.986
CP4   0.661   7.098  0.437  0.567  0.303   3.324  0.092  0.388  0.472   9.501

       cos2  vtest
4CV   0.160  1.284
5CV   0.626 -1.255
6CV   0.052  0.536
ETRA  0.038 -0.847
FRAN  0.038  0.498
CP1   0.255  1.288
CP2   0.131 -0.574
CP3   0.352 -1.281
CP4   0.223  0.655

Categorical variables (eta2)

      Dim.1  Dim.2  Dim.3
FISC  0.918  0.146  0.628
MARQ  0.001  0.895  0.038
PRIX  0.929  0.364  0.705

In [47]:
from scientisttools import dimdesc
Dimdesc = dimdesc(res_mpca)
Dimdesc.keys()

dict_keys(['Dim.1', 'Dim.2', 'Dim.3', 'Dim.4', 'Dim.5'])

In [48]:
Dimdesc["Dim.1"]

{'quanti':       correlation        pvalue
 CYLI     0.950441  3.425403e-14
 VITE     0.928352  3.042841e-12
 CONS     0.859012  9.770004e-09
 RP/P    -0.864684  6.038377e-09,
 'quali':       Sum. Intra  Sum. Inter        R2     F-stats  pvalue
 PRIX   11.879557  154.268986  0.928500   99.560015     0.0
 FISC   13.688248  152.460296  0.917614  133.656519     0.0}

In [49]:
Dimdesc2 = dimdesc(res_mpca2)
Dimdesc2.keys()

dict_keys(['Dim.1', 'Dim.2', 'Dim.3', 'Dim.4', 'Dim.5'])

In [50]:
Dimdesc3 = dimdesc(res_mpca3)
Dimdesc3.keys()

dict_keys(['Dim.1', 'Dim.2', 'Dim.3', 'Dim.4', 'Dim.5'])