# Partial PCA

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
# Load dataset
from scientisttools import load_body
data = load_body()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shoulder.girth  507 non-null    float64
 1   chest.girth     507 non-null    float64
 2   waist.girth     507 non-null    float64
 3   navel.girth     507 non-null    float64
 4   hip.girth       507 non-null    float64
 5   thigh.girth     507 non-null    float64
 6   bicep.girth     507 non-null    float64
 7   forearm.girth   507 non-null    float64
 8   knee.girth      507 non-null    float64
 9   calf.girth      507 non-null    float64
 10  ankle.girth     507 non-null    float64
 11  wrist.girth     507 non-null    float64
 12  weight          507 non-null    float64
 13  height          507 non-null    float64
 14  gender          507 non-null    object
dtypes: float64(14), object(1)
memory usage: 59.5+ KB

In [3]:
# Drop gender
body = data.drop(columns=["gender"])
body.columns = [x.replace(".","_") for x in body.columns]

In [4]:
# Concatenate
import pandas as pd
D = pd.concat((body,data.drop(columns=["weight","height"])),axis=1)
D.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shoulder_girth  507 non-null    float64
 1   chest_girth     507 non-null    float64
 2   waist_girth     507 non-null    float64
 3   navel_girth     507 non-null    float64
 4   hip_girth       507 non-null    float64
 5   thigh_girth     507 non-null    float64
 6   bicep_girth     507 non-null    float64
 7   forearm_girth   507 non-null    float64
 8   knee_girth      507 non-null    float64
 9   calf_girth      507 non-null    float64
 10  ankle_girth     507 non-null    float64
 11  wrist_girth     507 non-null    float64
 12  weight          507 non-null    float64
 13  height          507 non-null    float64
 14  shoulder.girth  507 non-null    float64
 15  chest.girth     507 non-null    float64
 16  waist.girth     507 non-null    float64
 17  navel.girth     507 non-null    float64
 18  hip.girth       507 non-null    float64
 19  thigh.girth     507 non-null    float64
 20  bicep.girth     507 non-null    float64
 21  forearm.girth   507 non-null    float64
 22  knee.girth      507 non-null    float64
 23  calf.girth      507 non-null    float64
 24  ankle.girth     507 non-null    float64
 25  wrist.girth     507 non-null    float64
 26  gender          507 non-null    object
dtypes: float64(26), object(1)
memory usage: 107.1+ KB

In [5]:
from scientisttools import PartialPCA
res_partialpca = PartialPCA(standardize=True,partial=["weight","height"],quanti_sup=list(range(14,26)),quali_sup=26,parallelize=False)
res_partialpca.fit(D)

PartialPCA(partial=['weight', 'height'], quali_sup=26,
           quanti_sup=[14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

## Eigenvalues

In [6]:
res_partialpca.eig_

        eigenvalue  difference  proportion  cumulative
Dim.1     4.431024    2.099932   36.925197   36.925197
Dim.2     2.331092    1.081100   19.425765   56.350961
Dim.3     1.249992    0.189688   10.416597   66.767558
Dim.4     1.060304    0.481427    8.835865   75.603423
Dim.5     0.578877    0.030628    4.823974   80.427397
Dim.6     0.548249    0.069588    4.568738   84.996135
Dim.7     0.478660    0.105026    3.988836   88.984971
Dim.8     0.373634    0.037169    3.113617   92.098587
Dim.9     0.336465    0.061691    2.803874   94.902462
Dim.10    0.274774    0.090666    2.289782   97.192243
Dim.11    0.184108    0.031285    1.534231   98.726474
Dim.12    0.152823         NaN    1.273526  100.000000

## Individuals informations

In [7]:
# Individuals informations
ind = res_partialpca.ind_
ind.keys()

dict_keys(['coord', 'cos2', 'contrib', 'infos'])

In [8]:
# Individuals coordinates
ind["coord"].head(6)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
0  1.337784  1.497947 -0.227617 -0.664201 -0.596579
1  1.927503  1.274232  1.178204 -0.774523 -0.660382
2 -0.703805 -0.665354 -1.160614  0.397857  0.010186
3 -0.535374 -0.399563 -0.029212 -0.697962 -0.490187
4 -0.816964  1.455011  0.121039 -0.915111 -1.233306
5  1.450843  0.305848  0.082057  0.245470  1.125245

In [9]:
# Individuals contributions
ind["contrib"].head(6)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
0  0.079664  0.189856  0.008175  0.082066  0.121267
1  0.165378  0.137382  0.219041  0.111591  0.148593
2  0.022049  0.037457  0.212550  0.029445  0.000035
3  0.012759  0.013508  0.000135  0.090620  0.081871
4  0.029709  0.179129  0.002312  0.155779  0.518260
5  0.093698  0.007915  0.001062  0.011209  0.431420

In [10]:
# Individuals square cosinus (cos2)
ind["cos2"].head(6)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
0  0.227896  0.285731  0.006597  0.056178  0.045321
1  0.387712  0.169440  0.144864  0.062602  0.045510
2  0.105971  0.094708  0.288175  0.033864  0.000022
3  0.077346  0.043082  0.000230  0.131458  0.064840
4  0.098451  0.312281  0.002161  0.123527  0.224365
5  0.411084  0.018268  0.001315  0.011768  0.247277

In [11]:
# Individuals additionals informations
ind["infos"].head(6)

     Weight  Sq. Dist.   Inertia
0  0.001972   7.852995  0.015489
1  0.001972   9.582555  0.018901
2  0.001972   4.674321  0.009220
3  0.001972   3.705758  0.007309
4  0.001972   6.779325  0.013371
5  0.001972   5.120476  0.010100

## Variables informations

In [12]:
# Variables informations
var = res_partialpca.var_
var.keys()

dict_keys(['coord', 'cor', 'cos2', 'contrib', 'infos'])

In [13]:
# Variables coordinates
var["coord"].head(6)

                   Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
shoulder_girth  0.774720  0.057639  0.042945  0.161424  0.492250
chest_girth     0.792629 -0.200842  0.208610  0.180338  0.271366
waist_girth     0.318691 -0.562922  0.520454 -0.307305  0.093834
navel_girth    -0.412455 -0.403948  0.684019  0.216657 -0.120601
hip_girth      -0.745999 -0.019537  0.329182  0.415724  0.029121
thigh_girth    -0.706047  0.273335 -0.060839  0.526376  0.113801

In [14]:
# Variables contributions
var["contrib"].head(6)

                    Dim.1      Dim.2      Dim.3      Dim.4      Dim.5
shoulder_girth  13.545218   0.142517   0.147545   2.457578  41.858710
chest_girth     14.178688   1.730419   3.481468   3.067229  12.721068
waist_girth      2.292111  13.593671  21.669929   8.906519   1.521023
navel_girth      3.839276   6.999891  37.430773   4.427063   2.512542
hip_girth       12.559496   0.016374   8.668898  16.299742   0.146500
thigh_girth     11.250276   3.205016   0.296112  26.131372   2.237188

In [15]:
# Variables square cosinus (cos2)
var["cos2"].head(6)

                   Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
shoulder_girth  0.600192  0.003322  0.001844  0.026058  0.242310
chest_girth     0.628261  0.040338  0.043518  0.032522  0.073639
waist_girth     0.101564  0.316881  0.270872  0.094436  0.008805
navel_girth     0.170119  0.163174  0.467882  0.046940  0.014545
hip_girth       0.556514  0.000382  0.108360  0.172827  0.000848
thigh_girth     0.498502  0.074712  0.003701  0.277072  0.012951

## Linear models informations

In [16]:
# Linear models results
res_partialpca.others_["ols"]

                 intercept    weight    height        R2   Adj. R2      RMSE
shoulder_girth   50.018877  0.642596  0.080297  0.774923  0.774030  4.917200
chest_girth      54.429940  0.704420 -0.057293  0.809531  0.808775  4.372017
waist_girth      56.750176  0.862360 -0.230220  0.835975  0.835324  4.455740
navel_girth     106.366311  0.708596 -0.407319  0.586939  0.585300  6.050894
hip_girth       111.845008  0.536280 -0.305279  0.671834  0.670532  3.823270
thigh_girth      81.763530  0.327059 -0.277679  0.478536  0.476467  3.217417
bicep_girth      16.309711  0.291429 -0.030920  0.753398  0.752419  2.106909
forearm_girth    10.549518  0.174624  0.019391  0.758139  0.757179  1.390688
knee_girth       28.921817  0.169061 -0.025762  0.637064  0.635624  1.575377
calf_girth       33.145007  0.195397 -0.061807  0.612035  0.610495  1.771968
ankle_girth      13.453761  0.101317  0.009920  0.581861  0.580201  1.203068
wrist_girth       5.925035  0.068407  0.031799  0.689435  0.688202  0.768811

## Others informations

In [17]:
# Others informations
others = res_partialpca.others_

In [18]:
# Correlation
others["corr"]

,shoulder_girth,chest_girth,waist_girth,navel_girth,hip_girth,thigh_girth,bicep_girth,forearm_girth,knee_girth,calf_girth,ankle_girth,wrist_girth,weight,height
shoulder_girth,1.000000,0.927192,0.823455,0.515466,0.533672,0.323427,0.895188,0.894984,0.624783,0.627054,0.679757,0.840709,0.878834,0.665735
chest_girth,0.927192,1.000000,0.883799,0.622982,0.583499,0.363051,0.908185,0.887591,0.614055,0.608864,0.669140,0.824675,0.898959,0.618731
waist_girth,0.823455,0.883799,1.000000,0.754770,0.692351,0.421085,0.804704,0.780792,0.658207,0.631345,0.655889,0.728981,0.903991,0.552960
navel_girth,0.515466,0.622982,0.754770,1.000000,0.825892,0.602643,0.557807,0.486218,0.612093,0.524779,0.519479,0.435420,0.711816,0.313197
hip_girth,0.533672,0.583499,0.692351,0.825892,1.000000,0.828941,0.559885,0.514358,0.734902,0.674580,0.577043,0.458857,0.762969,0.338584
thigh_girth,0.323427,0.363051,0.421085,0.602643,0.828941,1.000000,0.411458,0.345285,0.638440,0.628890,0.421769,0.241610,0.558563,0.116310
bicep_girth,0.895188,0.908185,0.804704,0.557807,0.559885,0.411458,1.000000,0.942376,0.620730,0.637404,0.669324,0.847944,0.866672,0.588415
forearm_girth,0.894984,0.887591,0.780792,0.486218,0.514358,0.345285,0.942376,1.000000,0.657545,0.670192,0.712554,0.904709,0.869553,0.655018
knee_girth,0.624783,0.614055,0.658207,0.612093,0.734902,0.638440,0.620730,0.657545,1.000000,0.795828,0.737715,0.640960,0.795552,0.525702
calf_girth,0.627054,0.608864,0.631345,0.524779,0.674580,0.628890,0.637404,0.670192,0.795828,1.000000,0.762222,0.647627,0.769283,0.452683
ankle_girth,0.679757,0.669140,0.655889,0.519479,0.577043,0.421769,0.669324,0.712554,0.737715,0.762222,1.000000,0.753636,0.761998,0.570910
wrist_girth,0.840709,0.824675,0.728981,0.435420,0.458857,0.241610,0.847944,0.904709,0.640960,0.647627,0.753636,1.000000,0.816488,0.690834
weight,0.878834,0.898959,0.903991,0.711816,0.762969,0.558563,0.866672,0.869553,0.795552,0.769283,0.761998,0.816488,1.000000,0.717301
height,0.665735,0.618731,0.552960,0.313197,0.338584,0.116310,0.588415,0.655018,0.525702,0.452683,0.570910,0.690834,0.717301,1.000000

In [19]:
# Partial correlation
others["partial_corr"]

,shoulder_girth,chest_girth,waist_girth,navel_girth,hip_girth,thigh_girth,bicep_girth,forearm_girth,knee_girth,calf_girth,ankle_girth,wrist_girth,weight,height
shoulder_girth,1.000000,0.443657,0.014348,-0.235799,0.084115,-0.133144,0.169179,0.041769,0.036599,0.027536,0.012728,0.004142,0.117293,0.042063
chest_girth,0.443657,1.000000,0.182541,0.159320,-0.131814,-0.005278,0.184323,0.034058,-0.144815,-0.145499,0.018104,0.072085,0.242247,-0.156886
waist_girth,0.014348,0.182541,1.000000,0.294053,0.035455,-0.358264,-0.007908,-0.077576,-0.039530,-0.026990,-0.027199,-0.018220,0.532277,-0.383228
navel_girth,-0.235799,0.159320,0.294053,1.000000,0.481708,-0.115249,0.147908,-0.137464,0.084687,-0.117375,0.096089,-0.078794,0.002304,-0.037936
hip_girth,0.084115,-0.131814,0.035455,0.481708,1.000000,0.567350,-0.133947,-0.061972,0.033976,-0.070663,0.008850,0.113504,0.242358,-0.098923
thigh_girth,-0.133144,-0.005278,-0.358264,-0.115249,0.567350,1.000000,0.257886,-0.078429,0.150253,0.198044,-0.055020,-0.249028,0.265020,-0.304335
bicep_girth,0.169179,0.184323,-0.007908,0.147908,-0.133947,0.257886,1.000000,0.595144,-0.153330,-0.074641,-0.031959,0.072760,0.028870,-0.093267
forearm_girth,0.041769,0.034058,-0.077576,-0.137464,-0.061972,-0.078429,0.595144,1.000000,0.106670,0.060436,-0.025943,0.377989,0.172209,-0.065577
knee_girth,0.036599,-0.144815,-0.039530,0.084687,0.033976,0.150253,-0.153330,0.106670,1.000000,0.213372,0.177433,0.084406,0.172655,0.016819
calf_girth,0.027536,-0.145499,-0.026990,-0.117375,-0.070663,0.198044,-0.074641,0.060436,0.213372,1.000000,0.336593,0.075868,0.251329,-0.227205
ankle_girth,0.012728,0.018104,-0.027199,0.096089,0.008850,-0.055020,-0.031959,-0.025943,0.177433,0.336593,1.000000,0.281699,-0.004343,0.051897
wrist_girth,0.004142,0.072085,-0.018220,-0.078794,0.113504,-0.249028,0.072760,0.377989,0.084406,0.075868,0.281699,1.000000,-0.027124,0.129205
weight,0.117293,0.242247,0.532277,0.002304,0.242358,0.265020,0.028870,0.172209,0.172655,0.251329,-0.004343,-0.027124,1.000000,0.687712
height,0.042063,-0.156886,-0.383228,-0.037936,-0.098923,-0.304335,-0.093267,-0.065577,0.016819,-0.227205,0.051897,0.129205,0.687712,1.000000

In [20]:
# Global KMO
others["global_kmo"]

0.915799142804101

In [21]:
# KMO per variables
others["kmo_per_var"]

shoulder_girth    0.955327
chest_girth       0.942379
waist_girth       0.908691
navel_girth       0.902153
hip_girth         0.884704
thigh_girth       0.787021
bicep_girth       0.925049
forearm_girth     0.923929
knee_girth        0.966256
calf_girth        0.937876
ankle_girth       0.959092
wrist_girth       0.949347
weight            0.884586
height            0.824965
Name: KMO, dtype: float64

In [22]:
# Normalized coefficients
others["normalized_coef"]

                  weight    height
shoulder_girth  0.826609  0.072808
chest_girth     0.937513 -0.053748
waist_girth     1.045053 -0.196657
navel_girth     1.003462 -0.406588
hip_girth       1.071318 -0.429873
thigh_girth     0.978690 -0.585706
bicep_girth     0.915799 -0.068489
forearm_girth   0.823327  0.064444
knee_girth      0.861964 -0.092586
calf_girth      0.915740 -0.204179
ankle_girth     0.726055  0.050110
wrist_girth     0.661104  0.216624

## Supplementary elements

### Supplementary quantitatives variables

In [23]:
quanti_sup = res_partialpca.quanti_sup_

In [24]:
# coordinates
quanti_sup["coord"].head(6)

                   Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
shoulder.girth  0.774720  0.057639  0.042945  0.161424  0.492250
chest.girth     0.792629 -0.200842  0.208610  0.180338  0.271366
waist.girth     0.318691 -0.562922  0.520454 -0.307305  0.093834
navel.girth    -0.412455 -0.403948  0.684019  0.216657 -0.120601
hip.girth      -0.745999 -0.019537  0.329182  0.415724  0.029121
thigh.girth    -0.706047  0.273335 -0.060839  0.526376  0.113801

In [25]:
# Cos2
quanti_sup["cos2"].head(6)

                   Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
shoulder.girth  0.600192  0.003322  0.001844  0.026058  0.242310
chest.girth     0.628261  0.040338  0.043518  0.032522  0.073639
waist.girth     0.101564  0.316881  0.270872  0.094436  0.008805
navel.girth     0.170119  0.163174  0.467882  0.046940  0.014545
hip.girth       0.556514  0.000382  0.108360  0.172827  0.000848
thigh.girth     0.498502  0.074712  0.003701  0.277072  0.012951

In [26]:
# Ols regression
quanti_sup["ols"]

                 intercept    weight    height        R2   Adj. R2      RMSE
shoulder.girth   50.018877  0.642596  0.080297  0.774923  0.774030  4.917200
chest.girth      54.429940  0.704420 -0.057293  0.809531  0.808775  4.372017
waist.girth      56.750176  0.862360 -0.230220  0.835975  0.835324  4.455740
navel.girth     106.366311  0.708596 -0.407319  0.586939  0.585300  6.050894
hip.girth       111.845008  0.536280 -0.305279  0.671834  0.670532  3.823270
thigh.girth      81.763530  0.327059 -0.277679  0.478536  0.476467  3.217417
bicep.girth      16.309711  0.291429 -0.030920  0.753398  0.752419  2.106909
forearm.girth    10.549518  0.174624  0.019391  0.758139  0.757179  1.390688
knee.girth       28.921817  0.169061 -0.025762  0.637064  0.635624  1.575377
calf.girth       33.145007  0.195397 -0.061807  0.612035  0.610495  1.771968
ankle.girth      13.453761  0.101317  0.009920  0.581861  0.580201  1.203068
wrist.girth       5.925035  0.068407  0.031799  0.689435  0.688202  0.768811

### Supplementary qualitatives

In [27]:
quali_sup = res_partialpca.quali_sup_

In [28]:
# Coordinates
quali_sup["coord"]

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
female -1.119138  0.019323 -0.012686  0.125060  0.001163
male    1.178040 -0.020340  0.013354 -0.131642 -0.001225

In [29]:
# Cos2
quali_sup["cos2"]

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
female  0.980542  0.000292  0.000126  0.012244  0.000001
male    0.980542  0.000292  0.000126  0.012244  0.000001

In [30]:
# Vtest
quali_sup["vtest"]

            Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
female -12.270014  0.292088 -0.261868  2.802964  0.035292
male    12.270014 -0.292088  0.261868 -2.802964 -0.035292

In [31]:
# eta2
quali_sup["eta2"]

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
gender  0.297536  0.000169  0.000136  0.015527  0.000002

In [32]:
# square distance
quali_sup["dist"]

female    1.277324
male      1.415318
Name: Sq. Dist., dtype: float64

In [33]:
res_partialpca.transform(body).head(6)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
0  1.337784  1.497947 -0.227617 -0.664201 -0.596579
1  1.927503  1.274232  1.178204 -0.774523 -0.660382
2 -0.703805 -0.665354 -1.160614  0.397857  0.010186
3 -0.535374 -0.399563 -0.029212 -0.697962 -0.490187
4 -0.816964  1.455011  0.121039 -0.915111 -1.233306
5  1.450843  0.305848  0.082057  0.245470  1.125245

In [34]:
res_partialpca.fit_transform(D).head(6)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
0  1.337784  1.497947 -0.227617 -0.664201 -0.596579
1  1.927503  1.274232  1.178204 -0.774523 -0.660382
2 -0.703805 -0.665354 -1.160614  0.397857  0.010186
3 -0.535374 -0.399563 -0.029212 -0.697962 -0.490187
4 -0.816964  1.455011  0.121039 -0.915111 -1.233306
5  1.450843  0.305848  0.082057  0.245470  1.125245

In [35]:
from scientisttools import predictPartialPCA
predict = predictPartialPCA(res_partialpca,X=body)
predict.keys()

dict_keys(['coord', 'cos2', 'dist'])

In [36]:
predict["coord"].head(6)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
0  1.337784  1.497947 -0.227617 -0.664201 -0.596579
1  1.927503  1.274232  1.178204 -0.774523 -0.660382
2 -0.703805 -0.665354 -1.160614  0.397857  0.010186
3 -0.535374 -0.399563 -0.029212 -0.697962 -0.490187
4 -0.816964  1.455011  0.121039 -0.915111 -1.233306
5  1.450843  0.305848  0.082057  0.245470  1.125245

In [37]:
predict["cos2"].head(6)

      Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
0  0.227896  0.285731  0.006597  0.056178  0.045321
1  0.387712  0.169440  0.144864  0.062602  0.045510
2  0.105971  0.094708  0.288175  0.033864  0.000022
3  0.077346  0.043082  0.000230  0.131458  0.064840
4  0.098451  0.312281  0.002161  0.123527  0.224365
5  0.411084  0.018268  0.001315  0.011768  0.247277

In [38]:
predict["dist"].head(6)

0    7.852995
1    9.582555
2    4.674321
3    3.705758
4    6.779325
5    5.120476
Name: Sq. Dist., dtype: float64

In [39]:
from scientisttools import splitmix, supvarPartialPCA
X = data.drop(columns=["weight","height"])
X_quanti = splitmix(X)["quanti"]
X_quali = splitmix(X)["quali"]
supvar = supvarPartialPCA(res_partialpca,X_quanti_sup=X_quanti,X_quali_sup=X_quali)

In [40]:
supvarquanti = supvar["quanti"]
# Coordinates
supvarquanti["coord"].head(6)

                   Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
shoulder.girth  0.774720  0.057639  0.042945  0.161424  0.492250
chest.girth     0.792629 -0.200842  0.208610  0.180338  0.271366
waist.girth     0.318691 -0.562922  0.520454 -0.307305  0.093834
navel.girth    -0.412455 -0.403948  0.684019  0.216657 -0.120601
hip.girth      -0.745999 -0.019537  0.329182  0.415724  0.029121
thigh.girth    -0.706047  0.273335 -0.060839  0.526376  0.113801

In [41]:
# square cosinus (cos2)
supvarquanti["cos2"].head(6)

                   Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
shoulder.girth  0.600192  0.003322  0.001844  0.026058  0.242310
chest.girth     0.628261  0.040338  0.043518  0.032522  0.073639
waist.girth     0.101564  0.316881  0.270872  0.094436  0.008805
navel.girth     0.170119  0.163174  0.467882  0.046940  0.014545
hip.girth       0.556514  0.000382  0.108360  0.172827  0.000848
thigh.girth     0.498502  0.074712  0.003701  0.277072  0.012951

In [42]:
# ols
supvarquanti["ols"].head(6)

                 intercept    weight    height        R2   Adj. R2      RMSE
shoulder.girth   50.018877  0.642596  0.080297  0.774923  0.774030  4.917200
chest.girth      54.429940  0.704420 -0.057293  0.809531  0.808775  4.372017
waist.girth      56.750176  0.862360 -0.230220  0.835975  0.835324  4.455740
navel.girth     106.366311  0.708596 -0.407319  0.586939  0.585300  6.050894
hip.girth       111.845008  0.536280 -0.305279  0.671834  0.670532  3.823270
thigh.girth      81.763530  0.327059 -0.277679  0.478536  0.476467  3.217417

#### Supplementary qualitatives

In [43]:
supvarquali = supvar["quali"]
# Coordinates
supvarquali["coord"]

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
female -1.119138  0.019323 -0.012686  0.125060  0.001163
male    1.178040 -0.020340  0.013354 -0.131642 -0.001225

In [44]:
# square cosinus (cos2)
supvarquali["cos2"]

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
female  0.980542  0.000292  0.000126  0.012244  0.000001
male    0.980542  0.000292  0.000126  0.012244  0.000001

In [45]:
# square distance
supvarquali["dist"]

female    1.277324
male      1.415318
Name: Sq. Dist., dtype: float64

In [46]:
# value - test
supvarquali["vtest"]

            Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
female -12.270014  0.292088 -0.261868  2.802964  0.035292
male    12.270014 -0.292088  0.261868 -2.802964 -0.035292

In [47]:
# Square correlation ratio
supvarquali["eta2"]

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
gender  0.297536  0.000169  0.000136  0.015527  0.000002

## Recode male

In [48]:
data2 = data.copy()
data2.gender = data2.gender.map({"male" : 1, "female" : 0}).astype("float")

In [49]:
res_partialpca2 = PartialPCA(standardize=True,partial=["weight","height","gender"],parallelize=False)
res_partialpca2.fit(data2)

PartialPCA(partial=['weight', 'height', 'gender'])

In [50]:
res_partialpca2.eig_

        eigenvalue  difference  proportion  cumulative
Dim.1     2.889848    0.416549   24.082070   24.082070
Dim.2     2.473299    0.880459   20.610828   44.692898
Dim.3     1.592840    0.256072   13.273667   57.966565
Dim.4     1.336768    0.520329   11.139731   69.106297
Dim.5     0.816439    0.216497    6.803657   75.909954
Dim.6     0.599942    0.050529    4.999516   80.909469
Dim.7     0.549413    0.079022    4.578441   85.487910
Dim.8     0.470391    0.069740    3.919924   89.407834
Dim.9     0.400651    0.040913    3.338757   92.746591
Dim.10    0.359738    0.080465    2.997815   95.744407
Dim.11    0.279273    0.047874    2.327272   98.071679
Dim.12    0.231399         NaN    1.928321  100.000000

In [51]:
res_partialpca2.var_["coord"]

                   Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
shoulder.girth  0.423750  0.533504  0.084608 -0.044379  0.623604
chest.girth     0.192310  0.770442  0.229867  0.055068  0.281532
waist.girth    -0.588026  0.293500  0.381443  0.388519  0.036237
navel.girth    -0.441364  0.169338  0.722247  0.189711 -0.170419
hip.girth      -0.223873 -0.338878  0.732900 -0.292393  0.051967
thigh.girth     0.189277 -0.486423  0.331216 -0.665842  0.129259
bicep.girth     0.626896  0.446891  0.270376 -0.306590 -0.215054
forearm.girth   0.806260  0.236216  0.126082 -0.102054 -0.309200
knee.girth      0.323133 -0.599292  0.208008  0.220276  0.150557
calf.girth      0.469070 -0.602490 -0.001083  0.202719  0.206125
ankle.girth     0.440531 -0.378579  0.235712  0.540328  0.112088
wrist.girth     0.696575  0.088608  0.176150  0.360564 -0.281000