# MFACT - predict & supvar

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
from scientisttools import load_mortality
mortality = load_mortality()
mortality.shape

(62, 18)

In [3]:
import pandas as pd
from scientisttools import MFACT
mortality2 = mortality.copy()
mortality2.columns = [x + "-2" for x in mortality2.columns]
dat = pd.concat((mortality,mortality2),axis=1)
res_mfact = MFACT(group=[9]*4,name_group=["1979","2006","1979-2","2006-2"],num_group_sup=[2,3],ind_sup=list(range(50,dat.shape[0])),parallelize=True)
res_mfact.fit(dat)

MFACT(group=[9, 9, 9, 9],
      ind_sup=[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61],
      name_group=['1979', '2006', '1979-2', '2006-2'], num_group_sup=[2, 3],
      parallelize=True)

## predict function

In [4]:
from scientisttools import predictMFACT
ind_sup = mortality.iloc[list(range(50,mortality.shape[0])),:]

### transform

In [5]:
# transform
res_mfact.transform(ind_sup).head(6)

,Dim.1,Dim.2,Dim.3,Dim.4,Dim.5
Other infectious diseases and parasites,-0.325731,0.157468,-0.291875,-0.172298,-0.199636
Other malignent tumours,1.163547,-0.241955,-0.126343,0.229662,0.240028
Other psychological and behavioural disorders,-1.733616,0.527912,0.398427,-0.745911,-0.919939
Other respiratory ailments,-0.917021,0.060218,0.044329,-0.104252,-0.011968
Other tumours,0.432077,0.207390,-0.302293,-0.126599,-0.263197
Pneumonia,-1.547383,0.375400,0.453367,-0.522505,-0.403540

### predict

In [6]:
# Coordinates with MFACT function
res_mfact.ind_sup_["coord"].head(6)

,Dim.1,Dim.2,Dim.3,Dim.4,Dim.5
Other infectious diseases and parasites,-0.325731,0.157468,-0.291875,-0.172298,-0.199636
Other malignent tumours,1.163547,-0.241955,-0.126343,0.229662,0.240028
Other psychological and behavioural disorders,-1.733616,0.527912,0.398427,-0.745911,-0.919939
Other respiratory ailments,-0.917021,0.060218,0.044329,-0.104252,-0.011968
Other tumours,0.432077,0.207390,-0.302293,-0.126599,-0.263197
Pneumonia,-1.547383,0.375400,0.453367,-0.522505,-0.403540

In [7]:
from scientisttools import predictMFACT
predict = predictMFACT(res_mfact,X=ind_sup)
predict.keys()

dict_keys(['coord', 'cos2', 'coord_partiel'])

In [8]:
# Coordinates with predictMFACT function
predict["coord"].head(6)

,Dim.1,Dim.2,Dim.3,Dim.4,Dim.5
Other infectious diseases and parasites,-0.325731,0.157468,-0.291875,-0.172298,-0.199636
Other malignent tumours,1.163547,-0.241955,-0.126343,0.229662,0.240028
Other psychological and behavioural disorders,-1.733616,0.527912,0.398427,-0.745911,-0.919939
Other respiratory ailments,-0.917021,0.060218,0.044329,-0.104252,-0.011968
Other tumours,0.432077,0.207390,-0.302293,-0.126599,-0.263197
Pneumonia,-1.547383,0.375400,0.453367,-0.522505,-0.403540

In [9]:
# Square cosinus with MFACT function
res_mfact.ind_sup_["cos2"].head(6) # à faire un check

,Dim.1,Dim.2,Dim.3,Dim.4,Dim.5
Other infectious diseases and parasites,0.000976,0.000228,0.000784,0.000273,0.000367
Other malignent tumours,0.012781,0.000553,0.000151,0.000498,0.000544
Other psychological and behavioural disorders,0.022692,0.002104,0.001199,0.004201,0.006390
Other respiratory ailments,0.007778,0.000034,0.000018,0.000101,0.000001
Other tumours,0.001758,0.000405,0.000860,0.000151,0.000652
Pneumonia,0.021304,0.001254,0.001829,0.002429,0.001449

In [10]:
# Square cosinus with predictMFACT function
predict["cos2"].head(6)

,Dim.1,Dim.2,Dim.3,Dim.4,Dim.5
Other infectious diseases and parasites,0.000976,0.000228,0.000784,0.000273,0.000367
Other malignent tumours,0.012781,0.000553,0.000151,0.000498,0.000544
Other psychological and behavioural disorders,0.022692,0.002104,0.001199,0.004201,0.006390
Other respiratory ailments,0.007778,0.000034,0.000018,0.000101,0.000001
Other tumours,0.001758,0.000405,0.000860,0.000151,0.000652
Pneumonia,0.021304,0.001254,0.001829,0.002429,0.001449

In [11]:
# Partiel coordinates with MFACT function
res_mfact.ind_sup_["coord_partiel"].head(6).round(4)

                                                  1979                  \
                                                 Dim.1   Dim.2   Dim.3
Other infectious diseases and parasites         0.0281  0.1656 -0.1866
Other malignent tumours                         0.8423 -0.0434 -0.2578
Other psychological and behavioural disorders  -0.6014 -0.0238  0.0973
Other respiratory ailments                     -0.7792 -0.0920  0.3121
Other tumours                                   0.8453  0.3015 -0.2525
Pneumonia                                      -0.9156  0.0409  0.5055

                                                                  2006  \
                                                 Dim.4   Dim.5   Dim.1
Other infectious diseases and parasites        -0.0508  0.0595 -0.6796
Other malignent tumours                        -0.4038 -0.6739  1.4848
Other psychological and behavioural disorders   0.3331  0.4192 -2.8658
Other respiratory ailments                      0.4205  0.6094 -1.0548
Other tumours                                  -0.5561 -0.4696  0.0189
Pneumonia                                       0.4008  0.7984 -2.1792


                                                 Dim.2   Dim.3   Dim.4   Dim.5
Other infectious diseases and parasites         0.1493 -0.3971 -0.2938 -0.4587
Other malignent tumours                        -0.4405  0.0051  0.8631  1.1540
Other psychological and behavioural disorders   1.0796  0.6995 -1.8249 -2.2591
Other respiratory ailments                      0.2124 -0.2234 -0.6290 -0.6334
Other tumours                                   0.1132 -0.3520  0.3029 -0.0568
Pneumonia                                       0.7099  0.4012 -1.4458 -1.6055

In [12]:
# Partiel coordinates with predictMFACT function
predict["coord_partiel"].head(6).round(4)

                                                  1979                  \
                                                 Dim.1   Dim.2   Dim.3
Other infectious diseases and parasites         0.0281  0.1656 -0.1866
Other malignent tumours                         0.8423 -0.0434 -0.2578
Other psychological and behavioural disorders  -0.6014 -0.0238  0.0973
Other respiratory ailments                     -0.7792 -0.0920  0.3121
Other tumours                                   0.8453  0.3015 -0.2525
Pneumonia                                      -0.9156  0.0409  0.5055

                                                                  2006  \
                                                 Dim.4   Dim.5   Dim.1
Other infectious diseases and parasites        -0.0508  0.0595 -0.6796
Other malignent tumours                        -0.4038 -0.6739  1.4848
Other psychological and behavioural disorders   0.3331  0.4192 -2.8658
Other respiratory ailments                      0.4205  0.6094 -1.0548
Other tumours                                  -0.5561 -0.4696  0.0189
Pneumonia                                       0.4008  0.7984 -2.1792


                                                 Dim.2   Dim.3   Dim.4   Dim.5
Other infectious diseases and parasites         0.1493 -0.3971 -0.2938 -0.4587
Other malignent tumours                        -0.4405  0.0051  0.8631  1.1540
Other psychological and behavioural disorders   1.0796  0.6995 -1.8249 -2.2591
Other respiratory ailments                      0.2124 -0.2234 -0.6290 -0.6334
Other tumours                                   0.1132 -0.3520  0.3029 -0.0568
Pneumonia                                       0.7099  0.4012 -1.4458 -1.6055

## supvar function

In [13]:
from scientisttools import supvarMFACT
X_group_sup = mortality2.iloc[:50,:]
supvar = supvarMFACT(res_mfact,X_group_sup=X_group_sup, group_sup=[9]*2,name_group_sup=["1979-2","2006-2"])
supvar.keys()

dict_keys(['group', 'partial_axes', 'freq'])

### Supplementary groups

In [14]:
# Coordinates with MFACT function
res_mfact.group_["coord_sup"].head(6)

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
1979-2  0.879146  0.549622  0.133389  0.063513  0.064215
2006-2  0.905345  0.369528  0.159236  0.147711  0.061893

In [15]:
# Coordinates with supvarMFACT function
supvar["group"]["coord"].head(6)

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
1979-2  0.879146  0.549622  0.133389  0.063513  0.064215
2006-2  0.905345  0.369528  0.159236  0.147711  0.061893

In [16]:
# Square cosinus with MFACT function
res_mfact.group_["cos2_sup"].head(6)

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
1979-2  0.577359  0.225659  0.013291  0.003013  0.003080
2006-2  0.658022  0.109624  0.020356  0.017516  0.003075

In [17]:
# Square cosinus with supvarMFACT function
supvar["group"]["cos2"].head(6)

           Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
1979-2  0.577359  0.225659  0.013291  0.003013  0.003080
2006-2  0.658022  0.109624  0.020356  0.017516  0.003075

In [18]:
# Square distance to origin with MFACT function
res_mfact.group_["dist2_sup"].head(6)

1979-2    1.338677
2006-2    1.245628
Name: Sq. Dist., dtype: float64

In [19]:
#Square distance to origin with supvarMFACT function
supvar["group"]["dist2"].head(6)

1979-2    1.338677
2006-2    1.245628
Name: Sq. Dist., dtype: float64

In [20]:
# Lg coefficients with MFACT function
res_mfact.group_["Lg"]

            1979      2006    1979-2    2006-2       MFA
1979    1.338677  0.797760  1.338677  0.797760  1.197225
2006    0.797760  1.245628  0.797760  1.245628  1.145082
1979-2  1.338677  0.797760  1.338677  0.797760  1.197225
2006-2  0.797760  1.245628  0.797760  1.245628  1.145082
MFA     1.197225  1.145082  1.197225  1.145082  1.312591

In [21]:
# Lg coefficients with supvarMFACT function
supvar["group"]["Lg"]

            1979      2006    1979-2    2006-2
1979    1.338677   0.79776  1.338677  0.797760
2006     0.79776  1.245628  0.797760  1.245628
1979-2  1.338677   0.79776  1.338677  0.797760
2006-2   0.79776  1.245628  0.797760  1.245628

In [22]:
# RV coefficients with MFACT function
res_mfact.group_["RV"]

            1979      2006    1979-2    2006-2       MFA
1979    1.000000  0.617789  1.000000  0.617789  0.903178
2006    0.617789  1.000000  0.617789  1.000000  0.895525
1979-2  1.000000  0.617789  1.000000  0.617789  0.903178
2006-2  0.617789  1.000000  0.617789  1.000000  0.895525
MFA     0.903178  0.895525  0.903178  0.895525  1.000000

In [23]:
# RV coeffcient with supvarMFACT function
supvar["group"]["RV"]

            1979      2006    1979-2    2006-2
1979    1.000000  0.617789  1.000000  0.617789
2006    0.617789  1.000000  0.617789  1.000000
1979-2  1.000000  0.617789  1.000000  0.617789
2006-2  0.617789  1.000000  0.617789  1.000000

### Partial axes

In [24]:
# Coordinates with MFACT function
res_mfact.partial_axes_["coord"].head(6)

           1979                                              2006            \
          Dim.1     Dim.2     Dim.3     Dim.4     Dim.5     Dim.1     Dim.2
Dim.1  0.908502 -0.307206  0.052472  0.014890  0.062142  0.948649  0.103569
Dim.2  0.310982  0.895289  0.057300 -0.057190 -0.042117 -0.178001  0.853136
Dim.3 -0.106932 -0.086129  0.922375 -0.010357 -0.011781  0.067478  0.221197
Dim.4 -0.225324 -0.117626 -0.172319 -0.125729  0.115816  0.176771  0.415056
Dim.5 -0.119077  0.277980  0.095619  0.308084  0.329838  0.174094 -0.192089

                                       1979-2                                \
          Dim.3     Dim.4     Dim.5     Dim.1     Dim.2     Dim.3     Dim.4
Dim.1  0.011243 -0.048121  0.100164  0.908502 -0.307206  0.052472  0.014890
Dim.2 -0.028407  0.096679  0.218827  0.310982  0.895289  0.057300 -0.057190
Dim.3  0.869336  0.032273 -0.187042 -0.106932 -0.086129  0.922375 -0.010357
Dim.4 -0.428572 -0.025160 -0.387769 -0.225324 -0.117626 -0.172319 -0.125729
Dim.5 -0.024005  0.568223  0.071968 -0.119077  0.277980  0.095619  0.308084

                   2006-2
          Dim.5     Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Dim.1  0.062142  0.948649  0.103569  0.011243 -0.048121  0.100164
Dim.2 -0.042117 -0.178001  0.853136 -0.028407  0.096679  0.218827
Dim.3 -0.011781  0.067478  0.221197  0.869336  0.032273 -0.187042
Dim.4  0.115816  0.176771  0.415056 -0.428572 -0.025160 -0.387769
Dim.5  0.329838  0.174094 -0.192089 -0.024005  0.568223  0.071968

In [25]:
# Coordinates with supvarMFACT function
supvar["partial_axes"]["coord"].head(6)

         1979-2                                            2006-2            \
          Dim.1     Dim.2     Dim.3     Dim.4     Dim.5     Dim.1     Dim.2
Dim.1  0.908502 -0.307206  0.052472  0.014890  0.062142  0.948649  0.103569
Dim.2  0.310982  0.895289  0.057300 -0.057190 -0.042117 -0.178001  0.853136
Dim.3 -0.106932 -0.086129  0.922375 -0.010357 -0.011781  0.067478  0.221197
Dim.4 -0.225324 -0.117626 -0.172319 -0.125729  0.115816  0.176771  0.415056
Dim.5 -0.119077  0.277980  0.095619  0.308084  0.329838  0.174094 -0.192089


          Dim.3     Dim.4     Dim.5
Dim.1  0.011243 -0.048121  0.100164
Dim.2 -0.028407  0.096679  0.218827
Dim.3  0.869336  0.032273 -0.187042
Dim.4 -0.428572 -0.025160 -0.387769
Dim.5 -0.024005  0.568223  0.071968

In [26]:
# Square cosinus with MFACT function
res_mfact.partial_axes_["cos2"].head(6)

           1979                                              2006            \
          Dim.1     Dim.2     Dim.3     Dim.4     Dim.5     Dim.1     Dim.2
Dim.1  0.825376  0.094376  0.002753  0.000222  0.003862  0.899935  0.010727
Dim.2  0.096710  0.801542  0.003283  0.003271  0.001774  0.031684  0.727841
Dim.3  0.011434  0.007418  0.850776  0.000107  0.000139  0.004553  0.048928
Dim.4  0.050771  0.013836  0.029694  0.015808  0.013413  0.031248  0.172271
Dim.5  0.014179  0.077273  0.009143  0.094916  0.108793  0.030309  0.036898

                                       1979-2                                \
          Dim.3     Dim.4     Dim.5     Dim.1     Dim.2     Dim.3     Dim.4
Dim.1  0.000126  0.002316  0.010033  0.825376  0.094376  0.002753  0.000222
Dim.2  0.000807  0.009347  0.047885  0.096710  0.801542  0.003283  0.003271
Dim.3  0.755745  0.001042  0.034985  0.011434  0.007418  0.850776  0.000107
Dim.4  0.183674  0.000633  0.150365  0.050771  0.013836  0.029694  0.015808
Dim.5  0.000576  0.322877  0.005179  0.014179  0.077273  0.009143  0.094916

                   2006-2
          Dim.5     Dim.1     Dim.2     Dim.3     Dim.4     Dim.5
Dim.1  0.003862  0.899935  0.010727  0.000126  0.002316  0.010033
Dim.2  0.001774  0.031684  0.727841  0.000807  0.009347  0.047885
Dim.3  0.000139  0.004553  0.048928  0.755745  0.001042  0.034985
Dim.4  0.013413  0.031248  0.172271  0.183674  0.000633  0.150365
Dim.5  0.108793  0.030309  0.036898  0.000576  0.322877  0.005179

In [27]:
# Square cosinus with supvarMFACT function